README.md
jenkins_pipelines/Jenkinsfile_prs_changelog
jenkins_pipelines/README.md

this PR has the goal to convert some jenkins job into pipeline, and create the initial structure.
As small step,   i will adress the changelog-pr test ( which is composed from 2 jobs (trigger + test) and decompose it to 1 pipeline with 2 stages).

Init Pipelines jenkins for susemanager ci

---

jenkins_pipelines/Jenkinsfile_prs_changelog
jenkins_pipelines/Jenkinsfile_prs_java_checkstyle
jenkins_pipelines/Jenkinsfile_prs_psql_unit

add postactions

---

jenkins_pipelines/Jenkinsfile_prs_backend_unitpsql
jenkins_pipelines/Jenkinsfile_prs_build_rpms
jenkins_pipelines/Jenkinsfile_prs_java_checkstyle

connvert all PRs namespace jobs into pipelines in git 

---

jenkins_pipelines/Jenkinsfile_prs_susemanager_unittest

Add susemanager_unittest pipeline

---

jenkins_pipelines/performance_testsuite/Jenkinsfile_performance_testsuite

Fix type in https://github.com/SUSE/susemanager-ci/pull/16/

Change the jenkins job scheduling for the performance testsuite to run every 2 hours

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog

So after the changelog test passes (it doesn't matter the result), merging for the PR will be enabled.

Enable PR merging on changelog tests

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog

It seems that using the pipe does not work as I expected in two lines.

Run changelog test and save variable at a single line

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint

JavaScript pipeline to run ESLint and Flow on PRs.

Javascript Lint pipeline

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unitpsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_checkstyle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/manager_prs/Jenkinsfile_prs_psql_unit
jenkins_pipelines/manager_prs/Jenkinsfile_prs_rubocop
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_oracle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_postgre
jenkins_pipelines/manager_prs/Jenkinsfile_prs_sql_standard_name
jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittest
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unitpsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_checkstyle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_rubocop
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_oracle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_postgre
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_sql_standard_name
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittest

It will revert the line removed to run the cleanWs only when the job finish successfully.

[6376] PR#30 fix

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_psql_unit

Task : https://github.com/SUSE/spacewalk/issues/6376

[6376] Fix Junit report not running when testsuite has fails

---

jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog_test
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_oracle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests

Porting the new pipeline to Uyuni, and fixing job trigger to be asynchron.

PR check pipeline for Uyuni

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_oracle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog_test
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests

The parameters section was duplicated in several jenkins pipelines, after adding the new GITARRO_PR_NUMBER parameter. So, to fix it I merged both sections

Fix parameters section duplicated

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_oracle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint

It was missing a script section in a pair pipelines

Fix script section

---

jenkins_pipelines/manager_prs/Jenkinsfile_testsuite

Finishing stage moved to always, so we always generated the tarball.
A condition was added too, we don't generate tarball either report if the deployment failed.

Finishing stage moved to always

---

jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_spacecmd_unittests

Add jenkins runner for spacecmd tests

Add jenkins job for running spacecmd unit tests

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint

Fix the package used by javascript_lint from js/ to web/

Fix the package used by javascript_lint from js/ to web/

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_setup
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_testsuite

We will have two pipelines, one for deployment, core features, and sync products.
Another for bootstrap clients and perform smoke tests.

QAM TestSuite Pipeline

---

jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite

That change will fix the issue in Head and Uyuni testsuite, after the change made in the Rakefile of spacewalk.

Changing pipeline to support new rake tasks

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_oracle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests
jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequencial_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_setup
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_testsuite
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog_test
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_spacecmd_unittests
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests
jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_sequencial_testsuite
jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite

https://github.com/SUSE/spacewalk/issues/9908 will be probably fixed by this.

Use synchronous workspace cleaning

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequencial_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite

Add a variable to allow specify the terraform version to run the test. Needed in the context of upgrading terraform for version 0.12.
We always set the var TERRAFORM. The script that use it, should have a fall back if no value is set

Terraform 012 enablement

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_setup

Add sumaform_branch as param to be injected into test-runner for deployment stability purpose.
Our sumaform changes in master are not stable at all!

Add sumaform branch as param in QAM deployment

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequencial_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite

add parameter for test runner branch

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequencial_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite

Allow configure terraform plugins folder to use. Need for 0.12 migration.

configure terraform plugins folder

---

jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_sequencial_testsuite
jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite

Add new branch parameters to uyuni pipeline

add new branch parameters to uyuni pipeline

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequencial_testsuite

This PR re-enables the reposync stage.
Tested, to be merged after uyuni-project/uyuni#1666 is merged.

Re-enable reposync

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_setup
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_testsuite

Our QAM Pipelines are enough stable now to be merged.

Automated QAM pipelines

---

jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequential_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_setup
jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_testsuite
jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_sequential_testsuite
jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite

To synch. with the new code in sumaform-test-runner where the export of artifacts it's made in a different script

Exporting artifacts at the finish stage

---

jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_sequential_testsuite

If we are to skip features or scenarios, let's do it at test suite level (with cucumber tags), but not at pipelines level.

Run reposync features on Uyuni too

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

3.2 and 4.0 will follow if this works fine for a few builds.

Add 2 CPUs for CentOS on Head, Uyuni and Test environments

---

jenkins_pipelines/manager_prs/tests_files/rubocop.sh

Related to https://github.com/SUSE/spacewalk/pull/11521

Update rubocop matching ruby 2.5

---

terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

Update terraform config. files to use the new min-build VM.
(This PR complements https://github.com/uyuni-project/uyuni/pull/2198)

Setup min-build VM

---

terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf

Setup the min-build VM at the Provo CI.

Setup min-build VM at Provo

---

terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

**This PR is going to be merged to private branch only.**

Move buildhost and pxeboot VM to sle15sp2

---

terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

Change all TF files to use the official JeOS SLES15SP2 images

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint

Also watch for `yarn.lock` changes to trigger `javascript_lint` tests

javascript_lint needs to be triggered on yarn.lock changes too

---

terracumber_config/tf_files/SUSEManager-3.2-NUE.tf

Change 3.2 to cokerunner

---

jenkins_pipelines/environments/manager-3.2-cucumber-NUE
jenkins_pipelines/environments/manager-3.2-cucumber-PRV
jenkins_pipelines/environments/manager-3.2-reference-PRV
jenkins_pipelines/environments/manager-4.0-cucumber-NUE
jenkins_pipelines/environments/manager-4.0-cucumber-PRV
jenkins_pipelines/environments/manager-4.0-qam-cucumber
jenkins_pipelines/environments/manager-4.0-reference-NUE
jenkins_pipelines/environments/manager-4.0-reference-PRV
jenkins_pipelines/environments/manager-4.1-cucumber-NUE
jenkins_pipelines/environments/manager-4.1-cucumber-PRV
jenkins_pipelines/environments/manager-4.1-qam-cucumber
jenkins_pipelines/environments/manager-4.1-qam-setup-cucumber
jenkins_pipelines/environments/manager-4.1-reference-PRV
jenkins_pipelines/environments/manager-Head-cucumber-NUE
jenkins_pipelines/environments/manager-Head-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
jenkins_pipelines/environments/manager-TEST-Naica-cucumber
jenkins_pipelines/environments/manager-TEST-Orion-cucumber
jenkins_pipelines/environments/manager-TEST-cucumber
jenkins_pipelines/environments/uyuni-master-cucumber-NUE

Back to Julio's repository and master branch

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf

New images centos 6, centos 7, centos 8, ubuntu 16, ubuntu 18, ubuntu 20. Some of them are new products, others needed fixing because they were commented out and obsolete settings. My recommendation is to just try to deploy this from my fork and see if it works. I haven't tested it because I don't have the computing power.
Fixes https://github.com/SUSE/spacewalk/issues/9360

Qam new images

---

jenkins_pipelines/environments/manager-4.0-cucumber-PRV
jenkins_pipelines/environments/manager-4.1-cucumber-PRV
jenkins_pipelines/environments/manager-Head-cucumber-NUE
jenkins_pipelines/environments/uyuni-master-cucumber-NUE

For 4.0, head, uyuni and 4.1 use the branch disable-sles15sp1o
from https://github.com/calancha/sumaform.git

Temporary use sumaform custom branch at the testsuites

---

jenkins_pipelines/environments/manager-4.0-cucumber-PRV
jenkins_pipelines/environments/manager-4.1-cucumber-PRV
jenkins_pipelines/environments/manager-Head-cucumber-NUE
jenkins_pipelines/environments/uyuni-master-cucumber-NUE

Run test suite back with sumaform from uyuni-project and well tested images.
This reverts commit 9e655f86ca84e8223f7a34b11787170b2db369ca.

Revert "Temporary use sumaform custom branch at the testsuites"

---

jenkins_pipelines/environments/manager-3.2-cucumber-NUE
jenkins_pipelines/environments/manager-3.2-cucumber-PRV
jenkins_pipelines/environments/manager-3.2-reference-PRV
jenkins_pipelines/environments/manager-4.0-cucumber-NUE
jenkins_pipelines/environments/manager-4.0-cucumber-PRV
jenkins_pipelines/environments/manager-4.0-reference-NUE
jenkins_pipelines/environments/manager-4.0-reference-PRV
jenkins_pipelines/environments/manager-4.1-cucumber-NUE
jenkins_pipelines/environments/manager-4.1-cucumber-PRV
jenkins_pipelines/environments/manager-4.1-qam-cucumber
jenkins_pipelines/environments/manager-4.1-reference-PRV
jenkins_pipelines/environments/manager-Head-cucumber-NUE
jenkins_pipelines/environments/manager-Head-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
jenkins_pipelines/environments/manager-TEST-Naica-cucumber
jenkins_pipelines/environments/manager-TEST-Orion-cucumber
jenkins_pipelines/environments/manager-TEST-cucumber
jenkins_pipelines/environments/uyuni-master-cucumber-NUE

Temporary run testsuites using:
repo: https://github.com/calancha/sumaform.git
branch: revert-use-official

Run testsuites w/o recently official images

---

jenkins_pipelines/environments/manager-TEST-Naica-cucumber
jenkins_pipelines/environments/manager-TEST-cucumber
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf

Change config to run cucumbers on correct branches.

Test salt authentication

---

terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf

New attempt to do an emergency fix
Like the previous ones, it's on branch 4.0 only for now

Disable CentOS 7 until salt issue is resolved

---

jenkins_pipelines/environments/manager-3.2-cucumber-NUE
jenkins_pipelines/environments/manager-3.2-cucumber-PRV
jenkins_pipelines/environments/manager-3.2-reference-PRV
jenkins_pipelines/environments/manager-4.0-reference-NUE
jenkins_pipelines/environments/manager-4.0-reference-PRV
jenkins_pipelines/environments/manager-4.1-cucumber-NUE
jenkins_pipelines/environments/manager-4.1-cucumber-PRV
jenkins_pipelines/environments/manager-4.1-reference-PRV
jenkins_pipelines/environments/manager-Head-cucumber-NUE
jenkins_pipelines/environments/manager-Head-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
jenkins_pipelines/environments/manager-TEST-Naica-cucumber
jenkins_pipelines/environments/manager-TEST-Orion-cucumber
jenkins_pipelines/environments/manager-TEST-cucumber
jenkins_pipelines/environments/uyuni-master-cucumber-NUE
terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

Applying emergency fix to all branches
Also reverting to official images in all branches

Applying emergency fix to all branches

---

terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf

minima-mirror.prv.suse.net => minima-mirror.mgr.prv.suse.net

Move minima mirror to new network in Provo

---

terracumber_config/tf_files/SUSEManager-4.1-PRV.tf

Use new DHCP and DNS for 4.1 Provo test suite.

Use new network for 4.1 PRV

---

terracumber_config/tf_files/SUSEManager-4.1-PRV.tf

Temporary revert as we still have huge networking problems

Revert: use new network for 4.1 PRV

---

terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf

Temporary revert whil new network is not usable

Revert new network for minima-mirror

---

terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
terracumber_config/tf_files/SUSEManager-3.2-PRV.tf

* sles12sp3o -> sles12sp3
* whitespace alignement

No sles12sp3o image yet

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf

(WIP, do not merge until we have the new VLAN please)

WIP: Use mgr.prv.suse.net for QAM

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf

Use new network for QAM

---

terracumber_config/tf_files/SUSEManager-4.1-qam.tf

Add placeholders to QAM main.tf for additional_repos
basically only comments

Add placeholders to QAM main.tf for additional_repos

---

terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

Reverts SUSE/susemanager-ci#141

Revert "Upgrade controller to opensuse152o"

---

jenkins_pipelines/environments/common/pipeline.groovy
jenkins_pipelines/environments/uyuni-master-cucumber-NUE

Add run_long_tests parameter and use it in uyuni, if it works fine, I will port it to the other environments.

Add run_long_tests parameter and use it in uyuni

---

terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf

use galaxy-proxy from Provo instead of the one in Nuremberg

Use new proxy in Provo

---

terracumber_config/tf_files/SUSEManager-4.1-PRV.tf

- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf:
Fix MAC address.

Testsuite: Fix MAC of 4.1 PRV xen-host

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

Requires: https://github.com/uyuni-project/sumaform/pull/792

Adapt Head TFs for 4.2 and SLE15SP3

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf

Related to https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/215

QAM: Moving all RES channels to mirror 2

---

terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf

partial fix for https://github.com/SUSE/spacewalk/issues/13060

Move internal registry to registry.mgr.prv.suse.net

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf

Added SLES 15 SP2 and renumbered MAC addresses.

Added SLES 15 SP2

---

jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
terracumber_config/tf_files/SUSEManager-4.1-qam.tf

Changes required to test PR https://github.com/uyuni-project/uyuni/pull/3122

Update manager-TEST-Hexagon-cucumber to test PR#3122

---

terracumber_config/tf_files/SUSEManager-4.1-qam.tf

Enable sles15o for QAM again
goes together with https://github.com/uyuni-project/sumaform/pull/835

Enable sles15o for QAM again

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/common/pipeline-qam-setup.groovy
jenkins_pipelines/environments/manager-Head-build-validation-cucumber
terracumber_config/tf_files/SUSEManager-4.2-beta-validation.tf

This PR creates a new terraform file and a new Jenkins pipeline in order to run a test suite for all our supported clients (only smoke tests) for the different milestones we will have in 4.2.
**Note**: For now we still using the same hypervisors for 4.1 and 4.2
**Warning**: This PR needs to be merged after https://github.com/uyuni-project/uyuni/pull/3071

Support for automated build validations

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf
terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

See SUSE/spacewalk#13796 for description
Test suite part: uyuni-project/uyuni/pull/3187

Adding SLE 15 SP3

---

terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

Fix QAM typo for 15sp3 sshminion image and name

Fix QAM typo for 15sp3 sshminion image and name

---

terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

Add debian minions and sshminions in advance, they will be commented out even when this is merged.

Add debian minions and sshminions in advance

---

terracumber_config/tf_files/SUSEManager-4.0-qam.tf
terracumber_config/tf_files/SUSEManager-4.1-qam.tf
terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

Rename base_newsle_ubuntu to base_newsle_debian from comment https://github.com/SUSE/susemanager-ci/pull/190#discussion_r580162120

Rename base_newsle_ubuntu to base_newsle_debian

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

* rename QAM to BV
* insert SLE 12 SP 5

Added SLE 12 SP 5

---

jenkins_pipelines/environments/manager-4.1-build-validation
jenkins_pipelines/environments/manager-4.2-beta-build-validation

Change description of cucumber_ref value on 4.2 BV and remove whitespace

Change description of cucumber_ref value on 4.2 BV and remove whitespace

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

Renamed BV mirrors

---

jenkins_pipelines/environments/manager-4.0-cucumber-NUE
jenkins_pipelines/environments/manager-4.0-cucumber-PRV
jenkins_pipelines/environments/manager-4.1-cucumber-NUE
jenkins_pipelines/environments/manager-4.1-cucumber-PRV

Setting this variable is crucial for retail tests to be executed.

Setting of long_tests variable for all regular testsuites

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Now we wait for reposyncs to finish, the "are you ready?" questions are not needed anymore

Remove "are reposync finished?" questions

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

Enable ubuntu20 and debian9 and debian10 minions in BV

Enable ubuntu20 and debian9 and debian10 minions in BV

---

jenkins_pipelines/environments/common/pipeline.groovy
jenkins_pipelines/environments/manager-4.1-cucumber-NUE
jenkins_pipelines/environments/manager-4.1-cucumber-PRV
jenkins_pipelines/environments/manager-Head-cucumber-NUE
jenkins_pipelines/environments/manager-Head-reference-NUE
jenkins_pipelines/environments/uyuni-master-cucumber-NUE

Related to https://github.com/SUSE/spacewalk/pull/14359

Get rid of the service_pack_migration tag

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

Related to : 
- https://github.com/SUSE/spacewalk/issues/14365
- https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/308

Preparation of Terraform files for our 6 environments for PR testing

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-pr-tests

Related to : 
- https://github.com/SUSE/spacewalk/issues/14365
It includes only a Jenkins pipeline for Uyuni, but is completely parametrizable to allow another pipeline for Manager-4.1 if required after hackweek.

Jenkins pipeline for PR tests, including an env for Uyuni

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Fix api parameter for osc call for pull request pipeline

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-pr-tests

Related to : 
- https://github.com/SUSE/spacewalk/issues/14365

PR Tests: Simple logic to lock/release/pick a environment

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

I see doing a for in groovy is not that straighforward ;) so I created a
bash script and we can call it from the pipeline

Use wait-for-build bash script

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-pr-ci-tests
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

Related to:
https://github.com/SUSE/spacewalk/issues/14365

PR tests: Use the new node specific for this kind of tests

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-pr-ci-tests

Get rid of some parameters of the pipeline, moving them inside the pipeline values.
So the user has only available the parameters that need to care of.

PR Tests: Simplify parameters

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf

Do not install proxy pattern for BV test suite
sumaform part uyuni-project/sumaform#870
test suite part uyuni-project/uyuni#3487

BV: Don't install proxy pattern

---

jenkins_pipelines/environments/manager-Head-cucumber-NUE

Follow up of https://github.com/SUSE/susemanager-ci/pull/203.

Fix long tests variable for Head

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

fix pull request pipeline: build repo is a paramater for add subcommand

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Couldn't find an api call to unlock a project, so we will call "osc
unlock"

Unlock project before removing it

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests

Instead of building all packages, let's only build the packages that
have changed.
fixes https://github.com/SUSE/spacewalk/issues/14612

Build only the packages that have changed

---

terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf

New info for the java, the sp0 will come from the home project and all SPs will come from that one. For uyuni tomorrow I will add from Factory here: https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.2/

SLE packages are coming all from sp0 from the home project

---

terracumber_config/tf_files/Uyuni-Master-NUE.tf

Add new java to uyuni testsuite

Add new java to uyuni testsuite

---

terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

It was verified that the new Java does not cause problems

Remove the additional repos for java11

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Do not lock packages or it creates broken metadata

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

mechanism
fixes https://github.com/SUSE/spacewalk/issues/14626

Publish rpms into the build host instead of using the obs publishing

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

fix path for publishing repos

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise, we get the hostname of the jenkins server

Move get hostname into a stage

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Add some debug messages

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

This PR fixes a copy'n'paste error.

Fix variable name

---

terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

WARNING: This requires https://github.com/uyuni-project/sumaform/pull/890 to be merged first.

Adapt Uyuni TFs for Leap15.3 on the server/proxy, SLE15SP3 build hosts, salt 3002 for everyone

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

Related: https://github.com/SUSE/spacewalk/issues/15042

Adapt Uyuni-PR-test-env* to Leap 15.3

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf

Add image to use in coruscant for buildhost and terminal because we added to use it there

Add image to use in coruscant for buildhost and terminal

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise, we were not testing with packages from this repo

Fail if packages fail to build in TEST:XX:CR projects

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests

Publish in host was an experimental feature. After having it used more
than ten times during the past few days, this proved to work very good.

Promote publish in host as stable

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

This way we include fixes from master branch and also new version bumps.
Otherwise, in the first case we will have failures that are already
fixed, and in the second, we will use the package from master.

Merge to master before running tests

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Discard error output when checking lockfile output

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise, it would be a mess, given we have only one project in the
build service per PR.

Do not let 2 jobs try to test the same PR

---

terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

DO NOT MERGE BEFORE JUNE 22ND
Remove Salt 3002 additional repository
when done, revert this commit:  uyuni-project/uyuni@c2d33e1

Remove salt 3002 additional repository

---

jenkins_pipelines/environments/manager-4.2-qa-build-validation
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Preparing for 4.2 Maintenance Updates validations

4.2 BV is not beta anymore, but about MUs

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests

We need the metadata, not the full channel, so we can speed it up but
shortening this time.

Shorten the time it takes for the scc reposync

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

fix syntax error

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

We were not checking if environment_workspace had been set

Fix finally clause in PR

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

16 GB are needed for the parallel case

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf

Test SLES 12 SP5 in BV 4.1, like we do already in BV 4.2.

Test SLES 12 SP5 too

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Attempt to get rid of generic clients (https://github.com/SUSE/spacewalk/issues/15149)

Remove unneeded generic clients

---

jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf

Currently acceptance test are not stable, so I thought it was a good idea to cleanup some have a couple of adjustement:
- update SUSEManager-Test-Naica-NUE.tf to use more recent OS version 
- use master as default branch for jenkins pipeline

Update naica test

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise, we get the error
groovy.lang.MissingPropertyException: No such property

Initialize environment_workspace variable

---

jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf

This will add an Uyuni reference host. See https://github.com/SUSE/spacewalk/issues/15431
@srbarrios I am not 100 % sure about everything and did copy paste a lot from the SUMA reference host.

Add Uyuni master reference host

---

terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

Fix additional_repos in tf files, it's outside of provider_settings

Fix additional_repos in tf files

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

This is a partial fix for SUSE/spacewalk#15846
This should be merged after uyuni-project/uyuni#4215

Use additional repos for clients

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

Otherwise, the official opensuse image keeps changing and sometimes is
not available.
Goes after https://github.com/uyuni-project/sumaform/pull/951

Use our own image for opensuse clients for PR testing

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/common/pipeline-reference.groovy
jenkins_pipelines/environments/common/pipeline.groovy
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.0-infra-reference-PRV
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
jenkins_pipelines/environments/manager-4.1-qa-build-validation
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
jenkins_pipelines/environments/manager-4.2-qa-build-validation
jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-Head-infra-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
jenkins_pipelines/environments/manager-TEST-acceptance-tests
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
jenkins_pipelines/environments/uyuni-master-infra-reference-NUE

Implements https://github.com/SUSE/spacewalk/issues/15912

Save/restore terraform state through Jenkins artifacts

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/common/pipeline-reference.groovy
jenkins_pipelines/environments/common/pipeline.groovy
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.0-infra-reference-PRV
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
jenkins_pipelines/environments/manager-4.1-qa-build-validation
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
jenkins_pipelines/environments/manager-4.2-qa-build-validation
jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-Head-infra-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
jenkins_pipelines/environments/manager-TEST-acceptance-tests
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
jenkins_pipelines/environments/uyuni-master-infra-reference-NUE

Reverts SUSE/susemanager-ci#341

Revert "Save/restore terraform state through Jenkins artifacts"

---

terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf

This will partially fix https://github.com/SUSE/spacewalk/issues/15911.

Add monitoring to reference hosts

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

This PR adds support for ARM clients in SUSE Manager 4.2 Build Validation.
See also https://github.com/uyuni-project/sumaform/pull/957
Note: we currently use a HERE-document for the contents of the XSLT file, because `terracumber` does not coppy that file yet. This should be fixed in a subsequent PR.

Add support for ARM to BV 4.2

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

This will speed it up 15 minutes.

CI: Parallelize package publishing

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

We added an external storage because we were running out of disc space.

Fix disc space

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Reverts SUSE/susemanager-ci#362

Revert "Add ARM support to 4.1 BV as well"

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.0-infra-reference-PRV
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
jenkins_pipelines/environments/manager-4.1-mu-aws
jenkins_pipelines/environments/manager-4.1-qa-build-validation
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
jenkins_pipelines/environments/manager-4.2-qa-build-validation
jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-Head-infra-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
jenkins_pipelines/environments/manager-TEST-acceptance-tests
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
jenkins_pipelines/environments/uyuni-mu-cloud

Path to the terraform bin was wrong and point to a non existing file

correct path to terraform bin

---

jenkins_pipelines/environments/common/pipeline-reference.groovy
jenkins_pipelines/environments/common/pipeline.groovy

Correct parameter name to match the one on defined in: https://github.com/uyuni-project/terracumber/pull/1

correct terraform bin parameter name

---

terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/local_mirror.tf

update terraform hexagon Job to use Terraform 1.0.10

update terraform hexagon job to use terraform 1.0.10

---

terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf

remote duplicate provider block

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/mail_templates/mail-template-jenkins-pull-request-env-fail.txt
terracumber_config/mail_templates/mail-template-jenkins-pull-request.txt
terracumber_config/mail_templates/mail-template-jenkins.txt
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf

Review links and add more links.
Links can't point to the worker node (workspace) because this is not constant. Instead, we can "publish" the results as artifacts.

Review email for pull request testing

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests

Instead, leave the build for debugging but set an auto cleanup option.

Do not remove build at the end

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

This way it is easier to identify which is yours

Add email to the description of the job

---

terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf

This PR requires https://github.com/uyuni-project/sumaform/pull/1006 to work

Enable Salt bundle installation for Uyuni Master

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise, we can't run the tests if .changes file conflicts

Ignore changes in .changes files

---

terracumber_config/tf_files/common/nfs-mounts.sh

2 exports tested to work for aarch64

Two new exports, and used loops

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

On branch Manager-4.2, use SLE 15 SP3 build hosts and terminals.

USE 15 SP3 as retail build host and terminal

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

This is to have more information on the environments. Let's store who is using it and for what PR. Also, let's put some extra info in jenkins about  it.

Add info on lock

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Add Debian 11 minion and SSH minion  for 4.1 and 4.2 BV test suites

Add Debian 11 minions

---

terracumber_config/tf_files/SUSEManager-4.1-PRV.tf

fixes https://github.com/SUSE/spacewalk/issues/16428

Run 4.1 tests in selektah

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env11.tf
terracumber_config/tf_files/Uyuni-PR-tests-env12.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

We are running out of envs, specially if we want to keep envs for 24h
for debugging.

Add 6 more envs for PR testing

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/scripts/set_custom_header.sh
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env11.tf
terracumber_config/tf_files/Uyuni-PR-tests-env12.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

This is an improvement over https://github.com/SUSE/susemanager-ci/pull/419

Add header to server page 2

---

jenkins_pipelines/environments/manager-4.3-qa-build-validation
terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Depends on https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/461

Preparing BV 4.3

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env11.tf
terracumber_config/tf_files/Uyuni-PR-tests-env12.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

Adapting change in https://github.com/uyuni-project/sumaform/pull/1024

Overwrite additional grains in PR test suites

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Change build validation pipeline so that reposync happens even when selecting products failed.

Reposync even when selecting products failed

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise we get "spam" emails

Set only zypp-team as maintainer

---

terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf

Adapt to sumaform change: https://github.com/uyuni-project/sumaform/pull/1029

Use build_host module

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

because there is an issue with the dhcpd configuration

Disable environments > 6

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

1-8 for devs
9-10 for jordi ;)

Remove moscowmule hypervisor: reassign envs

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/common/pipeline.groovy
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-TEST-acceptance-tests
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
jenkins_pipelines/environments/uyuni-mu-cloud

Related card: https://github.com/SUSE/spacewalk/issues/13530
This PR depends on https://github.com/uyuni-project/uyuni/pull/4740 let's merge both together.

Get rid of long_tests tag

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

fix https://github.com/SUSE/spacewalk/issues/16828

Do not remove previous build to keep previous checkout

---

jenkins_pipelines/environments/common/pipeline.groovy

temporary change to try to understand if issue is at cucumber or rake or pipelines level

Fix stuck forever

---

jenkins_pipelines/environments/common/pipeline.groovy

Revert, thanks for your patience

Debug: Reverting previous test

---

terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-refenv-PRV.tf

Use 10 GB on 4.2 like on head.
Might solve, or not, issues with reposync stuck.

Raise memory for 4.2 server

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

and do some refactoring to use a variable instead of having the x86_64
literal

Only check build status for x86_64 arch

---

terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-AWS.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

Because of the introduction of manager-proxy, galaxy-proxy was confusing.

Rename galaxy-proxy to http-proxy

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

fix https://github.com/SUSE/spacewalk/issues/16828

do not fetch tags to save some time

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

This way we can test salt updates, or any other package update or new
package.

Use the update repo for adding custom packages

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
jenkins_pipelines/manager_prs/Jenkinsfile_prs_spacecmd_unittests
jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests

Similar to what we already do in cucumber tests:
https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/SUSEManager-4.0-NUE.tf#L10
This goes with https://github.com/uyuni-project/uyuni/pull/4992

Add product variable to differentiate between Manager and Uyuni tests

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

Jordi's sumaform has the log enabled in the server and we need this to
debug some stuff.

Use jordi sumaform for reference jobs

---

jenkins_pipelines/environments/uyuni-prs-ci-tests

This only works for server, proxy, kvm and xen hosts. Let's put this
into the description to avoid misexpectations.

Set description to additional_repo

---

jenkins_pipelines/environments/uyuni-prs-ci-tests

I need this to add the log4j package.

Disable additional repos

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

I put that only for my environment, sorry.

Set must_build and must_test for all envs

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Partially revert commit 265717f5ceeec4836b2d672159797556d4427184.

Re-add Debian 11 to 4.2

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

**PLEASE DO NOT APPLY I'D LIKE TO FIX THE ISSUE INSTEAD**

Disable temporarily ARM

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Because we need the cleanup-env utility which is in the uyuni source
code

Checkout project before checking environment

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Phony hardware for the Retail HW groups
(sle 11 sp3 uses default)

Phony hardware for the Retail HW groups

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

Update to Leap 15.4 PR-tests

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Revert increase of memory that was motivated by OOM, now there is a fix

4 GB for proxy again

---

terracumber_config/tf_files/SUSEManager-Test-Hub.tf

change default branch for hub test environment

change default branch for hub test environment

---

terracumber_config/tf_files/SUSEManager-Test-Hub.tf

test hub: use_os_released_updates set to true

test hub: use_os_released_updates set to true

---

jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Test containerized proxy automatically using Hexagon repo

Test container proxy for Hexagon

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Remove arm hypervisor and minion from 4.2 BV

Remove arm hypervisor and minion from 4.2 BV

---

terracumber_config/tf_files/SUSEManager-Test-Hub.tf

update proxy and registry on testhub environment

update proxy and registry on testhub environment

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests

Run secondary test job is for running continuously all secondary tests.
The difference with running on master is that this job excludes flaky
tests.

Add new job for reference secondary tests

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Disable arm again in 4.2 BV

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf

4.3 GM is already declared, and I already changed the 2obs job to use master.

Return Head back to master

---

jenkins_pipelines/environments/uyuni-prs-ci-tests

fix quotes

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

We can't trust opensuse mirrors...

For PRs, use frozen images for kvm and xen testing

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

Use uyuni branches instead of jordi's fork for secondary tests

---

jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Use TEST:Hexagon to test proxy auth fix

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

This makes it easy to collaborate with other devs.

Use the branches for testing flaky tests intead of forks

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Try to save space by only keeping 10 builds

Change cleanup to only keep 10 builds

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Disable overdrive because it is down because of AC issues in the server room.

Disable overdrive because it is down

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Fix removal of overdrive missing part of previous PR was the controller

Fix removal of overdrive missing part of previous PR

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

PR testing runs in Provo, so we better use that mirror.

Use Provo mirror for PR testing

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Use 32 addresses blocks for minions and SSH minions in Build Validation test suite

Prepare for more BV VMs

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

This will add a SLE Micro 5.2 minion to our 4.3 build validation.
https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/570

Add SLE Micro 5.2 as minion to 4.3 BV

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

add minssh-opensuse153arm
there's also a minor fix for Dominik's PR

Test SSH minion for openSUSE 15.3

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

Temporary change Jordis PR pipeline to test https://github.com/uyuni-project/sumaform/pull/1133.

Temp. change Jordis PR Pipeline

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

They both need to test changes in sumaform.

Add jobs for QE and Ion

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.2-qe-build-validation
jenkins_pipelines/environments/manager-4.3-qe-build-validation

Fixes https://github.com/SUSE/spacewalk/issues/17973

Add Retail to BV Jenkins pipeline for 4.3/4.2

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

... otherwise initrd gets full during reinstallation at PXE boot

More memory for SLE 12 SP5 terminal

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

This will add Ubuntu 22.04 to the 4.3 BV.

Add Ubuntu 22.04 to 4.3 BV

---

jenkins_pipelines/environments/uyuni-master-sonarqube

Rely on sonar scanner properties in uyuni repo to connect to the prop…er host

Use sonarcloud

---

terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

See uyuni-project/sumaform#1164

New variable for custom download endpoints

---

terracumber_config/tf_files/SUSEManager-4.3-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE-cobbler-3.3.2
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/Uyuni-Master-AWS.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

Part of https://github.com/SUSE/spacewalk/issues/18408

Upgrade from Ubuntu 20.04 to 22.04 in Head, Uyuni and 4.3

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Switch 4.3 BV to Manager-4.3 branch in spacewalk repo now that we split master and 4.3

Switch 4.3 BV to Manager-4.3 spacewalk

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Fix to 4.3 from https://github.com/SUSE/susemanager-ci/pull/662

Fix to 4.3

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Just use NUE's DHCP and PRV's DNS

No more tunnel to provide DHCP to ARM VMs

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Simply use DHCP in NUE and DNS in PRV

Re-enable ARM testing

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Re-enable the ARM hypervisor

---

terracumber_config/tf_files/SUSEManager-Test-NUE-cobbler-3.3.2
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

some tf files were not switched yet to support opensuse154o image for comtrol node

add opensuse154o image for controller node to missing tf files

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-Master-AWS.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

**Only merge together with the other PRs mentioned in https://github.com/SUSE/spacewalk/issues/12595**
This will
- replace CentOS 7 with Rocky 8 on Uyuni/HEAD

Replace CentOS 7 with Rocky 8 on Uyuni/HEAD

---

README.md

- add Rocky 8 for Uyuni/HEAD and PR test
- add Leap 15.4 for all

Update image matrix

---

README.md
terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

This will specify an image and a name for each node in our terraform configuration files.
Fixes https://github.com/SUSE/spacewalk/issues/19270

Specify image and names in configuration files

---

terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf

Getting problems with assigning IP addresses. So let's move some things around

move 4.2 to selektah and 4.3 to metropolis

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Switch the mirror source from `minima-mirror-bv` to `minima-mirror` for 15.4 product on 4.2 BV tf file.

Use minima-mirror for 15.4 source

---

terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

See also https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/634

Consolidate all 3 build validation mirrors into one

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Note: this assumes changes to sumaform.
Those changes are on their way too.

Add Rocky 9

---

terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf

Switch from metropolis to hugo because metropolis is down and it might need some time to be up again.

Switch from metropolis to hugo

---

terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf

Switch again to bloodymary instead of hugo or metropolis

Switch again to bloodymary

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Comment out Rocky 9 in main.tf

Disable Rocky 9 until we have the products in SCC

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

See
- https://github.com/uyuni-project/sumaform/pull/1197
- https://github.com/uyuni-project/uyuni/pull/5240

QE: Adjust QE PR test pipeline

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-build-validation

Don't merge this PR before:
https://github.com/uyuni-project/uyuni/pull/5014

QE: Adding a new stage in BV for Containerization tests

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Fix variable names

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.2-qe-build-validation
jenkins_pipelines/environments/manager-4.3-qe-build-validation

Part of https://github.com/SUSE/spacewalk/issues/17627

QE: Add monitoring server to BV pipeline

---

terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf

Align `SUSEManager-Test-Orion-NUE.tf` to `SUSEManager-Test-NUE.tf`

Fix Orion environment

---

jenkins_pipelines/environments/common/pipeline.groovy

Card:
https://github.com/SUSE/spacewalk/issues/18100

Re-try the deployment step in our CI testsuites

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Remove sle15 from BVs

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Add oracle and alma to 4.3 BV

---

terracumber_config/tf_files/Uyuni-Master-AWS-mc.tf
terracumber_config/tf_files/Uyuni-Master-AWS.tf

Configure AWS environments with fix IP addresses and own private networks per environment

aws with multiple envs and fix ips

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE

Use master branch of sumaform for the Uyuni CI tests

Use master branch for uyuni CI tests

---

terracumber_config/tf_files/Uyuni-Master-AWS.tf

Test new sumaform feature to overwrite FQDN
See also https://github.com/SUSE/spacewalk/issues/19888

set overwrite fqdn values

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

that might be the cause of the red during the "get results" phase...

An leftover of renaming from QA to QE

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

Temporary use the Ion PR pipeline for QE. @SchoolGuy granted persmission.

Temp use Ions pipeline for QE

---

terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf

Adding credentials of a RediS DB for this PoC (we could re-think it later)

Adding credentials of a RediS DB for this PoC (we could re-think it later)

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf

Removing remainder of the 3 BV mirrors

Updated mirror name

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Reverts SUSE/susemanager-ci#769

Revert "Temporarily disable SLE micro in BV"

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

Add SUSE Liberty Linux 9 support to 4.3 Build Validation
See https://github.com/uyuni-project/sumaform/pull/1259

Add SUSE Liberty Linux 9 support

---

terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf

Test ION: Update for testing Uyuni PR 6676

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf

See https://github.com/uyuni-project/sumaform/pull/1264

Use bundle for CentOS 7 because Salt 3000 was removed

---

terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf

Test ION: Remove Debian Minion

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

This will restore the PR test pipeline of Ion and updates the QE one.

Restore Ion pipeline and adjust QE

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
jenkins_pipelines/environments/common/pipeline-pull-request.groovy

PR #809 introduced test commits by mistake. Revert them

Revert test commits introduced by PR #809

---

jenkins_pipelines/environments/manager-4.2-qe-build-validation

Backports missing parameters from 43 B.V to 4.2 BV

Backport changes from 4.3 BV to 4.2 BV parameters

---

terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-K3S.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

See https://github.com/uyuni-project/sumaform/pull/1280

Revert nested VM variables from list to string

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation
jenkins_pipelines/environments/uyuni-master-qe-build-validation
terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
terracumber_config/tf_files/Uyuni-Master-build-validation.tf

This will add the SLE Micro 5.4 (which will get released this months) to the 4.3 and Uyuni BV.

QE: Add SLE Micro 5.4 to Uyuni and 4.3 BV

---

jenkins_pipelines/environments/manager-4.2-qe-sle-update
jenkins_pipelines/environments/manager-4.3-qe-sle-update

Backport changes needed to support new parallel BV pipeline to sle update configuration files. 
It may need some tuning around minion list. I will do an other PR when I'm back. The PR should fix the Sync issues.

Backport BV changes to sle update

---

jenkins_pipelines/environments/manager-4.2-qe-sle-update
jenkins_pipelines/environments/manager-4.3-qe-sle-update

Disable monitoring deployment for sle update pipeline

Disable monitoring for sle update

---

jenkins_pipelines/environments/manager-4.2-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.2-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

+ removing the unused `//xxx_additional_repository` tags

First steps of BV in NUE

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Error related to BV pipeline.
Result condition checking client stage finish without fail was not bool. 
Declaring variable using env. declaration will result in having the type be a string even Boolean are declared.

Fix client_stage_result_fail type to bool.

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf

support for BV in Nuremberg on suma-05 (4.2 + uyuni) and suma-06 (4.3)

BV in NUE: 4.3 and Uyuni

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE

Follow-up to #856 - adding the new pipelines
Also some recent changes were missing in the Uyuni pipeline, I added them

New pipelines for 4.3 and Uyuni

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf

bridge is br0 on suma-06 and suma-07

Fix bridge name

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf

we need "providers" statmenet for ARM hypervisor

Removed too many "providers" statements

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Move the if condition inside the stage definition to have the stage always visible even when skip.
Split `Prepare stage` into stages corresponding to Jenkins parameters for Proxy and Monitoring.
Add node name into generic stage name.

Refactor BV to have stage always apparent

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE

Add new parameters to BV 4.3 NUE.

Update BV 4.3 NUE parameters with new parameters

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/common/pipeline.groovy

Add Jenkins build number to controller environment to create unique results directory when running rake test on controller.
uyuni PR : https://github.com/uyuni-project/uyuni/pull/7016

Add build number to controller

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Disable liberty until we fix it

Disable liberty until we fix it

---

terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-PRV.tf

Partial revert of previous PR.
It looks like we are not yet ready to test 4.2 with the bundle :disappointed:

For now only use the bundle on proxy and rh-like with 4.2

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Increase random wait range to 180

Increase random wait range to 180

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

With this new changes, if monitoring or retail or containerization fail, it will fail the stage but not stop the pipeline.
At the end of the test, check this none critical status and fail the pipeline if any of this stage failed.
Test done.
The try / catch need to be start before the stage description otherwise the stage will be green even if it fails.

[BV] Fail pipeline when none critical stage fail

---

jenkins_pipelines/environments/manager-4.2-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.2-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

* add sles 15 sp 5
* add openSUSE 15.5
* renumber MAC addresses of SLE micro 5.1, 5,2, 5.3, and 5.4
* renumber MAC addresses of openSUSE 15.4
* remove traditional clients for Uyuni

Add SLES 15 SP 5 and openSUSE 15.5

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Fix Hexagon `main.tf` resource name to work around the CDN issue

Fix hexagon main.tf

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-K3S
terracumber_config/tf_files/Uyuni-Master-K3S.tf

Fix #https://github.com/SUSE/spacewalk/issues/21739

Move K3S CI from PRV to NUE

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf

No special hypervisor for RES in NUE

---

jenkins_pipelines/environments/manager-4.2-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.2-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.2-qe-sle-update
jenkins_pipelines/environments/manager-4.3-qe-sle-update
terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf

See https://bugzilla.suse.com/show_bug.cgi?id=1212437

No Debian 11 / Rocky 9 in 4.2

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/Uyuni-Master-K3S.tf

adapt to https://github.com/uyuni-project/sumaform/pull/1341

Containerized server fix

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/Uyuni-Master-K3S.tf

Adjust to https://github.com/uyuni-project/sumaform/pull/1343

Avoid containerized_server variable / module conflict

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

align Hexagon testsuite: increase RAM and set timeout (as for the other pipeline)

align Hexagon configuration: increase RAM and set timeout 

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Currently, overdrive is not available. Comment all overdrive mention in BV.

Comment overdrive from BV

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Disable auto create bootstrap repository during BV
Required : https://github.com/uyuni-project/sumaform/pull/1357

Disable auto create bootstrap repository during BV

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.2-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.2-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.2-qe-sle-update
jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.3-qe-sle-update
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

Create specific custom channel for monitoring so it will not break sles15sp4 minion add MU channel stage.
Remove the mechanics in place to protect sles15sp4 minion add MU channel stage.

Add specific custom channel to monitoring server

---

terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf

Nuremberg mirror for BV starts being ready for use

Use Nuremberg mirror for Build Validation

---

terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf

The idea is to increase stability and reduce downloads in Nuremberg CI too

Use the mirror in NUE CI too

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

add ubuntu image to hexagon

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/Uyuni-Master-K3S.tf

fix min-nested host in hexagon and k3s

fix min-nested host in hexagon and k3s

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

use opensuse in hexagon tests

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Last changes on pxe boot system requires sles15sp4o image synced

add sles15sp4o image to hexagon test

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/Uyuni-Master-K3S.tf

Test mgr-push tests safely on k3s CI without disturbing podman CI

mgr-push test

---

terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

Testing if there is anything else broken other than the min-kvm vm.

TEST: do not deploy min-kvm

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-podman
terracumber_config/tf_files/Uyuni-Master-podman.tf

https://github.com/SUSE/spacewalk/issues/22281

Add server in podman pipeline and tf file

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

The image was changed to 15.5, but the repos were still 15.4.

Use 15.5 repos for 15.5 images

---

terracumber_config/tf_files/Uyuni-Master-podman.tf

fixes https://github.com/SUSE/spacewalk/issues/22690 .
This same fix works on master.

Update kvm images to leap 15.5 for podman pipeline

---

terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
terracumber_config/tf_files/Uyuni-PR-tests-env9.tf

We are getting OOMKiller killing tests when reposync. We need more memory.
I have checked we have enough memory on all hypervisors.

Increase memory for PR testing

---

README.md
jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
jenkins_pipelines/environments/common/pipeline-pull-request.groovy

fixes https://github.com/SUSE/spacewalk/issues/22407

Rename repositories jordi to pull-request-repositories

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf

fixes https://github.com/SUSE/spacewalk/issues/22705

Update to Leap 15.5 SUSEManager-Head-NUE

---

terracumber_config/tf_files/SUSEManager-4.3-PRV.tf

fixes https://github.com/SUSE/spacewalk/issues/22705

Update to Leap 15.5 SUSEManager-4.3-PRV

---

terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf

fixes https://github.com/SUSE/spacewalk/issues/22703

Update to Leap 15.5 Uyuni-Master-tests-code-coverage pipeline

---

jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-K3S
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-podman

Removing the references to `server-container` branch now that it's gone after the merge

Move containers CI branches to master

---

jenkins_pipelines/environments/uyuni-master-sonarqube
jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests

Remove the PR sonarcloud analysis from the Java Unit tests pipeline as this is now a GH action.
Also rename the deprecated `SONAR_LOGIN` variable to `SONAR_TOKEN`.

Sonarcloud changes

---

terracumber_config/tf_files/Uyuni-Master-K3S.tf
terracumber_config/tf_files/Uyuni-Master-podman.tf

Use Master container image and chart for K3S and podman CIs.

No servercontainer

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

We start supporting Debian 12 in 4.3.9

Add Debian 12

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Use bundle on Debian 12 (I did not manage to have this work at sumaform level :cry: )

Debian 12 is bundle-only

---

jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
terracumber_config/tf_files/Uyuni-Master-K3S.tf
terracumber_config/tf_files/Uyuni-Master-podman.tf

Add the scan back to java unit tests until we have a solution for GH action in PRs coming from works

Revert sonarcloud pr scan

---

terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env6.tf

the hostname should be suma-prX-min-deblike and suma-prX-min-rhlike . This is what we have in the dns.

fix debian and ubuntu

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/common/pipeline.groovy

Related to:
https://github.com/SUSE/spacewalk/issues/22377

Collect and tag flaky tests in CI and PR tests

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

fixes https://github.com/SUSE/spacewalk/issues/21515

Update to Leap 15.5 in Hexagon Pipeline

---

jenkins_pipelines/scripts/cleanup-lock.sh

Fix clean_up_lock script

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-PRV
terracumber_config/tf_files/Uyuni-Master-PRV.tf

Motivated by datacenter migration

Be able to run Uyuni master CI in Provo

---

terracumber_config/tf_files/Uyuni-Master-PRV.tf

Pool and bridge

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

I have tested s390 in isolation after I added management of virtual switches on s390, and after I did the necessary changes linked to datacenter move. It worked fine.
It's time to try it as part of build validation test suite.

s390 should be working now

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

It was 9, when 9 is for the reference jobs

Fix environment for ion tests for PRs

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

* add authentication token
* force HTTPS
(ideally, the token should be set up by terracumber)

Added security for s390

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Value is defined in infrastructure repo

Use variable for zVM admin token

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
jenkins_pipelines/scripts/maintenance_json_generator.py
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Related to https://github.com/SUSE/spacewalk/issues/22410
`salt-migration-minion` and the likes are just placeholder names

BV: add entries for  Salt migration minion

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

add s390 minions to minions' list of checkboxes

Add new s390 minions

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

copy/paste error, sorry :blush:

Fix path for sumaform backend modules

---

jenkins_pipelines/environments/common/pipeline.groovy
terracumber_config/tf_files/PR-testing-template.tf

In PR testing, fix debname and rhlike names in template

Pr fix deb redhat names

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

PR update product version for suma43 ci test ref

PR update product version for suma43 ci test ref

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Forgot to change the minion names when i switched from sp3 to sp5

Correct name for s390 minions

---

jenkins_pipelines/environments/common/pipeline-reference-new.groovy
jenkins_pipelines/environments/common/pipeline.groovy

taint data_disk and database_disk if available

taint data_disk and database_disk

---

terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-PRV.tf

Increase repository_disk_size on Uyuni CI, as we synchronize two products SLES15SP4 and Leap 15.5

Increase repository_disk_size on Uyuni CI, as we synchronize two products SLES15SP4 and Leap 15.5

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Wrong images for s390 minions

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf

related to https://github.com/SUSE/spacewalk/issues/23081

move head to sle micro 5.5 and podman

---

terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars

I think we used to have rocky 9 already, because we have the repos point to rocky 9.

Add rocky 9 to PR testing for uyuni

---

README.md

This PR
- adds our Uyuni Podman CI to the image matrix
- updates the entries for Head

Add Uyuni Podman to image matrix and update it

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
jenkins_pipelines/scripts/maintenance_json_generator.py
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

SLES 12 SP4 LTSS has been EOL for more than 3 months -> removing it

Remove SLES 12 SP4

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

To be able to sync the repositories, increase the main disk until we have a solution for additional disk.
Depends on : https://github.com/uyuni-project/sumaform/pull/1479

Increase main disk size

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf

something broken in the image ?

Temporarily disable SLE Micro 5.5

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf

I forgot the SSH minion when i updated the image

Wrong image for s390 SSH minion

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

To be pushed with https://github.com/uyuni-project/uyuni/pull/8230 and https://github.com/uyuni-project/uyuni-tools/pull/154

Add the architecture to the HEAD container_repository variables

---

jenkins_pipelines/environments/manager-4.3-vm-dev-acceptance-tests-NUE
terracumber_config/tf_files/SUSEManager-4.3-VM-NUE.tf

https://github.com/SUSE/spacewalk/issues/22625

Add 4.3 VM pipeline

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Simplify libvirt names for ARM

Simplify libvirt names

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

make work with clean-env.sh easier

Names more friendly to cleanup script

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Bump to feilong provider 0.0.6

Bump to feilong provider 0.0.6

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

We agreed and Abid gave to OK, to disable the SLE Micro Minions, until we have full support for them. This will be reevaluated once SUME 5.0 will be released.

BV: Disable SLE Micro SSH Minions

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-podman.tf

Fixes https://github.com/SUSE/spacewalk/issues/23647

Enable mirror in Head and Uyuni podman

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf

Test Hexagon: increase disk size as already done for HEAD

Test Hexagon: increase disk size as already done for HEAD

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Test Hexagon: add test repo

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Test Hexagon: fix test repo

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-podman.tf

Related to https://github.com/SUSE/spacewalk/issues/23272 and https://github.com/SUSE/spacewalk/issues/23615
To be merged at the same time than https://github.com/uyuni-project/uyuni/pull/8352/

Replace proxy by proxy_containerized in Uyuni podman and Head envs

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy

Add missing variable use to store paygo stage testing result.

Add missing variable for paygo testing

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

This will increase the main disk size for the 5.0 BV environment.

Increase main disk size for 5.0 BV

---

jenkins_pipelines/environments/common/pipeline-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-pull-request.groovy
jenkins_pipelines/environments/common/pipeline-reference.groovy
jenkins_pipelines/environments/common/pipeline-salt-shaker.groovy
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage

If we don't taint them the next run will have prepopulated volumes and fail.

Taint the spacewalk and database disks too

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Follow-up PR of https://github.com/SUSE/susemanager-ci/pull/1166

5.0 BV: Temporary disable Liberty Linux 9

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf

- correctly declare the `is_server_paygo_instance` variable for AWS BV using BYOS image
- update both paygo and byos server to fix the netfconfig package issue ( https://bugzilla.suse.com/show_bug.cgi?id=1220718 ). The current available netconfig package on those images has a bug. The fix is available in the repositories but we need to update those servers . Depends on : https://github.com/uyuni-project/sumaform/pull/1541
- add chrony package for sles12 deployment. The salt state is failing to install those packages on sles12
- set data disk to 0, we don't handle this disk creation in aws modules

Fix aws bv deployment

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Revert some of the temporary changes, I did on Friday.

QE: Enable mirror and Liberty 9 in 5.0 BV NUE

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
terracumber_config/tf_files/PR-testing-template.tf
terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars
terracumber_config/tf_files/variables/PR-testing-variables.tf

Use Leap Micro for PR testing with containerized server and proxy.

Test leap micro on PR testing for uyuni-product version

---

jenkins_pipelines/environments/manager-4.3-qe-sle-update

Add missing option necessary for pipeline, we forgot to add it here, the SLE pipeline uses the BV.

Add missing option necessary for pipeline

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Set up external DHCP and DNS server on 5.0 Build Validation

Use an external DHCP and DNS server

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

Use an external DHCP and DNS server (2)

---

.github/workflows/sumaform-validation.yml
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

Jenkins worker has no direct access to private network

Fix DHCP and DNS server setup

---

terracumber_config/tf_files/PR-testing-template.tf
terracumber_config/tf_files/tfvars/PR-testing-manager43.tfvars
terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars
terracumber_config/tf_files/variables/PR-testing-variables.tf

We were missing the deployment of the proxy container into our Uyuni PR test environment.

Fix proxy integration into our PR tests

---

terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-PRV.tf

Let's try to reproduce the bug again

Back to 2 GB to reproduce bsc#1221382

---

terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf

Fix MAC for testorion proxy

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

Reverts SUSE/susemanager-ci#1105 due to issues found in the 5.0 BV.
```bash
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 7a442059-500f-4a20-acc2-ae81e3970752
org.jenkinsci.plugins.workflow.cps.CpsCompilationErrorsException: startup failed:
Script1.groovy: 220: unexpected token: -> @ line 220, column 53.
features_list.each( feature -> {
^
1 error
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:149)
at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:349)
at …
```

Revert "BV: Add products and Salt migration tests stages"

---

jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV

This would be done on the Jenkins worker in PRV not in NUE.

Fix 5.0 BV PRV worker definition

---

terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf

Add main.tf for Vega team
(Mostly a copy-paste from Naica)

Add main.tf for Vega team

---

terracumber_config/tf_files/Uyuni-Master-K3S.tf

Renumbered K3S test suite

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/Uyuni-Master-podman.tf

Add missing hypervisor information
(jenkins worker has no direct access to 192.168.x.x private network)

Add missing hypervisor information

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf

Add private ip for sle12 and 15 terminal

Add private ip for sle12 and 15 terminal

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf

Fix bv 4.3 suma-arm url

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Debian 10 is not supported anymore by suma 4.3.
Remove debian10 from BV deployment.

Remove debian 10 from 4.3 BV deployment

---

jenkins_pipelines/environments/common/pipeline-reference-new.groovy
jenkins_pipelines/environments/common/pipeline-reference.groovy
jenkins_pipelines/environments/common/pipeline-salt-shaker.groovy
jenkins_pipelines/environments/common/pipeline.groovy
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage

Properly taint also resources of type standalone_provisioning
Otherwise the DHCP and DNS server is unsufficiently tainted.

Properly taint also resources of type standalone_provisioning

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Use salt to deploy on slemicro for BV

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Disable sle15sp5 s390 ssh minion from 4.3 BV NUE
Use the correct sle15sp5 s390 image for 4.3 BV PRV

Update sle15sp5 s390 image

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.3-qe-sle-update
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

With this [change](https://github.com/uyuni-project/uyuni/pull/8622) we don't need to distinguish anymore between proxies.

BV: Simplify proxy stages

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Related to https://github.com/SUSE/spacewalk/issues/23848

QE: Add openSUSE 15.6 support

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

Same as https://github.com/SUSE/susemanager-ci/pull/1105 with due fixes

BV: Add products and Salt migration stages

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

aa:b2:92:42:00 -> aa:b2:92:05:00 in Provo to avoid false duplicates
see also https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/890

Use different MAC addresses in Provo

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

Missing dash on some name prefixes (not all)

Fixed some name prefixes

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV

Add salt migration client the BV list

Add salt migration client the BV list

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

latest tag for hexagon pipeline

latest tag for hexagon pipeline

---

jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests

set manager-TEST-Hexagon-acceptance-tests default value

set manager-TEST-Hexagon-acceptance-tests default value

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Use correct image for s390 SLES 15 SP 5
Also reenable s390 in 4.3 BV

Use correct image for s390 SLES 15 SP 5

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV

These stages execute some basic tests on a containerized proxy, that makes sense only for 4.3 BV pipelines.

BV: remove containerization stages in 5.0 pipelines

---

terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf

I changed in infra but forgot in main.tf

Renumbered the MAC in Provo to avoid conflicts

---

jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-sles15sp5
terracumber_config/tf_files/salt-shaker/Salt-Shaker-Products-SLES15SP5.tf

Add Salt Shaker job to test the Salt package built in OBS `systemsmanagement:saltstack:products` for SLES15SP5.

Add Salt Shaker job to test after promotion for SLES15SP5

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf

See https://suse.slack.com/archives/C05EEE30L4W/p1718373891147499

QE: Temporarily disable Liberty 9 in the 4.3 BV

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Reenable Liberty 9 on 5.0 BV

---

README.md
terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf

Add main.tf files for 5.0 CI and 5.0 reference hosts.
Also use final products in 5.0 BV.
*Checks are currently red because I need to add support for "5.0-released" to sumaform first.*

Add 5.0 CI and reference hosts

---

jenkins_pipelines/environments/manager-5.0-infra-reference-NUE
jenkins_pipelines/environments/manager-5.0-infra-reference-PRV

Add pipelines for 5.0 refhosts

Add pipelines for 5.0 refhosts

---

terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf

Add SLE Updates testsuite for 5.0

---

jenkins_pipelines/environments/manager-5.0-qe-sle-update

Add SLE Updates testsuite for 5.0 (2)

---

terracumber_config/tf_files/Uyuni-Master-podman.tf

Related to https://github.com/SUSE/spacewalk/issues/24883#issuecomment-2244556574

Enable again mirror in Uyuni-Master-podman

---

terracumber_config/tf_files/PR-testing-template.tf

Fix container_repository url

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Remove Debian 10 and SLE 15 SP1 from pipelines and main.tf files

Remove Debian 10 and SLE 15 SP1

---

terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

This fixes and aligns the Uyuni BV configuration to what we have in 5.0 with respect to the parameters.

Uyuni BV updates

---

jenkins_pipelines/data/non_MU_channels_tasks.json

Remove clm declaration for the non MU repositories in BV. We are now doing it in CI

Update non mu list

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

This PR fixes wrong MAC addresses for SLE 15 SP6 clients (likely a copy-paste error)

Fix MAC addresses in Provo for new clients

---

terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Update correct mac addresses for Uyuni BV PRV.

Update correct mac addresses for Uyuni BV PRV.

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

We have some discrepancies between the parameter minionList and the modules in main.tf for the BV pipelines
- Remove sles15sp1 from minionlist
- Add salt_migration_minion variable to uyuni minionList.

Update minionList for BV pipeline parameter

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
jenkins_pipelines/scripts/tests/test_maintenance_json_generator.py

This PR introduces some refactors in order to make the code more maintainable and increase test coverage.

Refactor JSON generator script and increase coverage

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Changing the container URL for the 5.0.1 BV.

QE: Change 5.0 BV URL for 5.0.1

---

terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf

Fix registry url, the rest gets added in the code of the mgr tools.

Fix registry url

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

This PR allows the change from 5.0 to 5.1 on Head branch.
It also removes temporary hacks

Head branch is now 5.1

---

terracumber_config/tf_files/Uyuni-Master-K3S.tf

fix k3s pipeline

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Also taint null resourve on BV

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf

Since it seems to work with short registry names, let's do last leftovers

Shorten last long registry names

---

jenkins_pipelines/scripts/json_generator/README.md
jenkins_pipelines/scripts/json_generator/ibs_osc_client_README.md
jenkins_pipelines/scripts/json_generator/maintenance_json_generator_README.md
jenkins_pipelines/scripts/json_generator/smash_client_README.md

Add README files for pipeline scripts

Add README files for pipeline scripts

---

jenkins_pipelines/environments/common/pipeline.groovy

Try to update the minima mirror before we start the deployment
See also https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/948

update the mirror before starting a deployment

---

jenkins_pipelines/environments/common/pipeline.groovy

"prefix" variable is undefined in this scope

Revert 8d4993b8fbfb8adc33376d2cbbac90e6e69b6320

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-podman
terracumber_config/tf_files/Uyuni-Master-podman.tf

Part of https://github.com/uyuni-project/uyuni/pull/9181

Use again master branches for Uyuni Podman CI pipeline

---

terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Add the new product version variable.
This variable select the correct ruby version

Add product_version to controller in BV and QE Maintenance

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Update name to match new infra hostnames.

Change names in main.tf to match new hostname in infra

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage

fix code-coverage-pipeline

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Update name to follow new infra hostname for BV 50 NUE
Depends on : https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/955

Update name to follow new infra hostname for BV 50 NUE

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

Minions connect to proxy, not to server

Minions connect to proxy, not to server

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Correctly update the salt migration minion name for BV 5.0 NUE and 4.3 PRV

Fix salt migration names

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Update hostname in main.tf for uyuniNUEBV uyuniPRVBV 50PRVBV

Update hostname in main.tf for uyuniNUEBV uyuniPRVBV 50PRVBV

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-sle-update
jenkins_pipelines/environments/manager-5.0-qe-sle-update

Non MU repositories file declaration was move from the pipeline description to the parameter description because the file differ between 5.0 and 4.3.
QE update pipeline didn't have this change and so was failing when trying to load the file.
This PR add the file path for those pipelines.

Fix non mu file needed qe release

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Fix typo in terminals' names

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf

Follow-up of previous (incomplete) PR

Fixed typo

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-4.3-qe-sle-update
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-sle-update
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

Rename minionList and add back maintf selector.
see https://suse.slack.com/archives/C02D12TNYLS/p1727307840479139

Rename minionList and add back maintf selector.

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Add Ubuntu 24.04 on SUSE Manager 4.3

Add Ubuntu 24.04 on 4.3

---

jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Add libertylinux9 to uyuni BV deployment.

Add liberty linux 9 to uyuni BVs

---

jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-ubuntu2404-bundle
jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-ubuntu2404-bundle
terracumber_config/tf_files/salt-shaker/Salt-Shaker-Next-Ubuntu2404-Bundle.tf
terracumber_config/tf_files/salt-shaker/Salt-Shaker-Testing-Ubuntu2404-Bundle.tf

Added:
- TF files for the new jobs
- pipeline for the new jobs

Salt Shaker: add TF files and pipelines for Ubuntu 24.04 jobs

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV

Forgot Ubuntu 24.04 in 4.3 pipelines

Forgot Ubuntu 24.04 in 4.3 pipelines

---

terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf

Update registry with latest MU

Update registry with latest MU

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/manager-4.3-qe-sle-update-NUE
jenkins_pipelines/environments/manager-4.3-qe-sle-update-PRV
jenkins_pipelines/environments/manager-5.0-qe-sle-update-NUE
jenkins_pipelines/environments/manager-5.0-qe-sle-update-PRV
terracumber_config/tf_files/SUSEManager-4.3-SLE-update-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf

Related to: https://github.com/SUSE/spacewalk/issues/25447
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/970

Create sle maintenance update pipeline nue

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
jenkins_pipelines/environments/uyuni-prs-ci-tests

domain should depend on the localization

Fix domain for pr testing

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf

Add a comment about RHEL 9 testing
Piggyback: some reordering in the AWS file

Add a comment about RHEL 9 testing

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

follow-up of https://github.com/SUSE/susemanager-ci/pull/1438

Add a comment about RHEL 9 testing (2)

---

terracumber_config/tf_files/salt-shaker/Salt-Shaker-Next-Ubuntu2404-Bundle.tf
terracumber_config/tf_files/salt-shaker/Salt-Shaker-Testing-Ubuntu2404-Bundle.tf

See https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/977

Fix Salt shaker numbering

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf

Add ubuntu2404 in controller module

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py

Fix for https://github.com/SUSE/spacewalk/issues/25035

Missing coma in proxy 5.0 channels

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Otherwise, when debugging we miss this repos and that is confusing

Do not remove PR repos if tests fail

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy

We can't mix 4.3 and master without removing the whole sumaform directory.

Reserve for 4.3

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

Part of https://github.com/SUSE/spacewalk/issues/24491

Enable beta channels in Head environments

---

terracumber_config/tf_files/Uyuni-Master-podman.tf
terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf

Related to https://github.com/uyuni-project/uyuni/pull/9431

Enable Quality Intelligence in Uyuni Master Podman

---

terracumber_config/tf_files/Uyuni-Master-K3S.tf

Testing https://github.com/uyuni-project/uyuni-tools/pull/450 with the broken K3S CI

Use K3S CI to test Kubernetes refactoring

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf

Fix dhcp module name for CI head pipeline

Fix dhcp module name for CI head pipeline

---

jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop

Request from the discussion: https://suse.slack.com/archives/C02D12TNYLS/p1729753176627919

Trigger rubocop only if ruby files has been changed

---

terracumber_config/tf_files/PR-testing-template.tf
terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
terracumber_config/tf_files/Uyuni-Master-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
terracumber_config/tf_files/local_mirror.tf

switch to terraform libvirt provider for PRV + tests on PRs

First bunch of test suites with new provider

---

terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf

Add dhcp module for naica and vega pipelines

Add dhcp module for naica and vega pipelines

---

terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf

Remove default parameters.
Remove name field to use default name.

Rename code cov modules.

---

jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-4.3-infra-reference-NUE
jenkins_pipelines/environments/manager-4.3-infra-reference-PRV
jenkins_pipelines/environments/manager-5.0-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-5.0-dev-acceptance-tests-PRV
jenkins_pipelines/environments/manager-5.0-infra-reference-NUE
jenkins_pipelines/environments/manager-5.0-infra-reference-PRV
jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
jenkins_pipelines/environments/manager-Head-infra-reference-NUE
jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Ion-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
jenkins_pipelines/environments/manager-TEST-Vega-acceptance-tests
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-K3S
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-PRV
jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-podman
jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
jenkins_pipelines/environments/uyuni-prs-ci-tests

All pipelines has been renamed, we can now switch back sumaform to master branch.

Switch back sumaform branch to master

---

terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
terracumber_config/tf_files/Uyuni-Master-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
terracumber_config/tf_files/local_mirror.tf

Revert 0.8.1 provider to 0.6.3 for now

Revert 0.8.1 provider to 0.6.3 for now

---

terracumber_config/tf_files/Uyuni-Master-K3S.tf

k3s sumaform mirror fixes have been merged, use the regular repos.

Get k3s pipeline back to normal

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-paygo-AWS.tf
terracumber_config/tf_files/local_mirror.tf

Currently, this pipeline is only deploying the paygo environment without configuring the server
Add the options to configure the server.

Improve bv aws

---

jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Add options for continuous bv to run 5.1 product (head).

Add head options to continuous bv

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
jenkins_pipelines/environments/qe-build-validation-cleaning-pipeline
jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/TestEnvironmentCleaner.py
jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/test_environment_cleaner_api.py
jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/test_environment_cleaner_ssh.py
jenkins_pipelines/scripts/test_environment_cleaner/tests/test_main_program.py
jenkins_pipelines/scripts/test_environment_cleaner/tests/test_test_environment_cleaner_api.py

Stop parsing the product version from the job name.
Use the api to get the product version.

CLEANUP PIPELINE: Use the API to get the product version

---

README.md
jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Mapping of https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/999 entries onto Terraform deployments using https://github.com/SUSE/susemanager-ci/pull/1162 as a template following the requirements in https://github.com/SUSE/spacewalk/issues/26216.

SL Micro 6.1 infrastructure entries to the testsuite deployment mapping

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

ip6tables bug https://bugzilla.suse.com/show_bug.cgi?id=1234996 was marked as RESOLVED FIXED with comment "accepted into codestream" today
-> removing our workaround

Remove temporary fix to ip6tables issue

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

Get ip6tables fix somewhere else again

Get ip6tables fix somewhere else again

---

terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf

Get right version of ip6tables fix

Get right version of ip6tables fix

---

terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Add server hostname to main.tf output for BV Continuous to be compatible with the cleanup pipeline.

Add server hostname to main.tf output for BV continuous

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Use MAC prefix for new partition ZL41

Use MAC prefix for new partition ZL41

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Fix the workspace setup for PR pipelines to match CI and BV.
Also fix the symlink issue.

Fix workspace prs

---

jenkins_pipelines/environments/common/pipeline-pull-request.groovy

Fixing this error: 
```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 23894fab-cf90-406b-ace0-0adb97367856
groovy.lang.MissingPropertyException: No such property: running_same_pr for class: groovy.lang.Binding
```

Fix running_same_pr issue on Jenkins PR tests

---

jenkins_pipelines/environments/uyuni-prs-ci-tests

Reverts SUSE/susemanager-ci#1540

uyuni-prs-ci-tests by default in NUE

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
jenkins_pipelines/environments/qe-build-validation-cleaning-pipeline

Depends on: https://github.com/uyuni-project/terracumber/pull/49

Use simplify cleanup option

---

terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
terracumber_config/tf_files/Uyuni-Master-PRV.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Switch to new libvirt provider 0.8.1 in Provo

Switch to new provider in Provo

---

jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
jenkins_pipelines/environments/common/pipeline-pull-request.groovy
terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars

Switch to Ubuntu 24.04 in tests on PRs
To be merged last of all related PRs, together with #1533

Switch to Ubuntu 24.04 in tests on PRs

---

terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-SLE-update-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Hub.tf
terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-K3S.tf
terracumber_config/tf_files/Uyuni-Master-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-podman.tf
terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
terracumber_config/tf_files/local_mirror.tf

Switch NUE CI to libvirt provider version 0.8.1

Switch NUE CI to libvirt provider version 0.8.1

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

Fix base image for head server

---

terracumber_config/tf_files/PR-testing-template.tf

Switch to new provider for tests on PRs

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Revert junit publish to comment

Comment back junit result

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy

Fix cleaning pipeline when s390 not present.

Fix cleaning pipeline workaround s390

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/TestEnvironmentCleaner.py
jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/test_environment_cleaner_api.py
jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/test_environment_cleaner_ssh.py
jenkins_pipelines/scripts/test_environment_cleaner/tests/test_main_program.py

Add the possibility to clean retail artifacts.

Improve BV cleaning pipeline to cover retail 

---

terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf

Fixes
- hypvervisor selection
- local net work name

Fixups for 5.1 BV

---

jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Remove ubuntu 2004 and opensuse155 arm from continuous pipeline

Remove ubuntu 2004 and opensuse155 arm from continuous pipeline

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage

Bump up JaCoCo version to the latest version.

Bump up JaCoCo version

---

jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage

Small refactor to make it more readable.

Small refactor uyuni-master-dev-acceptance-tests-code-coverage

---

jenkins_pipelines/environments/manager-TEST-Vega-acceptance-tests
terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf

- disable periodic pipeline trigger
- update server image to SL Micro 6.1

Disable periodic pipeline trigger

---

terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf

Renumbered to free IP addresses for MLM 5.1

Update main.tf files for s390 after introducing 5.1

---

jenkins_pipelines/environments/manager-5.0-qe-alternative-base-OS-NUE
terracumber_config/tf_files/SUSEManager-5.0-alternative-base-OS-NUE.tf

Add SLES 15 SP6 as base OS for SUSE Manager 5.0
See https://github.com/SUSE/spacewalk/pull/26622

Add SLES 15 SP6 as potential base OS

---

terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-alternative-base-OS-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Fixes to product versions and container paths

Fixes to product versions and container paths

---

terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf
terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Card: https://github.com/SUSE/spacewalk/issues/26373

Enable beta client tools

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy

Use correct condition for the full main.tf cleanup

Use correct condition for the full main.tf cleanup

---

terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf

Fix arm bridge for mlm 51

---

README.md

Leap 15.5 removal: I forgot the documentation

Leap 15.5 removal: doc

---

README.md

Add DHCP and DNS server to the system versions matrix

Add DHCP and DNS server

---

README.md

Virtualization host disappears with 5.1, removing it

Virtualization host disappears with 5.1

---

README.md

GH validation already uses 15.6 on controller
Cf. https://github.com/uyuni-project/uyuni/pull/9905

GH validation already uses 15.6 on controller

---

terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf

Move some testsuites to the new servers (2)

Move some testsuites to the new servers (2)

---

terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

SLES 15 SP2 is EOL, end of grace period next Monday

SLES 15 SP2 is EOL, end of grace period next Monday

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator_README.md

Fix doc to use python3.11 and name of script

Fix doc to use python3.11 and name of script

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.1-qe-build-validation-NUE
jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV

Remove SLES 15 SP2 from build choices

Remove SLES 15 SP2 from build choices

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py

Add corrrect url for 61 minion

Add corrrect url for 61 minion

---

jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/TestEnvironmentCleaner.py

Fix update custom reppo

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py

Change names of url so they do not contain minion in the name

Change names of url so they do not contain minion

---

jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py

Use images repo for SL Micro instead of standard

Use images repo for SL Micro instead of standard

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy

Fix issue with main.tf file missing during BV cleanup pipeline.

Add back main.tf file for bv cleanup pipeline

---

terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf

Change Naica env to slmicro61 and registry

Change Naica env to slmicro61 and registry

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation.groovy

Correct English

---

terracumber_config/tf_files/SUSEManager-5.0-PRV.tf

Fix main.tf syntax

---

terracumber_config/tf_files/SUSEManager-5.0-PRV.tf

Temporary workaround against issues with bundle

Temporary workaround against issues with bundle

---

terracumber_config/tf_files/SUSEManager-5.0-PRV.tf

Use a repo available in SLC1

---

terracumber_config/tf_files/SUSEManager-5.0-PRV.tf

Better workaround against issues with bundle

Better workaround against issues with bundle

---

terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
terracumber_config/tf_files/Uyuni-Master-PRV.tf

Fix MAC addresses in Provo

---

terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf

it will help to reproduce https://bugzilla.suse.com/show_bug.cgi?id=1241034

use sles15sp6 as hostOS for mlm 5.1

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
jenkins_pipelines/environments/manager-5.1-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

* Remove SLE 15 SP2
* Add SLE 15 SP7
* Renumber SLE
Piggyback: remove SLE 15 SP3 from Retail images in Provo (probably a leftover).

Add SLE 15 SP7

---

jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
jenkins_pipelines/environments/manager-5.0-qe-build-validation-AWS
jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf

More SLE 15 SP7

---

jenkins_pipelines/environments/manager-TEST-Ion-acceptance-tests

This reverts commit b0575b0803bf58cec48bd99a096a41fcbd3ad147 as it is no longer necessary

Revert "Ion: test dead code removal"

---

jenkins_pipelines/environments/qe-build-validation-cleaning-pipeline

Add 5.1 BV pipeline to the cleanup pipeline

Add 5.1 BV pipeline to the cleanup pipeline

---

jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
jenkins_pipelines/environments/qe-build-validation-cleaning-pipeline

BV cleanup pipeline: Fix the tf variables for the containers

BV cleanup pipeline: Fix the tf variables for the containers

---

terracumber_config/tf_files/Uyuni-Master-podman.tf

Temporary increasing the memory on the Uyuni podman controller to test something

Increase controller's memory in Uyuni-Podman

---

terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf

Switch to  5.1-nightly product.

Change product version to 5.1 nightly for BV

---

jenkins_pipelines/environments/manager-5.1-qe-build-validation-NUE
jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
jenkins_pipelines/scripts/json_generator/repository_versions/v43_nodes.py
jenkins_pipelines/scripts/json_generator/repository_versions/v51_nodes.py
terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf

Add openEuler 24.03 LTS to main.tf's and pipelines

Add openEuler 24.03 LTS

---

jenkins_pipelines/environments/manager-5.0-qe-alternative-base-OS-NUE

Pass container image variable

---

terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
terracumber_config/tf_files/SUSEManager-Head-NUE.tf

Enable the large deployment option for all CI pipelines.
Note: Uyuni podman already have the option.

Enable large deployment configuration for CI.

---

jenkins_pipelines/environments/common/pipeline.groovy
terracumber_config/tf_files/Uyuni-Master-AWS.tf

Card:
https://github.com/SUSE/spacewalk/issues/26466
Related PRs:
- https://github.com/uyuni-project/sumaform/pull/1867
- https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/1062

In the case of an AWS environment, we want to export the reports to a publicly accessible web server.

---

jenkins_pipelines/environments/common/pipeline-build-validation.groovy

With the migration feature renaming, the pipeline needs an update.
Impact the new naming to clientMigrationStages function.
Depends on: https://github.com/uyuni-project/uyuni/pull/10448 and the ports to the other branches.

Impact migration naming changes to BV pipeline.

---

jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE

Forget to uncomment base OS choice for continuous pipeline.

Enable base OS choice

---

jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
jenkins_pipelines/environments/common/pipeline-build-validation.groovy
jenkins_pipelines/environments/common/pipeline.groovy

Remove the new cucumber message:

Disable cucumber publish message

---

jenkins_pipelines/environments/manager-5.1-qe-sle-update-NUE

Fix container paths for 5.1 SLE updates

Fix container paths for 5.1 SLE updates

---

terracumber_config/tf_files/SUSEManager-5.0-build-validation-paygo-AWS.tf

Support both x86 and arm64 version of the 5.0 BYOS Proxy.

Support both x86 and arm64 5.0 BYOS proxy

---

terracumber_config/tf_files/MLM-5.1-PRV.tf

I forgot one MAC address

---

.github/workflows/sumaform-validation.yml

Skip Sumaform validation in BV and Personal terraform files.
Related to https://github.com/SUSE/susemanager-ci/pull/1753

Skip Sumaform validation in BV and Personal terraform files

---

jenkins_pipelines/environments/manager-5.0-micro-qe-sle-update-NUE
jenkins_pipelines/environments/manager-5.0-micro-qe-sle-update-PRV
jenkins_pipelines/environments/manager-5.0-sles-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.0-sles-qe-sle-update-NUE
jenkins_pipelines/environments/manager-5.1-micro-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.1-micro-qe-sle-update-NUE
jenkins_pipelines/environments/manager-5.1-sles-qe-build-validation-NUE
jenkins_pipelines/environments/manager-5.1-sles-qe-sle-update-NUE

Add the display release tag to the new BV pipelines and fix some non MU channel file declaration.

Add the release tag to BV and fix non MU channel list.
