- jenkins_pipelines/performance_testsuite/Jenkinsfile_performance_testsuite
Change the jenkins job scheduling for the performance testsuite to run every 2 hours
> Change the jenkins job scheduling for the performance testsuite to run every 2 hours

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog
This is the only way I can fix this, as for some estrange reason the OR bash/sh operator doesn't seem to work on the declarative pipeline (CLRET was always empty)
@MalloZup if you have any better idea to use `||`, please tell me. I just ran out of ideas.
I switched uyuni job to use this branch, and it seems to be working fine:
https://ci.suse.de/job/Uyuni-PRs/job/Uyuni-PRs-changelog-pipeline/11903/
https://ci.suse.de/job/Uyuni-PRs/job/Uyuni-PRs-changelog-pipeline/11904/
> Fix changelog_test return code pickup

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unitpsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_checkstyle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_psql_unit
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_rubocop
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_oracle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_postgre
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_sql_standard_name
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittest
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unitpsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_checkstyle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_psql_unit
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_rubocop
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_oracle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_postgre
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_sql_standard_name
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittest
Task : https://github.com/SUSE/spacewalk/issues/6376
- Avoid failing when no pending PRs
- Avoid Junit failure if will the execution will not produce a report
- Fixing JUnit output path
Future work: I did it modifying the pipeline, parsing output of gitarro, so less impact in our system. Can be done modifying gitarro, so we return different exit codes and then parse those to exit always with 0 (to don't let fail the pipeline) or we read from a json file or env. variable produced by gitarro.
> Hotfix/6376 avoid failure when no pending PRs

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unitpsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_checkstyle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_psql_unit
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_rubocop
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_oracle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_postgre
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_sql_standard_name
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittest
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unitpsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_checkstyle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_psql_unit
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_rubocop
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_oracle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_postgre
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_sql_standard_name
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittest
Task: https://github.com/SUSE/spacewalk/issues/6376
This job needs files inside susemanager-ci repo, but the step cleanws at first stage is deleting also the repo checked out. There is no way to clean up before the checkout of pipelines repo, we don't want to use deletedir of a specific folder because it can be tricky, as pipelines also creates tmp and script dirs, only cleaned with cleanws step.
Solution:
- Checkout ci repo after cleanws, to fix rubocop script not found.
- Also added a bonus, boolean parameter in case you want to run the pipeline manually, avoiding clean up workspace after job success.
> [6376] Checkout ci repo after cleanws, to fix rubocop not found

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_oracle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests
- Added a PR_NUMBER parameter in PR Check jobs, to be able to run on a specific PR directly
- Add the PR_NUMBER to the title of PR Check jobs executed
- Fix rubocop pipeline test that needs a script contained in pipelines repo
> Improve Jenkins Pipelines to reduce GitHub calls

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
Increasing from 1h to 2days the filter of PRs to check.
As we sometimes have issues in our Jenkins slaves, and that cause that we need to force-push our PR to be checked.
We have around 5-6 PR max younger than 2 days, so it should be fine. 
And it will safe us from some support discussions on IRC.
> Increase the time to check a PR to 2 days old

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog_test
New force_test parameter added on changelog_test pipelines for Uyuni and SUMA, so it will run always the merged_enabled test even if we don't have a comment or a checkbox to re-trigger it.
This is to fix a corner case, when the changelog_test fails, we mark the merged_enabled to false, then we re-run the changelog_test with the checkbox but the merged_enabled doesn't change its status (as it is not triggered because has not a checkbox marked in the PR description)
> New force_test parameter on merge_enabled tets, so it will run always

- jenkins_pipelines/manager_prs/Jenkinsfile_testsuite
This PR contains a new pipeline Jenkins file that organizes the test suite in different stages, splitting them in core features, init clients, secondary features, finishing, and reporting.
For now it is using the traditional jenkins-runner bash script, it is intended to update to Terracumber, when Julio merges it.
That PR depends on sumaform-test-runner PR (https://gitlab.suse.de/galaxy/sumaform-test-runner/merge_requests/148) and spacewalk PR (https://github.com/SUSE/spacewalk/pull/8202).
> New pipeline to move from a Testsuite Jenkins Job to a TestSuite split in stages

- jenkins_pipelines/manager_prs/Jenkinsfile_testsuite
On that PR we move some final actions from a regular stage to a post-stage, which is always triggered.
In addition:
-  we include junit test collection.
- we remove `sumaform_env` parameter, as having it, the pipeline will override the value set manually on each job. We will use the same pipeline for both NUE and PROVO env.
> Finishing stage moved to always, junit, remove sumaform_env param

- jenkins_pipelines/README.md
- jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
- jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite
When we created the testsuite pipeline, we store it in manager_prs, which is wrong.
This PR creates new folders for manager and uyuni testsuites, where we can include our pipelines for QA/QAM testsuites.
> Reorganize folders

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_oracle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests
- jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequencial_testsuite
- jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
- jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_setup
- jenkins_pipelines/manager_testsuite/Jenkinsfile_qam_testsuite
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_spacecmd_unittests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests
- jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_sequencial_testsuite
- jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite
This reverts commit 315da00be5f40bf9048536141b49d4eb108e759d.
Reason: we need everyone rebasing their branches so they get https://github.com/uyuni-project/uyuni/pull/1555 and their tests are able to clean the leaked files.
Until that happens, sometimes synchronous workspace cleaning crashes while trying to cleanup a previous workspace.
> Temporary revert "Use synchronous workspace cleaning"

- jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_sequential_testsuite
- jenkins_pipelines/manager_testsuite/Jenkinsfile_qa_testsuite
- jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_sequential_testsuite
- jenkins_pipelines/uyuni_testsuite/Jenkinsfile_qa_testsuite
Card: SUSE/spacewalk#10347
We want to have the sanity checks in a different stage of the testsuite, so if the sanity checks fails, the rest of the test suite is aborted.
Related PRs:
- Manager-3.2 SUSE/spacewalk#11101
- Manager-4.0 SUSE/spacewalk#11099
- Uyuni https://github.com/uyuni-project/uyuni/pull/2073
> Move sanity check to a separate stage

- README.md
- jenkins_pipelines/README.md
- jenkins_pipelines/environments/README.md
- terracumber_config/README.md
Small rewrite to:
- Add information about new scripted pipelines used for testsuite and reference environments (also using terraform).
- Add links, to easy navigation
- Add more information about the contents of each folder
- Mark the old testsuite/reference pipelines as deprecated.
Other than the diff, you can also review the doc itself at https://github.com/juliogonzalez/susemanager-ci/tree/improve-doc
> Improve the doc, including new stuff about terracumber

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_oracle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_spacecmd_unittests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests
- jenkins_pipelines/uyuni_prs/tests_files/rubocop.sh
Our sumadockers will now use ruby2.5 for gitarro and rubocop. https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/172
So we need to update our pipelines according it.
> Upgrade Ruby2.1 to Ruby2.5

- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
Use image sles15sp2 for both, min-build and pxeboot VM's at the 4.0 branch.
This completes 'use sle15sp2 as a build host a retail terminal initial vm'
(5640b5cc7d0150f96f5e383a2ae346fd8a2b9469)
> Use image sles15sp2 for min-build and proxy

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
So we can move Server and Proxy to use Leap 15.2
That part is done at https://github.com/uyuni-project/sumaform/pull/723
> Add openSUSE Leap 15.2 to Uyuni Master

- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
Reason: because I can't test Leap 15.2 and KVM minion on Uyuni (we don't inject salt packages there, and Leap 15.2 doesn't have the correct salt 3000 yet, that wil come after 4.0.7 release).
So at least this way we can validate KVM on SLES15SP2.
> Change 4.1 and Head to use SLES15SP2 for the KVM minion

- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
It requires the PRs for DNS/DHCP merged in advance.
In the end the srv mac address for 4.1-PRV was right, but wasn't added to DNS/DNCP (the PRs do that). And to have everything right, the IPs and MACs for ref41 where bumped by adding `1`.
> Adjust mac addresses to DHCP/DNS changes requried to add suma-41-srv

- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
We had some conflicts between those developer tools channels
and our suse manager channels.
Adding those channels allow us to verify is all questions are solved.
> add dev tool channel for sles15sp2 on manager 4.1

- jenkins_pipelines/environments/manager-3.2-cucumber-NUE
- jenkins_pipelines/environments/manager-3.2-cucumber-PRV
- jenkins_pipelines/environments/manager-3.2-reference-PRV
- jenkins_pipelines/environments/manager-4.0-cucumber-NUE
- jenkins_pipelines/environments/manager-4.0-cucumber-PRV
- jenkins_pipelines/environments/manager-4.0-reference-NUE
- jenkins_pipelines/environments/manager-4.0-reference-PRV
- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-4.1-reference-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-Head-reference-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
- jenkins_pipelines/environments/manager-TEST-Naica-cucumber
- jenkins_pipelines/environments/manager-TEST-Orion-cucumber
- jenkins_pipelines/environments/manager-TEST-cucumber
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
The `activity` parameter is used so the timeout applies to "time without activity on the logs":
https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#timeout-enforce-time-limit
We could adjust it individually for each job if needed.
If you think more than 60 minutes are needed (or less), please do let me know.
I tested https://github.com/juliogonzalez/jenkins-pipeline-parameters (changing the value for `time` at `product3.2`) at my private Jenkins, and worked fine.
> Add a 60 minutes timeout for the testsuites

- jenkins_pipelines/environments/manager-3.2-cucumber-NUE
- jenkins_pipelines/environments/manager-3.2-cucumber-PRV
- jenkins_pipelines/environments/manager-3.2-reference-PRV
- jenkins_pipelines/environments/manager-4.0-cucumber-NUE
- jenkins_pipelines/environments/manager-4.0-cucumber-PRV
- jenkins_pipelines/environments/manager-4.0-reference-NUE
- jenkins_pipelines/environments/manager-4.0-reference-PRV
- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-4.1-reference-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-Head-reference-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
- jenkins_pipelines/environments/manager-TEST-Naica-cucumber
- jenkins_pipelines/environments/manager-TEST-Orion-cucumber
- jenkins_pipelines/environments/manager-TEST-cucumber
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
For some reason this is not working exactly as it should (sometimes the builds get terminated even with activity in the last 60 minutes), and no time to debug it now before going on holidays. Since I need results ASAP, I am going to switch it to a 10 hours absolute timeout with a this PR.
```
208[0m[0m
[2020-07-22T20:10:40.262Z] [32mAnd I follow "[32m[1mSoftware Channels[0m[0m[32m" in the [32m[1mcontent area[0m[0m[32m[90m                        # features/step_definitions/navigation_steps.rb:208[0m[0m
[2020-07-22T20:10:40.262Z] [32mAnd I wait until I do not see "[32m[1mLoading...[0m[0m[32m" text[90m                             # features/step_definitions/navigation_steps.rb:34[0m[0m
[2020-07-22T20:10:40.262Z] [32mAnd I check radio button …
```
> Change timeout to 10 hours and absolute

- jenkins_pipelines/environments/common/pipeline-qam-setup.groovy
- jenkins_pipelines/environments/common/pipeline-qam.groovy
- jenkins_pipelines/environments/manager-4.0-qam-cucumber
- jenkins_pipelines/environments/manager-4.0-qam-setup-cucumber
- jenkins_pipelines/environments/manager-4.1-qam-cucumber
- jenkins_pipelines/environments/manager-4.1-qam-setup-cucumber
- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
This PR migrate 4.0 and 4.1 QAM Test Environments from sumaform-test-runner to Terracumber.
We need it, so we can use the latest sumaform version, and see if using it we can fix the issues happening on deployment time for QAM 4.1.
See the related Cards:
https://github.com/SUSE/spacewalk/issues/11902
https://github.com/SUSE/spacewalk/issues/11901
> Migrating QAM from sumaform-test-runner to terracumber

- terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Update all main.tf to download and use official images by default.
We have merged https://github.com/uyuni-project/sumaform/pull/741 to
use official images by default in sumaform.   Now we need to update the main.tf
so that the default images are available.
- SUSEManager-4.1-NUE.tf:
Add the additional repos in the server
> Use official images in all CI

- terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This partially reverts commit ec1d90b43a5976883f97a3c60093357ed6028d7e.
Reestablish the main.tfs to use the well tested images.
> Revert "Use official images in all CI"

- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
Rollback:
- https://github.com/SUSE/susemanager-ci/pull/97
- https://github.com/SUSE/susemanager-ci/pull/101
- Part of https://github.com/SUSE/susemanager-ci/pull/106
Not needed anymore, as 4.1.1 is released and the packages we needed from there are already part of the "released" channels.
> Remove Development Tools repositories for 4.1

- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
For QAM testsuite:
* use second mirror (we might revert it if we use the big mirror on ceph cluster offered by paul)
* fix private network
> Mount the extra mirrors from the server

- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
With only one GB on CentOS for 4.0 and 4.1:
```
[root@suma-40-min-centos7 ~]# oscap xccdf eval --profile standard /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml >/dev/null
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml file which is referenced from XCCDF content
W: oscap:         Can't connect: 12, Cannot allocate memory.
E: oscap:         Connect: retry limit (0) reached.
W: oscap:       Can't connect: 12, Cannot allocate memory.
E: oscap:       Connect: retry limit (0) reached.
W: oscap:       Can't connect: 12, Cannot allocate memory.
E: oscap:       Connect: retry limit (0) reached.
W: oscap:       Can't connect: 12, Cannot …
```
> Let openscap run with more RAM on Centos minion on 4.0 and 4.1

- jenkins_pipelines/environments/manager-4.0-cucumber-NUE
- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
Use -o images again in 4.0 NUE
Note: if we prefer, we can close this, and do a full revert of the revert of the official images (i.e. all branches at once)
> Official images again in 4.0 NUE

- jenkins_pipelines/environments/manager-4.0-cucumber-NUE
- jenkins_pipelines/environments/manager-4.0-cucumber-PRV
- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
Salt seems to be broken on CentOS 7 official image
```
2020-09-12 05:13:31,609 [salt.utils.data  :1029][ERROR   ][1773] Invalid input for repack_dictlist: element tzdata is not a string/dict/numeric value
2020-09-12 05:13:31,610 [salt.state       :323 ][ERROR   ][1773] Invalidly formatted 'pkgs' parameter. See minion log.
2020-09-12 05:13:32,120 [salt.utils.data  :1029][ERROR   ][1773] Invalid input for repack_dictlist: element andromeda-dummy is not a string/dict/numeric value
2020-09-12 05:13:32,121 [salt.state       :323 ][ERROR   ][1773] Invalidly formatted 'pkgs' parameter. See minion log.
```
Reverting to Custom image
> Emergency fix: CentOS back to custom image

- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
Revert the emergency fix #120. 
As a side effect, this makes 4.0 fully use official images.
> Reverting: same problem on centos 7 custom

- terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
Fixing https://ci.suse.de/view/Manager/view/Manager-3.2/job/manager-3.2-cucumber-NUE/370/console:
```
10:49:25  Error: Can't retrieve base volume with name 'suma-32-sles12sp4o': virError(Code=50, Domain=18, Message='Storage volume not found: no storage vol with matching name 'suma-32-sles12sp4o'')
10:49:25  
10:49:25    on /home/jenkins/jenkins-build/workspace/manager-3.2-cucumber-NUE@2/results/sumaform/backend_modules/libvirt/host/main.tf line 41, in resource "libvirt_volume" "main_disk":
10:49:25    41: resource "libvirt_volume" "main_disk" {
10:49:25  
10:49:25  
10:49:25  
10:49:25  Error: Can't retrieve base volume with name 'suma-32-sles12sp4o': virError(Code=50, Domain=18, Message='Storage volume not found: no storage vol with matching name 'suma-32-sles12sp4o'')
10:49:25 …
```
> 3.2: Changing sles12sp4 to official image

- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
* try to have less VMs on metropolis
* stop 3.2 nue to discharge ramrod
* measure performance on reinstalled selektah
* use new network mgr.prv.suse.net
> 3.2 Provo on selektah and new network

- terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
OpenSCAP audit needs temporarily considerable amount of resources (all processes are able to consume 2.6 GiB of memory).
We need to increase memory size for this purpose.
> Increased memory for Centos 7 VM because of OpenSCAP test

- terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This PR upgrades the image used on the controller module. It will do it for all our environments.
At same time, we will change sumaform's default values, to use the new version of Leap as image for the controller module.
WARNING: This PR must be merged together with https://github.com/uyuni-project/sumaform/pull/779
> Upgrade controller to opensuse152o

- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-3.2-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
This PR prevents MAC address duplicates with private network by using a different prefix (`aa:b2:92` instead of `52:54:00`).
It also fixes one copy/paste error in QAM test suite (`ubuntu2004-sshminion` using `52:54:00:2A:47:D8` instead of `52:54:00:0E:28:39`).
See also https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/203
> Avoid false duplicate MAC addresses

- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Enable Ubuntu 20.04 on 4.0, 4.1, Head, and Uyuni.
Reference and test machines are left alone for the time being.
See also uyuni-project/uyuni#2753 for the test suite part.
> Enable Ubuntu 20.04

- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Now run the Xen cucumber tests. Also add a KVM minion on refhead to allow everyone to play with the virtualization features
> Add xen minion to 4.0+ test suites and kvm refhead minion

- terracumber_config/tf_files/SUSEManager-3.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-3.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
This PR upgrades the image used on the controller module. It will do it for all our environments.
At same time, we will change sumaform's default values, to use the new version of Leap as image for the controller module.
WARNING: This PR must be merged together with uyuni-project/sumaform#790
> Upgrade the opensuse image for the controller module

- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
We moved from ibs to scc for RES, now we need to adapt NFS accordingly.
This is the client part, see https://gitlab.suse.de/qa-css/css-infrastructure/-/merge_requests/57 for the server part.
> Mount the files that we mirror

- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
QAM 4.1: use `sles15o` instead of `sles15`
QAM 4.0: fix a missing quote
> Use SLE 15 official image

- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
This PR changes `sles15sp1` into `sles15sp1o` for QAM.
It also fixes a number of typos and resynchronizes 4.0's `main.tf` with 4.1's one.
> Use official image for SLE 15 SP1

- jenkins_pipelines/environments/manager-Head-cucumber-NUE
The last several runs took > 10 h (default limit), thus they were automatically aborted.
> Set global timeout to 12 hours for head NUE

- jenkins_pipelines/environments/manager-4.0-cucumber-PRV
Last several runs took > 10 h (default limit)
> Set global timeout to 12 hours for 4.0 @ PRV

- jenkins_pipelines/environments/common/pipeline-qam-setup.groovy
Taint also:
* the data disk for /var/spacewalk
* the extra NFS mounts from mirror2
> In the case of QAM we have more resources to taint

- jenkins_pipelines/environments/common/pipeline.groovy
- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-Head-reference-NUE
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
For now, I added support for parallel tests using a rake task on 4.1, Head, and Uyuni.
It might be that we ended to add it also to 4.0
> QA: Support running in parallel the bootstraps and some features

- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
As 4.1 was already working on ramrod.
> Revert "Move 4.1 NUE to cokeruner"

- jenkins_pipelines/environments/common/pipeline.groovy
- jenkins_pipelines/environments/manager-4.0-cucumber-NUE
- jenkins_pipelines/environments/manager-4.0-cucumber-PRV
- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-cucumber
- jenkins_pipelines/environments/manager-TEST-Naica-cucumber
- jenkins_pipelines/environments/manager-TEST-Orion-cucumber
- jenkins_pipelines/environments/manager-TEST-cucumber
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
Second part of https://github.com/SUSE/spacewalk/issues/12831
By using the environment variable PROFILE, we provide via Jenkins choice parameter, a Cucumber profile to our Rake task.
This will allow us to run a test suite running only a certain profile, which normally matches a certain group.
Note that this is the first approach. If people embrace it, we can re-visit and we might change it from a choice parameter to checkboxes, so we can select more than one profile. But that will also require a change in our product code.
> QA: Support run a testsuite filtering tests by scope

- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
We need 3 buildhosts for building all types of retail kiwi images and the same number of retail terminals. We also need to assure private network is located at the same hypervisor as proxy (branch server) and all the terminals for pxe booting.
This PR must be merged after: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/261
> QAM: Adding VMs necessary for retail tests

- jenkins_pipelines/environments/common/pipeline.groovy
- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-Head-reference-NUE
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
In order to run the SP migration by default, we must
inject the environment variable controlling that into the pipe.
Add parameter service_pack_migration with default true.
Export SERVICE_PACK_MIGRATION in all the stages that need this variable.
- jenkins_pipelines/environments/common/pipeline.groovy
- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-Head-reference-NUE
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
> Enable SP migration at reposync and init_clients stages

- terracumber_config/tf_files/SUSEManager-4.0-qam.tf
- terracumber_config/tf_files/SUSEManager-4.1-qam.tf
Fix MAC addresses for build hosts.
Add build hosts and terminals to 4.0 QAM even though it's likely to be deprecated soon.
There was also a name error "min" instead of "buildhost".
> Fix build hosts

- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation-new-hypervisors.tf
Basically a port for https://github.com/SUSE/susemanager-ci/pull/186 for the other main.tf
> Fix 15sp3 name and image for sshminion for new hypervisors main.tf

- jenkins_pipelines/environments/manager-4.1-cucumber-NUE
- jenkins_pipelines/environments/manager-4.1-cucumber-PRV
- jenkins_pipelines/environments/manager-Head-cucumber-NUE
- jenkins_pipelines/environments/manager-Head-reference-NUE
- jenkins_pipelines/environments/uyuni-master-cucumber-NUE
After the SP migration the migrated minion gets
the Salt version in SCC, i.e., and older version that
the one we should test.
Disable the SP migration while we investigate a long-term solution.
> Temporary disable the SP migration

- terracumber_config/tf_files/SUSEManager-4.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
We have SLE15SP1 client, so we need SLE15SP1 channels (same as we do for 4.1).
This starting failing since I removed SLE15SP0 from the mirror on December, and seems nobody complained, so looks to me that the ref40 environment is not that popular :-)
> Sync SLE15SP1 channels for 4.0 reference environments

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
This PR:
* uses `ssd` instead of `default` as pool for Build Validation
* splits between new SLE and debian (but only in 4.2 for now)
> Ssd pool everywhere

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
This PR uses the new "mandalore" hypervisor for Ubuntu VMs.
It also fixes a few errors:
* 4.1: missing `server_mounted_mirror = "minima-mirror-qam.mgr.prv.suse.net"` declaration
* 4.2:  `base_core.configuration` used for proxy instead of `base_retail.configuration`
* 4.2: `//sle12sp4-minion_additional_repos` used for sle12sp5
Finally it converges 4.1 and 4.2 main.tf's.
> Split new SLE and Debian on 2 hypervisors

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
4.2 build validation:
proxy moved to same hypervisor as build hosts and retail terminals
its base image needs therefore to be there as well
> Add base image for the proxy on terminus

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.1-build-validation
- jenkins_pipelines/environments/manager-4.2-beta-build-validation
Add new stage for BV create bootstrap repos with the new rake task that will be created later today. We need this to run the creation of bootstrap repos sequentially instead of parallel.
> WIP: Add new stage for BV create bootstrap repos

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
As I need to retest it again, before re-releasing, because of the problems we had with publishing for the Server and the Proxy.
> Use Uyuni-2021.04 for Uyuni

- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Fixes https://github.com/SUSE/spacewalk/issues/14634
It might cause problems in the build validation repos, we might have duplicate the additional_repos key. I will see in the next deployment and fix it. The fix would be simply to remove it from main.tf and add it in the default template in the json
> Add new experimental java in all CI runs to test

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
Remove from BV because we add them in the json and otherwise makes deployment fail
> Remove from BV because we add them in the json

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
We need to make sure the project is unlock before removing it in obs.
However, if it was not, unlocking returns an error. Let's just "force
the unlock" by running the unlock command and ignoring the error.
> CI: Force unlock and ignore errors

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
This is for PR testing. In order to prevent issues when packages are
being rebuild, which happens for example when packages are in a state A
when deploying, and state B when running the tests. Some tests will try
to install packages.
Having an error because of inconsistent metadata at the test it is very
paintful because we have to retrigger a 2 hour job.
Instead, we have a project for each environment which has links to all
packages in sm:Uyuni:Master. This way, we can disable the build before
running the tests.
https://github.com/SUSE/spacewalk/issues/14654
> CI: use a copy of master project but locked

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Links should go to sm:Uyuni:Master:TEST:XX:CR , so they get a higher
release number. Otherwise, packages could be installed from
sm:Uyuni:Master:TEST:XX:CR instead of from sm:Uyuni:Master:PR:YY
> Fix CI OBS links

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
These take 9 minutes and they are not needed always.
> Do not run smdba tests by default in Pull Requests

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Otherwise, given sm:Uyuni:Master:TEST:X:CR are links, the script always
finds out that all packages need to be updated, because it checkouts the
_link file instead of the contents.
See
https://github.com/uyuni-project/uyuni/pull/3643
> Expand links when runing push-to-obs

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
This is so, if there is no package, we force the creation of the
metadata by adding this package.
> Add release notes package to PR repos

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
We were getting the hostname of jenkins, when I was expecting the
"worker" hostname.
> Fix getting hostname where the pipeline-pull-request is running

- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.2-infra-reference-NUE
- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.2-refenv-PRV.tf
Git detected the removal of 3.2-NUE and creation of 4.2-NUE as a replacement, so better ignore the diff, and review the whole file.
Requires https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/338
> Remove 3.2-NUE, add 4.2

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
Because it has the required dependencies, so we will go from installing
more than 900 packages, which takes 15 minutes, to 115, which takes 3.
> Use opensuse152-CI-PR for server

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_changelog_test
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_check
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_lint_checkstyle
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_javascript_lint
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/manager_prs/Jenkinsfile_prs_susemanager_unittests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_backend_unittests_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_check
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_ruby_rubocop
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_migration_test_pgsql
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_schema_sql_standard_name
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_spacecmd_unittests
- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_susemanager_unittests
This PR removes the limitation of running only one build per pipeline in our unit-test.
Unless there is a real limitation for it, we should be allowing that.
> Allow parallel builds of the same unit-test job

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
The current behavior is:
- We run a job that deploys a terraform environment. Example: suma-pr1
- We save the terraform.tfstate in the workspace randomly selected for this job
- We run another job that aims to deploy with terraform a different environment. Example: suma-pr2
- We have bad luck and we re-use the same workspace used in the previous job
- The new main.tf for suma-pr2, and the terraform.tfstate for suma-pr1 collides
This PR fix it by specifying the workspace we use for each environment.
> Fix issue colliding tfstates

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
After I removed the centos 6 and ubuntu 16 I didn't fix the offset in the main.tf and now we have mismatches
> Fix wrong MACs after removal of centos and ubuntu, add 12sp5 buildhost in 4.1

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Reason: Neither SLE15 or openSUSE Leap 15.2/3 will salt 3002 until later, and we want to start testing now.
This is not needed for other OS, because for other OS we have salt as part of the client tools, so we can adjust the links.
For SLE15/openSUSE we do not want to add salt, even temporary, as it can cause a lot of problems.
> Temporary add salt 3002 to Uyuni SLE/openSUSE

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-beta-build-validation.tf
This PR does 3 things:
* it re-enables centOS 8
* it adds placehosders for additional repos for sles15 and sles15 sp1 (no idea why they were missing????)
* it adds a comment: do we really need $CLIENT, $MINION, and $SSHMINION in the BV test suites?
> Re-add CentOS 8, sle15 and sle15sp1 additional repos

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
If the user had selected the not remove build option, a new build needs
to do a clean up or it will give an error.
This commit makes sure the obs project is removed before building it
again.
> force remove previous builds in obs

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- jenkins_pipelines/environments/uyuni-prs-ci-tests
Sometimes you don't have a specific secondary test to run. In that case,
there was no option to run none of the secondary tests. This commit adds
this option.
> Add option to skip secondary tests in PR

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Otherwise, if the previous run was run with the option to not delete the
build, the next build starts with the previous project, which means you
might end up having packages that you don't want and you get an  error
when doing the linkpac for the release notes.
> Remove OBS project when starting

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
We were using test and touch for "acquiring" the test environment.
However, during our tests, we found out that two jobs could, and
actually did, take the same environment.
Most probably, this happened because two jobs run the "test" before one
of them could do the "touch".
Instead, let's use "lockfile" command, which implements semaphores,
which is what actually we were trying to implement with the "test and
touch".
Fixes https://github.com/SUSE/spacewalk/issues/15176
> Use lockfile for concurrent PR e2e testing

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- jenkins_pipelines/environments/uyuni-prs-ci-tests
After some weeks, we can drop some experimental features that do not work, and promote the one that do.
Parallel build :+1: 
Parallel client testing :-1: 
Shorten SCC timeout :-1:
> Update experimental features

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
Avoid the test suite abrubtly stopping on the controller.
Output of dmesg:
```
[12802.008861] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=ruby.ruby2.5,pid=28148,uid=0
[12802.008925] Out of memory: Killed process 28148 (ruby.ruby2.5) total-vm:16689288kB, anon-rss:16089632kB, file-rss:0kB, shmem-rss:0kB
[12802.959889] oom_reaper: reaped process 28148 (ruby.ruby2.5), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
> Avoid cucumber being killed by OOM killer

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This PR:
* gets back to 4 GB for the controller on BV test suite (after we analyzed the OOMs)
* attempts to use mortadelo instead of ramrod for Uyuni master
For a start, Mortadelo will still use a storage pool `ssd` on another disk, like it is done on ramrod.
If we still see performance issues, I will change that too.
> Attempt to use mortadelo on uyuni

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
If there was an error in the finally block, the lockfiles were not being
removed. Let's clean up the lockfiles as a first step
> Force clean up of lockfiles

- jenkins_pipelines/manager_prs/Jenkinsfile_prs_spacecmd_unittests
This PR adds the Jenkins configuration for running the spacecmd unittests also on SUMA PRs and not only Uyuni ones.
@jordimassaguerpla please review this and merge if it is okay.
> Add config for the spacecmd unittests for SUMA

- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
This is a fixup commit for #327. The Jenkins pipeline fails because of the missing openSUSE Leap 15.3 image.
> Add openSUSE Leap 15.3 to Uyuni Refmaster tf file

- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
This is a fixup that updates the channels in the Terraform file for the Uyuni reference host. Hopefully the Jenkins pipeline will succeed with this.
> Update channels for Uyuni reference host

- jenkins_pipelines/environments/common/pipeline.groovy
Related to: https://github.com/SUSE/spacewalk/issues/15779
When our Jenkins Master is rebooted, it lost connection with our Jenkins Worker, which continue running our CI jobs.
Once it restarts, it tries to connect again witht the Jenkins worker, then the current job fails, then the next job starts but using a different workspace name, appending a `@2` there.
As we rely in terraform files that are stored in the workspace between jobs, so we don't need to re-download all the images and stuff, so we can just do a taint terraform command in the current environment... all the job fails, as the workspace is different.
This PR tries to fix this issue by using always the same workspace name.
> Force a workspace name in CI jobs without @N appended

- jenkins_pipelines/environments/common/pipeline.groovy
Prepend the workspace folder into the path for CI envs
On top of https://github.com/SUSE/susemanager-ci/pull/336
> Prepend the workspace folder into the path for CI envs

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
Proxy is by default opensuse153o, but I have removed this image in
purpose because sometimes is not available. Thus, I need to specify the
alternative image for proxy as well, the same way that was done for the
server.
> Fix proxy image

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
We are not downloading opensuse152o, so better use the 15.3 image we use
for clients.
> fix controller image

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Use http instead of https because otherwise we get a 301 permanently
redirect error message. This is because openSUSE mirrors have issues
with https.
> Fix client repos

- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This content was already released so we don't need to inject any more:
https://download.suse.de/ibs/home:/fstrba:/branches:/SUSE:/SLE-15:/Update/SUSE_SLE-15_Update/
> Remove an additional repo for Java bugfix

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
Using a custom image is not working. The image we built in obs has
network issues with libvirt.
Let's use the official one. In any case we don't donwload the image
every time, only if we do a "cleanup", which happens seldomly and is
done manually. Cross your fingers the image is not unavailable at that
moment.
> Use official image for testing clients in Pull Request

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
openSUSE mirror is unreliable. For testing at the PR level, where some shortcuts are accepted, we will instead download the RPMs from obs using the API. Then, we will create a repo ourselves.
This will remove also the obs publisher from the testing. We have seen obs publisher can sometimes take a lot of time. Downloading from the build service using the API means we do not rely on the publisher.
Then, if we do this, we do not need a repo in the build service for each environment, so we can remove all the logic related to the CR subprojects. Instead, we will have a local repo in the jenkins worker for each environment.
In order to do this, we will use "osc getbinaries" for master, other and client subrepos.
For the server and proxy, we realized we also need the Other subproject, where …
> Skip opensuse mirror

- jenkins_pipelines/environments/manager-4.1-qa-build-validation
- jenkins_pipelines/environments/manager-4.2-qa-build-validation
We need bigger than 10s value due to the way the packages are loaded in the list of available packages to install (they load the whole list in a unique XMLRPC call) and sometimes it take more than 20s
> Increase default timeouts in BV

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
A stage like [this](https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/environments/common/pipeline.groovy#L71) was needed in [this](https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/environments/common/pipeline-build-validation.groovy#L41) pipeline also.
Relevant PR : https://github.com/uyuni-project/uyuni/pull/4442
Issue: https://github.com/SUSE/spacewalk/issues/15893
> Add sanity check stage

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.0-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.1-mu-aws
- jenkins_pipelines/environments/manager-4.1-qa-build-validation
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.2-qa-build-validation
- jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-Head-infra-reference-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-acceptance-tests
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
- jenkins_pipelines/environments/uyuni-mu-cloud
I just created https://github.com/uyuni-project/terracumber
A few days after the PR is merged, I will be able to remove internal repository. The few days are so the environments can run and get the new Jenkinsfiles with the new repository, and to avoid them failing.
> Use terracumber from GitHub

- terracumber_config/tf_files/SUSEManager-4.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.0-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.1-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/aws_mirror.tf
- terracumber_config/tf_files/local_mirror.tf
In preparation to terraform upgrade:
In variable declaration blocks, the type argument previously accepted v0.11-style type constraints given as quoted strings. This legacy syntax is removed in Terraform v0.15.
> change var definition to not use quotes in strings

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/common/pipeline-reference.groovy
- jenkins_pipelines/environments/common/pipeline.groovy
- jenkins_pipelines/environments/manager-4.0-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.0-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
- jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-Head-infra-reference-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-acceptance-tests
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
- terracumber_config/tf_files/Uyuni-Master-AWS.tf
- Add a new pipeline definition for Uyuni Master at AWS, as well as a new TF file
- Use the `sumaform_backend` parameter from the jobs
- Add the possibility to run jobs without tainting the environment. Mostly useful for AWS, so you don't need to pay for new instances (AWS bills by hour)
With this and https://github.com/uyuni-project/sumaform/pull/989, and I was able to launch an acceptance pipeline from a Jenkins at AWS, with no access to the R&D network at all.
Somethings are missing, however, before we can consider the work complete, but this is for other PRs, maybe even for other repositories like the testsuite.
Reference: https://github.com/SUSE/spacewalk/issues/11398
> Uyuni on AWS

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
This PR adds ARM support to 4.1 BV.
This is the same code that has already been reverted, plus the bit that was missing to make it work.
I also changed overdrive4 to overdrive3, so each test suite has its own ARM hypervisor.
I also fixed a bug in 4.2 preventing to use the JSON file for ARM.
If this still creates problems, please don't revert this time, but just comment out the problematic bit.
> Add ARM support to 4.1 BV as well

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
If a previous build was cancelled, some files might be owned by root
given it was run within a docker container.
Thus, we need to use a container again to remove them, or we will have a
permission error.
> CI: Fix build when previous build was cancelled

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
- terracumber_config/tf_files/common/nfs-mounts.sh
This PR:
* creates new NFS mounts for RedHat, for a cleaner separation of mirrors
* creates new NFS mounts for the third mirror
* factorizes the script that completes /etc/fstab and mounts the result
> NFS mounts for 3rd mirror

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Makes no sense to keep the environment locked for an extra hour if we
could not deployed. For example, this happens if there is any error
prior to the deploy phase. In that case, several retries which will take
less than an hour, will end up with all environment locked.
> Remove if not deployed

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
Partial revert of #198 : I don't see reasons why to not use mirrors for minions on 4.1 too
> Mirrors 41

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Because the repository is in a directory that depends on the
environment. If we do not publish, previous builds might be on a
different repository, so you need to publish for this environment for
the packages to be available.
> Acceptance tests at PR: Publish even if not build

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
Enabling accept_all_ssl_protocols in BVs
So we don't have issues with SLES11SP4 due to TLS 1.2 support
Related PR:
https://github.com/uyuni-project/sumaform/pull/1015
> Enabling accept_all_ssl_protocols in BVs

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
Free MAC address for Debian 11 salt and salt ssh minions.
Do not create them yet (sumaform PR is not ready yet).
See corresponding infrastructure PR https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/452 .
> Make room for Debian 11 (but do not create it yet)

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- terracumber_config/mail_templates/mail-template-jenkins-pull-request.txt
Now that we have 12 environments, we should be able to keep them for 24h without running out of them.
> Keep environment for 24h in case of failure

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- terracumber_config/scripts/set_custom_header.sh
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env11.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env12.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
This PR adds a custom header in the server web pages, to show that this is a test environment, who started and when to expect this to be removed. All this information is very useful because the same environment would be reused later for another user and you want to know if it is still the environment you deployed for you to debug, or if this is a new environment. This is more relevant now that we keep them for 24h, because it can be handy to know when the 24h had passed.
> Add custom header when deploying

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env11.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env12.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
This PR fix the workaround made by Cédric and Jordi some days ago, so we inject the variables not from the module but directly at top of main.tf
> Use mirrored images of xen and kvm as workaround of the recurrent issue with official mirrors

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env11.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env12.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
It did not work
@rjmateus will do the proper fix on sumaform so we can use the variables passed inside the module.
> Revert "Use mirrored images of xen and kvm as workaround of the recurrent issue with official mirrors"

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
Apparently, openSUSE 15.2 ARM is supported on 4.1:
```
suma-bv-41-srv:~ # spacewalk-common-channels -u admin -p admin --list | grep open.*aarch64
opensuse_leap15_1-aarch64: aarch64
opensuse_leap15_1-updates-aarch64: aarch64
opensuse_leap15_1-uyuni-client-aarch64: aarch64
opensuse_leap15_1-uyuni-client-devel-aarch64: aarch64
opensuse_leap15_2-aarch64: aarch64
opensuse_leap15_2-updates-aarch64: aarch64
opensuse_leap15_2-uyuni-client-aarch64: aarch64
opensuse_leap15_2-uyuni-client-devel-aarch64: aarch64
```
but I did not find 15.2 images similar to the 15.3 images in https://download.opensuse.org/distribution/leap/15.3/appliances/ .
Dropping ARM testing for 4.1.
> Drop ARM testing for 4.1

- jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- jenkins_pipelines/environments/uyuni-prs-ci-tests
This way, we can have a different file in our forks and use this
mechanism to reserve environments for development purposes. Otherwise we
are all the time messing up the pipeline devs use.
> Be able to select environments based on a file

- jenkins_pipelines/environments/uyuni-master-sonarqube
`git clean` complains about insufficient permissions on `.scannerwork`: use the container to remove it before.
> sonarqube: need to remove the .scannerwork from the container

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
Debian 11 is not in 4.2.5, let's assume it will not get backported from 4.3 once it's there.
It can always get reverted if that happens.
> Remove Debian 11 from 4.2

- terracumber_config/tf_files/common/nfs-mounts.sh
We were mirroring the products for openSUSE aarch64 client tools, but not NFS-mounting them.
> Add product for openSUSE aarch64 client tools

- jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
- jenkins_pipelines/environments/uyuni-prs-ci-tests
You can setup the sumaform via the environment file, which uses one or
the other value depending on the job name.
This way, we can still use a different sumaform, but it needs to be done
via changing that file. This is preferable because when changing the
sumaform, you need to do a manual clean up, so better do not make it too
easy for anyone to change this.
> Do not let user choose the sumaform repo. Simplify.

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
We are having trouble with the official repos. From time to time there
is an error. Thus, let's not use them at all.
Use minima mirror instead of download.opensuse.org
This is to minimize depending on external infrastructure such as
openSUSE mirrors.
Use an openSUSE image with no repositories at all for all openSUSE vms.
Add the repos with the tf_files, instead of using sumaform, so we can
add the ones in the minima mirror.
We are skipping update repos to avoid the problem with wrong metadata or
missing rpms. This way, it won't happen anymore plus it is
reproduceable.
> Do not use openSUSE official repos

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
I believe merging with master makes the git fetch/clone take longer
because a shallow copy is not enough if we want to merge the PR with
master.
This has the disadvantage that we are not including latest fixes from
master, so the developer will have to rebase her branch.
It has the advantage of being more stable and predictable.
> Let's not merge with git master

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Removing SLES11 from our BV4.3, as we will not support it.
> --- Comment #1 from Michael Calmer <mc@suse.com> ---
> Sles11 sp4 goes EOL in a bit more than 1 month and 4.3 gets released 4 month.
> 
> SUSE Manager 4.3 will not support SLES 11.
- We are removing the retail resources too.
- We have resource tags in all Cucumber features, so when this resources are not deployed the features are skipped (including retail features)
> QA: Removing SLES11 systems from BV4.3

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
As we must sync first common channels, and we moved it inside the same stage than custom channels, we have a conflict when we run them in parallel.
BV testsuite is designed to be fast, by running in parallel, let's keep this in mind for future refactors!
> We need a different stage for common channels

- jenkins_pipelines/environments/manager-TEST-acceptance-tests
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
As title mentioned, changes the TF files for the following environments to use Salt bundle (venv-salt-minion):
- head
- refhead
- testorion
- testnaica
- testhexagon
After this PR, the deployed instances will not have any "salt" package installed but instead `venv-salt-minion` package will be preinstalled. This changes also make the testsuite to know this instances are managed by `venv-salt-minion` and thefore proceed accordingly.
> Adjust Head and Test tf files to use salt bundle

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
-  Use minima-mirror for SCC mirroring: stabler and faster
- this goes with https://github.com/uyuni-project/sumaform/pull/1059
> Use minima-mirror for server_mounted_mirror

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
We need this to be able to skip opensuse mirrors even before the
cloudinit. Otherwise, we get this error that salt-call is not available
in CentOS because there was an error installing salt from openSUSE
mirrors.
Also, if we do not do this, we were getting an error preparing the test
repos with the dummy  package while downloading the packages from
openSUSE mirror.
> Use minima mirror for PR testing

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
RPMs for PR need to be recreated each time in the jenkins worker to
server as a "mirror" for the tests.
If we do not clean up them at the end of the pipeline, they are left in
the disc space as trash.
We run out of disc space because of this.
> Clean up published RPMS for PR

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Remove debian 9 from 4.3 BV because we no longer get updates for it and support it
> Remove debian 9 from 4.3 BV

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Add an additional repo for testing salt on the server, proxy and any
opensuse leap (kvm and xen).
> Add additional repos

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This adds the new introduced timeout parameter for a login session. It should improve the pipeline in order to have lesser automatic logouts and logins during the testsuite. In discussion with @srbarrios I set the timeout to 8h since some testsuite runs take up to 12h.
Links:
* https://github.com/uyuni-project/sumaform/pull/1074
* https://github.com/uyuni-project/sumaform/pull/1080
> QE: Add new `login_timeout` parameter to Uyuni CI

- jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
Otherwise, we do not get the latest fixes. This happened today, there
was a fix from Oscar and the reference jobs started to fail because I
was using my own fork.
> Use upstream sumaform for reference jobs (CI on PRs)

- terracumber_config/mail_templates/mail-template-jenkins-pull-request-env-fail.txt
- terracumber_config/mail_templates/mail-template-jenkins-pull-request.txt
So users can look by themselves if the infra is broken.
> Add link to grafana infra status dashboard to the email template

- jenkins_pipelines/environments/common/pipeline-pull-request-envs.groovy
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
This will add necessary changes to be able to use a new Jenkins CI pipeline for QE to test new service packs and service pack migrations.
What is still missing FMPOV:
- be able to do this for spacewalk/HEAD and not for Uyuni regarding PRs
- server and proxy should use SLES15SP4
- https://github.com/SUSE/spacewalk/issues/17410
- https://github.com/SUSE/spacewalk/pull/17629
- https://github.com/SUSE/susemanager-ci/pull/527
> QE: Add new QE testing pipeline for PRs

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
This is only the first part on integrating better Retail into Build Validation in sumaform.
The second part will allow to set up the hardware identification from the main.tf.
> Use pxe_boot sumaform module for Retail terminals

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Let's exclude tests that have the label flaky. We are not interested on
running tests that are not stable and the result is not reliable, or at
least confusing, for the developer.
partial fix for https://github.com/SUSE/spacewalk/issues/17818
> Exclude flaky tests

- terracumber_config/tf_files/SUSEManager-4.1-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Build Validation:
- remove sle 11 terminal and build host
- increase memory of proxy from 4 GB to 8 GB to avoid OOM
> BV - Remove sle 11 terminal, increase memory for proxy

- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-coverage.tf
uyuni master is now based on opensuse leap 15.4.
We need to update the scripts to download the new image on the base module definition.
> update uyuni master to leap 154

- terracumber_config/tf_files/SUSEManager-Test-Hub.tf
do not install venv-salt-minion in sles15sp3 instance
> do not install venv-salt-minion in sles15sp3 instance

- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.3-infra-reference-PRV
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
How I did this:
- Copied the 4.2 tf files and pipeline definitions as 4.3
- `tf` files and pipeline definitions: Replaced `4.2` to `4.3` and `42` to `43`
- `tf` files:  Adjusted the images to match what we have on Head
- `tf` files: Enabled the bundle and extra packages, according to what we have on Head
- `tf` files:  Increased RAM and CPU for the redhat minions, according to what we have on Head
- `tf` files:   Adjusted the MAC addresses according to the PR for the DHCP/DNS configuraiton
- `tf` files:  For the reference server, I adjusted the links to the images, and verified they are working
> Add 4.3 pipelines and tf files

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
We move the testsuite CI to use SLES15SP4. We made the changes only on Uyuni (and therefore HEAD) so we have to adjust the Uyuni `.tf`, too otherwise the testsuite will not work correctly.
See:
- https://github.com/SUSE/spacewalk/issues/17410
- https://github.com/uyuni-project/uyuni/pull/5413
- https://github.com/SUSE/susemanager-ci/pull/543
> QE: Switch Uyuni CI to use SLES15SP4 and Leap 15.4

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This modifies the image list in the Uyuni `main.tf`. The testsuite failes because the image for [SLES15 SP4 is missing](https://ci.suse.de/view/Manager/view/Manager-qe/job/uyuni-master-dev-acceptance-tests-NUE/3158/consoleFull):
```bash
16:17:37  │ Error: Can't retrieve base volume with name 'uyuni-master-sles15sp4o': virError(Code=50, Domain=18, Message='Storage volume not found: no storage vol with matching name 'uyuni-master-sles15sp4o'')
16:17:37  │ 
16:17:37  │   with module.cucumber_testsuite.module.suse-client.module.client.module.host.libvirt_volume.main_disk[0],
16:17:37  │   on /home/jenkins/jenkins-build/workspace/uyuni-master-dev-acceptance-tests-NUE/results/sumaform/backend_modules/libvirt/host/main.tf line 51, in resource "libvirt_volume" "main_disk":
16:17:37  │   51: …
```
> Modify Uyuni images

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
It seems older versions of openSUSE Leap are still needed, so I put them back in the Uyuni `main.tf` file.
> Add needed Leap 15.x images to Uyuni

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
To rule out issue and to be sure the issue is (not) coming from the mirror, we disable the mirror in the Uyuni Ci temporarily.
> QE: Temporary disable mirror in Uyuni CI

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
We still use SLE15SP2 for the client, minion and SSH minion. With the move of Uyuni/HEAD to SLE15SP4 we need to adjust the other environments, too otherwise all PR jobs will fail.
The current state in Uyuni/Head is:
server: SP4
proxy: SP4
suse-client: SP4
suse-minion: SP3 (since we want to migrate to SP4)
suse-sshminion: SP3 (since we want to migrate to SP4)
buildhost: SP4
pxeboot-minion: SP4
kvm-host: SP4/15.4
xen-host: SP4/15.4
FYI: the other terraform files that use Uyuni/HEAD should be adjusted too. The ones that use Manager 4.1/4.2 can be left with the old images.
```bash
$ grep -rin 'image = "sles15sp2o"'
terracumber_config/tf_files/SUSEManager-Test-NUE-cobbler-3.3.2:159:      image = "sles15sp2o"
terracumber_config/tf_files/SUSEManager-Test-NUE-cobbler-3.3.2:171:      image = …
```
> Move Uyuni PR test envs to SLE15SP3/SP4

- terracumber_config/tf_files/SUSEManager-4.3-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
This will move our 4.3 terraform files to use SLE15SP3 and SP4 like we do in the Uyuni/HEAD CI.
Someone from QE should have a look at the change to the build validations file.
> Switch 4.3 terraform files to SLE15SP3/4

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
If common_params was not set because an error happened before setting
it, we were getting an error about this variable not set in the final
clause. This was confusing the user and hiding the real error.
> Fix missing common_params

- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.3-infra-reference-PRV
- jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-Head-infra-reference-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Hub-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-acceptance-tests
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
- jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
In the past our pipelines were using activity timeout, instead of just a total timeout.
I think we should recover this approach, so we don't depend on how the test takes in time, but if it's doing something or not.
> QE: Recover timeout by unactivity in our test pipelines

- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Environment 9 had sles15sp4 as base system for suse-minion, instead of
sles15sp3, as the rest of the environemnts.
This was overlooked here https://github.com/SUSE/susemanager-ci/commit/bc59e05c564b38024c3f92bd821e18c2a985e832#diff-7712ea0bfd1d1f548571642c801aa3427c5c1df666d81e1d16db8a961228934a
> Fix suse version of suse-minion for environment9

- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.3-infra-reference-PRV
- jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-Head-infra-reference-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Hub-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-acceptance-tests
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
We decided to change to an activity timeout, because we had a total timeout of 10 hours that sometime aborted test suites that were totally fine. 
The reason for it is that some time ago we did not wait to have all channels fully synchronized, now we do. Plus recent timeout increases in several checks due to the lost of performance of our servers.
But it seems the activity timeout feature has a bug https://issues.jenkins.io/browse/JENKINS-58752 and so it doesn't take activity from the console output into account, failing after the 3 hours that we up.
**Therefore, we will come back to a total timeout for now, increasing it from 10 to 14 hours expecting this increase is enough big for the synchronization time added. As I'm not 100% sure how it will reacts if we remove the whole timeout …
> Changing again to total timeout instead of activity timeout (due to Jenkins bug), increasing from 10 to 14 hours

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Reverts SUSE/susemanager-ci#538
Until we have Manager-4.3 branch we can't merge the testsuite code fixes dependent from this PR. So let's revert until then, to remove some noise.
> Revert "Remove traditional client VM from Uyuni CI"

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This will change the minion and SSH minion image from SLE15SP3 to SP4
since we moved the migration from SP3 to SP4 to the build validation.
See
- https://github.com/SUSE/spacewalk/issues/18096
- https://github.com/uyuni-project/uyuni/pull/5745
> Change minion image on Uyuni/HEAD

- jenkins_pipelines/environments/manager-4.1-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.1-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.1-qe-build-validation
- jenkins_pipelines/environments/manager-4.2-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.2-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.2-qe-build-validation
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-4.3-infra-reference-PRV
- jenkins_pipelines/environments/manager-4.3-qe-build-validation
Use a different label for jenkins worker in Provo
The new label is defined in the infrastructure pillars
> Use a different label for jenkins worker in Provo

- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
This will replace CentOS 8 with Rocky 8 for our 4.3 and 4.2 build
validation.
See https://github.com/SUSE/spacewalk/issues/18030
> QE: Replace CentOS8 with Rocky 8 in BV 4.3/4.2

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Disable SLE Micro in 4.3 BV until hexagon has the bootstrap process ready.
See https://github.com/SUSE/spacewalk/issues/17352
> Disable SLE Micro in 4.3 BV

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
This will move the retail setup in BV below the smoke tests as suggested by @Bischoff.
> fix: BV: pipeline order for Retail

- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Since we moved the service pack migration from the CI to the BV, we can
now use the proper images in terraform configuration files.
[According](https://suse.slack.com/archives/C02CLBJ5RGF/p1660826764390329?thread_ts=1660822494.753399&cid=C02CLBJ5RGF) to @Bischoff these are the correct versions:
```bash
4.3 - Head - Uyuni:
client - minion - ssh_minion   SLES 15.4
rhlike                         CentOS 7.0
deblike                        Ubuntu 20.04
virthost                       SLES 15.4
4.2:
client - minion - ssh_minion   SLES 15.3
rhlike                         CentOS 7.0
deblike                        Ubuntu 20.04
virthost                       SLES 15.3
4.1:
client - minion - ssh_minion   SLES 15.1
rhlike                         CentOS 7.0
deblike                        Ubuntu 20.04 …
```
> CI: switch minions to correct service pack

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Since we moved the service pack migration from the CI to the BV we
can now use other images in our terraform files.
Split out of https://github.com/SUSE/susemanager-ci/pull/638
> PR tests: Switch minions to correct service pack

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Reverts SUSE/susemanager-ci#611
This was only a temporary change is is reverted now. @vandabarata heads up for the Uyuni CI.
Fixes https://github.com/SUSE/spacewalk/issues/18424
> Revert "QE: Temporary disable mirror in Uyuni CI"

- README.md
We had the wrong values for the virthosts in Uyuni. See e.g. https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/Uyuni-Master-NUE.tf#L210
> fix: Virthost entry in image version matrix

- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Reverts SUSE/susemanager-ci#652
Reverting because this breaks CI deployments 
https://ci.suse.de/view/Manager/view/Manager-4.3/job/manager-4.3-dev-acceptance-tests-PRV/190/console
> Revert "New variable for custom download endpoints"

- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
This will add the image names for the Red Hat-like minions on 4.3/4.2/4.1
> Define images names for CentOS 7 for 4.1/4.2/4.3

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
This will disable the minima mirror in Nuremberg for Uyuni since we do not have enough disk space to sync RES 8 required for Rocky 8.
> Temporary disable Nurenberg mirror for Uyuni

- README.md
- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
- Add a note for updating the image matrix to config
This will add a note to the configuration files to remind the developers
to adjust the image matrix as well when changing/replacing images.
- image matrix    
- move the PR test section to the very top
- add server and proxy for a complete overview
- remove 4.1 since the test suite is not running any longer and the EOL
is on 31.10.2022
> Update image matrix

- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
BV 4.2 deployment is failing because we tried to enable ARM Minion, but we did it partially.
I removed completely all trace of ARM Minion, and if we want to enable it again, please let's do it with a card in our board and all the necessary checkboxes to don't miss anything and a reviewed PR.
> Disabling again remainings of ARM Minion in BV42

- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
We updated the default image for the controller, but we did not update the BV 4.2 environment to match it.
We also enabled Ubuntu 22 SSH Minion, but we forgot regular Minion and the image in the base module.
Note:
We might have even more issue regarding my results on the last deployments, but let's fix them in parts.
> Fix deployment issues in BV 42

- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
Now that the `test-pr` target depends on `test-coverage-report` better use it as it sets the stage to fail if there are errors in the tests
> Use test-pr ant target for Uyuni PRs Java_pgsql_tests

- terracumber_config/tf_files/SUSEManager-4.1-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.1-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hub.tf
- terracumber_config/tf_files/SUSEManager-Test-NUE-cobbler-3.3.2
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-coverage.tf
All control nodes are running opensuse154o now.
Time to remove opensuse152o from the image definition
> opensuse152o is unused. Remove it from tf files

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
- Replace Leap 15.2 with 15.4 in the BV config files
- enable base_arm module again. The heat problem in Nuremberg is gone, as suggested by @Bischoff
> QE: Adjustments to 4.3 BV configuration file

- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
Reverts SUSE/susemanager-ci#685. Merge only after https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/630 got merged and the BV mirror was synced again.
> Revert "Use minima-mirror for 15.4 source"

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
In this commit 264904e5609f155be61542e6242a0b527c5b0448 , centos was updated from 7 to 8, but we forgot to also update the repositories.
> Fix CentOS repos for running acceptance tests at Pull Requests

- terracumber_config/tf_files/SUSEManager-4.2-build-validation.tf
See
https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/supported-features.html
Re-enable 4.2 tests for:
* Ubuntu 18.04
* Debian 10
* Debian 11
* openSUSE 15.4
that were disabled or removed for circumstancial reasons.
> Re-enable all minions supported in SUSE Manager 4.2

- jenkins_pipelines/environments/uyuni-prs-ci-tests
Otherwise, it is very easy to add a leading space when copying and pasting the number, and this results into an error.
> Trim pull request number

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Raise (temporarily or not) the available memory on the Uyuni-NUE test server to solve an OOM issue occurring from time to time.
> Raise available memory on Uyuni NUE server to 12GB

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
In the very early stages of preparation of the VMs, sumaform needs a Salt client to apply its configuration states. In the case of "official" images, `salt-minion` might be on the image, otherwise we install it from the `cloud-init`. We can either install `salt-minion` or `venv-salt-minion`, depending on the main.tf.
In 4.3 (but not 4.2) we need to pick the venv version. Especially that on some recent minions the `salt-minion` package might not even be available anymore in the tools. This PR addresses this.
Note: this PR sets this flag also on the SSH minions, because sumaform uses Salt to set up the SSH minions too.
> Install salt bundle on 4.3 BV

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Revert of #708. After detailed discussion with Pablo, it appears the original PR was at best useless:
* sumaform always uses salt-minion (no venv) to do its initial stuff
* BV test suite does its own stuff (first thing it does is remove all Salt stuff coming from sumaform)
The problem of absent salt-minion package on Rocky 9 might be an effect of https://bugs.rockylinux.org/view.php?id=1189 . If not, the reverted PR would not have solved the issue as sumaform always uses salt-minion, and we have to find something else.
> Revert: don't install the salt bundle on 4.3 BV

- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
Following https://github.com/SUSE/spacewalk/issues/19666, raising the available memory on the 4.2 SUSE Manager CI server from default 8GB to 10GB.
4.3 raised to 10GB as well
Head raised to 12GB to mirror Uyuni config
> Raising available memory for SUMA server to 10GB on 4.2 CI

- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
Since raising the memory to 10GB did not bring an expected fix to some issues on 4.2 , reverting to default memory attribution on 4.2 and 4.3 (8GB) to avoid raising it for no reason.
Original PR: https://github.com/SUSE/susemanager-ci/pull/713
Related card: https://github.com/SUSE/spacewalk/issues/19666
> Revert memory raise for suma CIs

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Most of us when running the BV, prefer to don't run it all at once, but run only some stages and verify all is good before moving to next stage. Or even, made some trick in between.
In order to facilitate having all in a unique job execution, I added confirmation messages that will wait until we type a key before running the next stage.
> Adding a confirmation step before each stage in BV

- jenkins_pipelines/environments/manager-TEST-acceptance-tests
- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
This PR simply restores back the `sumaform_ref` and `cucumber_ref` branches to use `master` again.
It also align "memory" parameter for the VM created for the server, according to HEAD.
> TEST: Align with "HEAD" environment

- terracumber_config/tf_files/SUSEManager-Test-NUE.tf
This PR fixes the issue we see atm in TEST environment: https://ci.suse.de/view/Manager/view/Manager-Test/job/manager-TEST-acceptance-tests/1426/console
```console
14:16:32  No hostname for 'suma-test-min-rocky8.mgr.suse.de'. Response code: 0 (RuntimeError)
```
> TEST: Use proper name for rocky8 minion

- jenkins_pipelines/environments/manager-4.2-qe-build-validation
- jenkins_pipelines/environments/manager-4.3-qe-build-validation
It make more sense to don't re-use the previous terraform state by default.
> BV 43 don't reuse previous tf state by default

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Increase disk size in 4.3 BV server because we are at the limit:
```
/dev/vdb1                                      1.5T  1.3T  119G  92% /var/spacewalk
```
> Increase disk size in 4.3 BV server

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
This will enable SLE Micro 5.2 and 5.3 for our 4.3 BV. It will only get merged once the test suite changes are ready.
- https://github.com/SUSE/spacewalk/issues/17352
> Add SLE Micro 5.2 and 5.3 to 4.3 BV

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
Temporarily disable SLE micro in BV because it fails to install timezone package because of the read-only filesystem
> Temporarily disable SLE micro in BV

- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
This adds a new variable to our terraform configuration files necessary for the Salt bundle migration tests that uses nested VMs.
See
- https://github.com/SUSE/spacewalk/issues/17238
- https://github.com/uyuni-project/sumaform/pull/1229
- https://github.com/uyuni-project/uyuni/pull/5240
> QE: Add new variables for nested VM tests

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
Fixup for https://github.com/SUSE/susemanager-ci/pull/772. I accidentally copied the image path from the 4.2 job instead of the 4.3 one and therefore I used Leap 15.3 instead oaf 15.4
> QE: Use Leap 15.4 as `hvm_disk_image`

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
Switch Head to salzbreze because ramrod is super slow, it takes hours and it gets stuck.
> Switch Head to salzbreze

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
Reverts SUSE/susemanager-ci#776 so we have uyuni running instead of head
> Revert "Switch Head to salzbreze"

- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
salt is not supported anymore for centos7. We need to use venv-salt.
Update suma4.2 dev acceptance terraform file to use salt-bundle during sumaform deployment.
> Add salt bundle for centos7 on suma42

- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
After adding a static hostname for the nested VM in the infrastructure repository, I need to make adjustments here, too. Furthermore
- the SLES image is only needed on HEAD. Uyuni and the PR tests only use Leap 15.4
- the Leap 15.4 image is necessary everywhere since we use it for the normal KVM/virtualization tests (`minkvm_guests.feature`)
- we only use those on Uyuni/HEAD, no backports at the moment
- all minions that are properly set up with DNS/DHCP in our infrastructure have their proper hostname. All others have a generic `min-nested` hostname.
See https://github.com/uyuni-project/sumaform/pull/1263
> Adjust config for static nested VM hostname

- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
This will add SLE Micro 5.1 to our 4.3 build validation. See https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/702 for the MAC addresses.
> QE: Add SLE Micro 5.1 to 4.3 BV

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
We have to do a full openSUSE Leap 15.4 sync on the server in order to onboard a Leap 15.4 nested VM. Since we already to a SLES 15 SP4 sync on the server, the Salt Bundle migration tests are only done with a SLES  image instead of a Leap 15.4 one on Uyuni and a SLES one on HEAD.
> Always use SLES for the nested VM tests

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
**What does this PR do ?**
output_****-build_validation_wait_for_custom_reposync.json are sometime malformated because two or more nodes will export there results in the same file. 
wait for custom reposync feature don't have a unique name and will be call each time we add non_mu or MU channels.
Because we are now running this steps in parallel, the timestamp can be the same.
To make this result file unique, I'm adding the node name. To do so, I need to export the node name on pipeline side and get this node name on testsuite side
**Links :**
Uyuni : https://github.com/uyuni-project/uyuni/pull/6811
SM42 : https://github.com/SUSE/spacewalk/pull/20979
SM43 : https://github.com/SUSE/spacewalk/pull/20978
> Export NODE name for reposync result file name prefix

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
This will specify the MAC addresses of the nested VM in the Salt bundle migration test. Before they were defined in an array in the test suite code which is not optimal.
- https://github.com/SUSE/spacewalk/issues/17238
- https://github.com/uyuni-project/sumaform/pull/1278
> Add CI MAC addresses for nested VM

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.2-qe-build-validation
- jenkins_pipelines/environments/manager-4.3-qe-build-validation
**What does this PR do?**
Add a new parameter for build validation allowing to disable some nodes during a run.
Build with this new parameter : https://ci.suse.de/view/Manager/view/Manager-4.3/job/manager-4.3-qe-build-validation-parallel/build?delay=0sec
I attempted to use both the `ExtendedChoice` and `Active Choice` Jenkins plugins to build the list of nodes, but unfortunately, the latter requires a plugin that is not currently installed on CI.
Active Choice allows to create more complex list ( with sub-list or sub-choices depending on a first choice). It also add a Filter feature. To describe the parameters, Active Choice is using Groovy script. The limit is the script will be executed on Jenkins Master and so we will not have access to our test environment.
I was unable with both …
> BV: Make minions/clients selectable

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
**What does this PR do ?**
Ssh minion and minion are running in parallel now. 
We can create the minion channel only once but this channel is needed for both minion and ssh minion.
The add MU repositories stage will only be executed during the minion pipeline.
The problem is the ssh minion will skip the Add MU repositories stage and will create an activation key before the minion MU channel is created.
This PR adds a wait for SSH minion during Add MU repositories stage to be sure minion MU repositories are correctly synchronized before creating the key.
I use a new variable setup in getMinionList that will be updated when minion and client finish the MU repositories synchronization.
> [BV] Add a wait during MU stage for SSH minion

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
**What does this PR do ?**
During BV pipeline, some nodes bootstrap and smoke test will fail because of UI issues.
This UI issues could come from the server side or controller side.
In my tests, the bootstrap and smoke test were more spread out ( and less users ) because I was running all the stages ( add MU / activation Key / boostrap reposync). So my nodes were not bootstrapping all at the same time.
To avoid having all the nodes ( 30 ~ ) to create a session and try to bootstrap at the same time add a random sleep ranging from 0 to 30 seconds.
This solution is not tested yet. We don't know if it will improve stability.
**Other solution**
We could also create a resource when bootstrapping saying only [2-10] nodes can bootstrap at the same time.
This solution is still open to discussion.
> [BV] Add a random wait for boostrap and smoke test

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
It seems the MAC addresses of the nested VMs in the PR test files were outdated. This PR fixes this.
See https://gitlab.suse.de/galaxy/infrastructure/-/blob/master/srv/salt/dhcpd-server/mgr_prv_suse_net/dhcpd.conf
```bash
grep -rin "nested_vm_mac"
./terracumber_config/tf_files/Uyuni-PR-tests-env4.tf:334:  nested_vm_mac =  "aa:b2:92:04:00:3b"
./terracumber_config/tf_files/Uyuni-PR-tests-env1.tf:334:  nested_vm_mac =  "aa:b2:92:04:00:0b"
./terracumber_config/tf_files/Uyuni-PR-tests-env5.tf:334:  nested_vm_mac =  "aa:b2:92:04:00:4b"
./terracumber_config/tf_files/Uyuni-PR-tests-env8.tf:334:  nested_vm_mac =  "aa:b2:92:04:00:7b"
./terracumber_config/tf_files/Uyuni-PR-tests-env9.tf:334:  nested_vm_mac =  "aa:b2:92:04:00:8b"
./terracumber_config/tf_files/Uyuni-PR-tests-env2.tf:334: …
```
> Fix `nested_vm_mac` addresses for PR tests

- terracumber_config/tf_files/Uyuni-Master-build-validation.tf
This alias is unnecessary and prevents the deployment from working. We need a default provider.
```bash
jenkins@jenkins-worker:~/jenkins-build/workspace/uyuni-master-qe-build-validation/results/sumaform> terraform plan
╷
│ Error: Missing required argument
│ 
│ The argument "uri" is required, but was not set.
```
> Remove unused alias in uyuni-bv config file

- terracumber_config/tf_files/Uyuni-Master-build-validation.tf
As discussed with @juliogonzalez and @srbarrios, we will use `uyuni-released`. When a new Uyuni version will be released and Julio prepared everything, we use a JSON to inject the new code changes from `uyuni-master` as we do for example in our SUMA BV with the MU/MIs.
> QE: switch uyuni-bv to uyuni-released

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.2-qe-build-validation
- jenkins_pipelines/environments/manager-4.3-qe-build-validation
- terracumber_config/tf_files/SUSEManager-4.3-build-validation.tf
**What does this PR is doing ?**
Synchronized sle15sp3 MU during Monitoring Server bootstrap so the repository is available for monitoring bootstrap.
Because sles15sp3 channel will be created during Monitoring Server stage, skip Add MU stage during sle15sp3 minion stage.
Currently tested in : https://ci.suse.de/blue/organizations/jenkins/manager-4.3-qe-build-validation-parallel/detail/manager-4.3-qe-build-validation-parallel/157/pipeline
Uyuni PR : https://github.com/uyuni-project/uyuni/pull/6824
> [BV] Fix monitoring bootstrap

- terracumber_config/tf_files/Uyuni-Master-build-validation.tf
Since the Uyuni BV uses openSUSE Leap for the server and the proxy and the proxy is using the base_retail module, it is necessary to add the Leap image there.
https://github.com/SUSE/susemanager-ci/blob/0e617723e297a50f6de1e613dd94857a096714c0/terracumber_config/tf_files/Uyuni-Master-build-validation.tf#L325-L330
```bash
09:57:30  ╷
09:57:30  │ Error: Can't retrieve base volume with name 'uyuni-bv-opensuse154o': virError(Code=50, Domain=18, Message='Storage volume not found: no storage vol with matching name 'uyuni-bv-opensuse154o'')
09:57:30  │ 
09:57:30  │   with module.proxy.module.proxy.module.host.libvirt_volume.main_disk[0],
09:57:30  │   on /home/jenkins/jenkins-build/workspace/uyuni-master-qe-build-validation/results/sumaform/backend_modules/libvirt/host/main.tf line 53, in …
```
> QE: Add Leap to the `base_retail` module in uyuni-bv

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
In order to have https://github.com/uyuni-project/uyuni/pull/6799 working on the Jenkins PR CI pipeline, the `testing_overlay_devel_repo` and `proxy_pool_repo` need to be installed in the proxy of every environment.
> Add repositories to PR environments

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
`testing_overlay_repo` is required on the server as well when deploying - this PR adds it to all PR CI environments.
> Add testing_overlay_repo to server as well

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
When providing a repository name in a `.tf` file, an additional `_repo` is added to the name - which was not taken into account in previous PRs related to some repositories.
This PR fixes this and removes the unnecessary repo addition on the server.
> Remove extra _repo in names

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
`testing_overlay_devel` repo seems to be needed on PR CI servers after all.
> Adding testing_overlay_devel to PR tests server

- terracumber_config/tf_files/Uyuni-Master-build-validation.tf
This fixes the name prefix that is actually `uyuni-bv-master-` instead of just `uyuni-bv-`. See https://gitlab.suse.de/galaxy/infrastructure/-/blob/master/srv/salt/bind-server/mgr_prv_suse_net/mgr.prv.suse.net.zone#L533 ff.
> Fix: Uyuni BV `name_prefix`

- terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
We'll use the following scheme:
`overdrive3`:
```
suma-bv-42-min-opensuse154arm.mgr.suse.de               suma-bv-42-min-opensuse154arm
suma-bv-42-minssh-opensuse154arm.mgr.suse.de            suma-bv-42-minssh-opensuse154arm
suma-bv-43-min-opensuse154arm.mgr.suse.de               suma-bv-43-min-opensuse154arm
suma-bv-43-minssh-opensuse154arm.mgr.suse.de            suma-bv-43-minssh-opensuse154arm
uyuni-bv-master-min-opensuse154arm.mgr.suse.de          uyuni-bv-master-min-opensuse154arm
uyuni-bv-master-minssh-opensuse154arm.mgr.suse.de       uyuni-bv-master-minssh-opensuse154arm
```
`overdrive4`:
```
suma-bv-42-min-opensuse154arm.mgr.prv.suse.net          suma-bv-42-min-opensuse154arm
suma-bv-42-minssh-opensuse154arm.mgr.prv.suse.net       suma-bv-42-minssh-opensuse154arm …
```
> Use ARM machines on overdrive3 to avoid conflict with Provo

- jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_java_pgsql_tests
Don't fail if there is the string `ref` in the PR label.
> Make sonarcloud PR variables detection more robust

- jenkins_pipelines/environments/common/openqa.groovy
- jenkins_pipelines/environments/manager-4.3-qe-openqa-offline-installation
- jenkins_pipelines/environments/manager-4.3-qe-openqa-online-installation
- jenkins_pipelines/environments/openqa
This creates 2 pipelines, one for online and one for offline installation in openqa.
Essentially we are setting up a json file that contains the variables we want to override/send to openQA and then we use that json with running the script from the openqa-executor. 
The only actual variable that you can customize is the ISO_URL for now the default it the latest from https://download.suse.de/ibs/SUSE:/SLE-15-SP4:/Update:/QR:/TEST/images/iso/
Both these jobs are running from my fork currently here:
Online: https://ci.suse.de/view/Manager/view/Manager-qe/job/openqa-installation_TEST2/ (already have a ticket with infra to rename)
Offline: https://ci.suse.de/view/Manager/view/Manager-qe/job/manager-4.3-qe-openqa-offline-installation/
> Set up new openqa installation jobs

- terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
On RH-like, we need `epel` repository because of (at least) `avahi` and `dbus-tools` packages.
However, `epel` might also contain a version of `salt-minion` we don't want.
This PR makes sure we install the bundle on all RH-like systems.
This is for the sumaform phase only, as the first thing we do in the test suite is to remove all versions of salt.
> Use bundle on RH-like

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.2-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.2-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-4.2-qe-sle-update
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-4.3-qe-sle-update
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
This PR is the next step after https://github.com/SUSE/susemanager-ci/pull/854. So you will also have the changes from this PR.
After discussion with Eric, we start to have too many options to select when using BV.
In this PR I try to simplify as much as I can the parameters ( 9 will be removed and one added with this PR ). It's just an idea open to discussion ! 
**Move some Jenkins parameters to pipeline variables ( common parameter to 4.2 and 4.3 ):** 
- `non_MU_channels_tasks_file` : path to Non Mu correspondence file. Same for 4.2 and 4.3.
- `capybara_timeout` : is it something we are changing when starting a pipeline ?  Should always be the same for stability I think. 
- `default_timeout` : same than capybara timeout
**Remove parameters useless or not use :** 
- `terraform_init` : …
> Bv hard simplication

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This will fix the wrong module assignments for some of the newly added Red Hat-like SSH minions like Liberty 9, Oracle 9 and Alma 9.
> Fix wrong module for some SSH minions

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Remove `server_configuration` for Red Hat-like SSH minions. We do not have it for other SSH minions, too.
```bash
14:02:15  ╷
14:02:15  │ Error: Unsupported argument
14:02:15  │ 
14:02:15  │   on main.tf line 864, in module "alma9-sshminion":
14:02:15  │  864:   server_configuration = {
14:02:15  │ 
14:02:15  │ An argument named "server_configuration" is not expected here.
14:02:15  ╵
```
> Fix Red Hat-like SSH minion configuration

- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
the venv must be preinstalled on 4.2 minions as we don't reposync
> Use Salt bundle on 4.2

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
SSH Minion and minion both need the minion MU repository when testing in BV. But we only can sync MU repository once. To solve this situation, only minion stage is creating the MU channel and ssh minion will use it.
Because ssh minion and minion are running in parallel, during add MU stage ssh minion are using a Jenkins waitUntil to wait the minion add MU stage to finish.
If the add MU minion stage fails, the add MU minion stage will wait forever that the MU minion stage succeed. 
To solve this situation, I changed `mu_sync_status[node]`  variable to string so it can store three states : 
- `NOSYNC`, set when creating the variable
- `SYNC`, set after minion add MU stage succeed
- `FAIL`, set if minion add MU stage failed.
The waitUntil will then wait for `SYNC` status or `FAIL`. And a …
> [BV] Correctly fail add MU ssh minion stage if minion stage fails

- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
Revert of partial revert of ca81feef1060ff8cb51dda6d12a2ec026fedeac6
Rationale is: bundle is now the default for bootstrapping on 4.2, so we want to test with bundle on every minion
Otherwise we get both `salt-minion` and `venv-salt-minion` running at same time
> Use the bundle everywhere again for 4.2

- terracumber_config/tf_files/SUSEManager-4.2-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
CI: It does not really make sense to preinstall the bundle on trad clients
(nor on any SLE system for that matter, as we reposync)
> It does not really make sense to preinstall the bundle on trad clients

- terracumber_config/tf_files/SUSEManager-4.2-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
Align the TF files for Provo 4.2 and 4.3 CI with their corresponding TF files from Nuremberg .
The following minions are not aligned vcpu-wise in order to avoid over-committing the amount of vcpus in 4.3:
- SLE client
- SLE minion
- SLE SSH minion
- Debian minion
- PXE boot minion
> QE: Align tf files

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
cloud-init will only run on images that end with 'o'. Thus, we need to append 'o' to opensuse-ci-pr image name.
We need to force installation of venv-salt-minion into server, so that we can use salt+sumaform to configure it.
Fixes https://github.com/SUSE/spacewalk/issues/21704
> Fix install venv-salt-minion to opensuse server and proxy vms.

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Reverts SUSE/susemanager-ci#886
This did not fix it.
> Revert "Set install_salt_bundle to false for the server"

- terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
According to https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/supported-features.html Rocky 9 is supported on 4.2.
> Add Rocky 9 to 4.2 BV

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
We had duplicated MAC addresses for our openSUSE 15.x ARM minions and SSH minions in NUE and PRV.
> Fix duplicate MAC addresses in the Uyuni BV

- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
Change scheduling of Hexagon pipeline, since it's currently used for testing containerized server and it takes around ~11 hours.
> change Hexagon pipeline schedule

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
bootstrap and run smoke tests look stable now in term of login page failing.
I have login page failing or server not responding during add MU stages now.
I would like to add randomWait() to all parallel stages calling the web interface to see if it's improve the stability.
It will spread a little more the web interface callls and probably stabilize the test.
> Add random wait before web interface calling stage during parallel

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Harmonize Capybara timeout to be setup for all the rake calls.
Remove random wait from Add MU / Add Non MU and create Activation Key ( I was able to reproduce the same behavior even with the wait ). It was more likely trigger by a too short timeout during login.
Add a persistent file state to manage the MUs shared by monitoring and sles15sp4_minion.
Indeed they are using the same MUs, you can't add twice the same MU.
I created a file so we keep the monitoring state between run.
> [BV]Harmonize capybara timeout / monitoring persistent

- README.md
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
This will move all minions from SLES to openSUSE Leap 15.4 on Uyuni and the pull request tests.
See:
- https://github.com/SUSE/spacewalk/issues/20945
- https://github.com/SUSE/spacewalk/issues/10235
> Uyuni: Switch from SLES to openSUSE Leap

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
To create the SSH minion Activation Key, we need to have the minion Custom Channel available
I created `CustomChannelStatus` variable to check if the Add MU (and|or) Add Non MU stage are finished for the related minion.
SSH minion needs the bootstrap repository during the bootstrap. 
This bootstrap repository is created by the minion version of themself during create bootstrap repository stage.
Now that auto create bootstrap repository is disable during BV, it has to be trigger by minion.
It's a good think because now we are sure that the bootstrap repository have correctly all the custom channel ready when created.
Before that, some ssh minions were probably bootstrap without having the custom channel...
Create a new variable `BootstrapRepositoryStatus` to manage bootstrap repo creation …
> Move sync between minion and ssh minion during the create bootstrap

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Change BV pipeline to correctly create activation for ssh minion after waiting for MU and no MU channel has been created.
minion_name_without_ssh needs to be declared locally or it will be replaced dynamically by the last updated value.
> Create activation key for ssh minion

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This will also use openSUSE Leap 15.4 for the monitoring server in the Uyuni BV.
> Use openSUSE Leap for monitoring in Uyuni BV

- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This will
- remove Liberty Linux 9 (no support, yet)
- switch from `uyuni-released` to `uyuni-master`
> Adjust the Uyuni BV

- terracumber_config/tf_files/Uyuni-Master-K3S.tf
Since I keep having issues with 15.4 repo metadata, let's try 15.5
> Move k3s CI to Leap 15.5

- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
use sles15sp4 image instead of opensuse154o, to fix quickly podman tests. We should remove it once master acceptance tests will be green again.
```
"comment": "An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r3fab6dc3997e4c4c807c15d793b15a9e.scopeLoading repository data...\nReading installed packages...\nResolving package dependencies...\n2 Problems:\nProblem: the installed product:Leap-15.4-1.x86_64 conflicts with 'namespace:otherproviders(distribution-release)' provided by the to be installed product:SLES-15.4-0.x86_64\nProblem: the to be installed product:SLES-15.4-0.x86_64 requires 'product(SLES) = 15.4-0', but this requirement cannot be provided\n\nProblem: the installed product:Leap-15.4-1.x86_64 conflicts with …
```
> temporary fix: use sles15sp4o instead of opensuse154o

- README.md
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
We want to test the build host. Right now openSUSE Leap is not supported as base OS for the build host.
> Revert buildhost to use SLES instead of Leap

- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Due to missing support for openSUSE Leap as underlying base OS for the pxeboot-minion, we revert back to SLES15 SP4.
> Revert pxeboot-minion from Leap to SLES15 SP4

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
see https://github.com/SUSE/spacewalk/issues/21562
This supersedes https://github.com/SUSE/susemanager-ci/pull/932
> CI: Update minions to leap 15.5 for uyuni-master-nue

- terracumber_config/tf_files/SUSEManager-4.2-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.2-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This is just a proposal to speed up our BV tests.
Currently we have extra java logs printed out by default. With this PR, we will disable those extra debugging logs.
> Disable java_debugging in BV environments

- terracumber_config/tf_files/Uyuni-Master-NUE.tf
If we use 15.5, we have problems installing npm8. Better use this one for now, and once tests pass, we work on switching the controller.
Adding the opensuse154o image, will fix the controller that uses 15.4.
> Use opensuse 15.4 for the controller

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
If we use the one for CI PR (opensuse155-ci-pro), we have an issue installing the needed kvm packages, because we do not have the update repo available.
> Use opensuse 15.5 official image for kvm-host

- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
Seems https://github.com/SUSE/susemanager-ci/pull/951 took care of the acceptance test environment for master, but didn't change refmaster.
So refmaster fails  with:
```
07:44:40  │ Error: Can't retrieve base volume with name 'uyuni-refmaster-opensuse155o': virError(Code=50, Domain=18, Message='Storage volume not found: no storage vol with matching name 'uyuni-refmaster-opensuse155o'')
> Add the Leap 15.5 image to the Reference environment for Master

- terracumber_config/tf_files/Uyuni-Master-K3S.tf
In master is working, so let's apply it here as well.
> Update to leap 15.5: kvm isos in K3s

- .github/workflows/sumaform-validation.yml
Some .tf files have post-deployment provisioning steps that try to ssh into deployed hosts. Since the 'null' provider doesn't actually deploy any hosts with 'apply', these provisioning steps fail.
> Terraform validation: Use 'plan' instead of 'apply/destroy'

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
**Provo only, temporary only**
We are hitting uyuni-project/uyuni#7637 on 4.3.9 preliminary deployment tests.
The problem is partially on our side: we should not use Uyuni stable for the client tools when we are testing SUSE Manager. I have seen we are doing it on every type of minion in `user-data.yaml` in sumaform :-( .
Before we fix it one way or another, we will test without Debian 10 nor Ubuntu 20.04, so we can at least deploy the BV test suite.
> Temporarily disable Debian 10 and Ubuntu 20.04 minions

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This PR tells to use the bundle for every Debian 12 instance.
As there's no real choice, I would have preferred to do it in sumaform, but I did not manage.
Tested to work on debian12 minion in 4.3 BV PRV.
> Debian 12 is bundle-only

- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env5.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
I'm currently working on a main.tf template to be use accross all PR testing ( NUE / PRV and uyuni / manager ).
We are already using normalize name for suse minions but not for rh and deb like minions ( those normalize names are already used in CI ) .
This PR will normalize rh and deb minion name.
Require : https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/813
Related to : https://github.com/SUSE/susemanager-ci/pull/898
> Use normalize name for rh and deb like minion in uyuni PR testing

- .github/workflows/sumaform-validation.yml
Fixes:
- Add missing variable declarations (all mandatory variables must be set in env)
- Remove additional `libvirt` provider definitions
- Consider "commented out" lines in regexps
> Fix validator for all .tf files

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
This might work around issue https://github.com/uyuni-project/uyuni/issues/7637 that prevents from deploying Debian 10 and Ubuntu 20.04.
If that does not work out, we'll simply disable them for the time being.
> Try to work around dependency issue

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This will
- add a workaround for Debian 10 and Ubuntu 20.04
- remove the Debian 9 comment
> Uyuni BV: Add workaround for Deblike minions

- jenkins_pipelines/environments/manager-4.3-qe-sle-update
The possibility to check the stage is still there, even if it's not used by default. Checking the stage and running it would cause an error:
```
Don't know how to build task 'cucumber:build_validation_add_maintenance_update_repositories_monitoring_server' (See the list of available tasks with `rake --tasks`)
```
Removing it should prevent this from happening.
> Remove monitoring stage from QE SLE testsuite since we do not deploy monitoring server

- .gitignore
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/scripts/maintenance_json_generator.py
Addressing https://github.com/SUSE/spacewalk/issues/22506
This PR introduce a new parameter in our BV pipeline (only regular pipeline, not AWS).
- The name of this parameter is "mi_ids" and it expect a list of MI identifiers separated by comma without whitespaces.
- If this parameter is not empty, it will overwrite the JSON provided on the parameter "custom_repositories".
- We moved the script to generate the JSON from the spacewalk/uyuni repository to susemanager-ci repository, that way we can call it without depending on a controller deployment.
- In order to call OSC command, we are using an extra Jenkins node in the pipeline, for all the rest we keep using the same node.
> New BV pipeline parameter to provide a list of MI IDs and generate the JSON on the fly

- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
fixes https://github.com/SUSE/spacewalk/issues/22702
We need to keep 15.4 image because the controller is 15.4
> Use 15.5 in Hexagon Pipeline

- jenkins_pipelines/environments/manager-TEST-Ion-acceptance-tests
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
Update `manager-TEST-Ion-2obs` job to point to `spacewalk/Manager-4.3` and add a repo to the instance to test the `python-requests` version bump.
> Update Test Ion gitrepo and infra

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Due to offline hardware (overdrive3/4), we need to temporarily disable the ARM minions in our BV.
> BV: temporarily disable ARM minions

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
As we are waiting to synchronize the different channels at the same time we trigger the synchronization of them, we don't need any more this separate rake task.
> Synchronization of MU repositories is done when we add them.

- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- jenkins_pipelines/scripts/maintenance_json_generator.py
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
As the title implies, I've added some entries to support SLE Micro 5.5 in our BV pipelines.
This is related to https://github.com/SUSE/spacewalk/issues/22824
Edited files include:
- BV terraform configuration files 
-  BV Jenkins pipelines
- [maintenance_json_generator.py](https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/scripts/maintenance_json_generator.py)
> QE: Add BV entries for SLE Micro 5.5 minions

- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env6.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env1.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env10.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env2.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env3.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env4.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env7.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env8.tf
- terracumber_config/tf_files/Uyuni-PR-tests-env9.tf
Remove an old FIXME
This will hopefully remove that error:
```
[2023-12-14T14:32:22.663Z] ^[[0m^[[1mmodule.cucumber_testsuite.module.debian-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec):^[[0m ^[[0mpkg_resources.DistributionNotFound: The 'contextvars' distribution was not found and is required by salt
```
> The bundle is now available on Ubuntu too

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf
- terracumber_config/tf_files/aws_mirror.tf
- terracumber_config/tf_files/local_mirror.tf
Add a new deployment description using paygo instances
- server paygo
- proxy byos
- sles15sp5 paygo
- sles12sp5 paygo
- slesforsap15sp5 paygo
This new deployment is needed to test paygo in AWS using testsuite.
Remove known unsupported clients for paygo setup: 
- sles15sp3 and sles15sp2 LTSS not available with paygo instances
- ubuntu products not available by default
- retail branch
- no sle micro available
- https://github.com/uyuni-project/sumaform/pull/1426
- https://github.com/uyuni-project/sumaform/pull/1418
- https://github.com/uyuni-project/sumaform/pull/1428
- https://github.com/uyuni-project/sumaform/pull/1430
- https://github.com/uyuni-project/sumaform/pull/1431
- https://github.com/uyuni-project/sumaform/pull/1446
- https://github.com/uyuni-project/sumaform/pull/1445
- …
> Paygo aws pipeline

- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env6.tf
- terracumber_config/tf_files/SUSEManager-4.3-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hub.tf
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
- terracumber_config/tf_files/tfvars/PR-testing-manager43.tfvars
On sumaform side, controller is now using opensuse155o. 
opensuse155o was not declared in most of ci descriptions. 
This PR adds opensuse155o when needed or bump opensuse154o to opensuse155o when opensuse154o was only used for controller.
> Bump controller image version from opensuse154o to opensuse155o

- jenkins_pipelines/environments/common/pipeline.groovy
Backport changes from BV to ci test to manage timeouts.
Those changes are needed because PR is failing with a 4 minutes timeout on onboarding event.
This come for a changes in how we set the default timeout. Before, it was hard written in code at 500. For more flexibility between infra, we use a parameter now.
> Add default timeout to ci acceptance

- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
Depends on https://github.com/uyuni-project/sumaform/pull/1454
This PR aims to setup a bigger disk size for pgsql partition, as otherwise we had problems on CI tests, when we run the backup/restore test.
**Will those disk sizes make sense to you?**
I set up the official minimal size, but maybe we can work with less in CI?
```
suma-43-srv:/var/spacewalk # du -h -d0
54G	.
suma-43-srv:/var/lib/pgsql # du -h -d0
6,5G	.
```
Note: In Uyuni, I expect more, as we synchronize Leap (even if we kill it later) + SLES15SP4. But I don't have a working CI testsuite to check it.
> Set external disks for repository and database

- terracumber_config/tf_files/PR-testing-template.tf
- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env6.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/tfvars/PR-testing-NUE-environments.tfvars
- terracumber_config/tf_files/tfvars/PR-testing-PRV-environments.tfvars
Related to https://github.com/SUSE/spacewalk/issues/22410
We'll test the migration from OS Salt to Salt bundle only on a dedicated BV host.
The entries for a minion running in a nested VM are thus no longer needed.
> Remove nested VM entries

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Title - It was pointing to a non-existent "base" module
> Set the correct base config module for salt-migration-minion

- .github/workflows/sumaform-validation.yml
One design problem of current sumaform is that we can have only one backend symlink for all modules.
The sumaform tests on github actions set this symlink to the null provider, but the s390 module still points to the s390 provider for its backend.
This PR solves the issue by installing the s390 provider and tweaking the tf files a bit more.
> Let sumaform tests pass with the s390 provider

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
Keep database content inside the root partition on BV.
Otherwise we have too many free space in the root partition that it will never be used.
Note: We might have a similar consequence in our CI envs, but for now, we will keep it as it is there, as we are unsure about how to resize the root partition and the current size (200GB) is not enough for Database Backup/Restore test.
> Keep database content inside the root partition on BV

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Remove wait_for_product_reposync since it does not correspond to rake task:
It should fix this:
```
10:29:15  + ./terracumber-cli --outputdir /home/jenkins/workspace/manager-4.3-qe-sle-update/results --tf susemanager-ci/terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf --gitfolder /home/jenkins/workspace/manager-4.3-qe-sle-update/results/sumaform --logfile /home/jenkins/workspace/manager-4.3-qe-sle-update/results/84/testsuite.log --runstep cucumber --cucumber-cmd 'export BUILD_NUMBER=84; export BUILD_VALIDATION=true; export CAPYBARA_TIMEOUT=60; export DEFAULT_TIMEOUT=500;  cd /root/spacewalk/testsuite; rake cucumber:build_validation_wait_for_product_reposync'
10:29:16  Running command...
10:29:16  rake aborted!
10:29:16  Don't know how to build task …
```
> Remove wait_for_product_reposync since it does not correspond to rake task

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
We didn't save properly the exit codes and on print there was no need for escape, we would have run into a similar problem, we don't want to treat the exit code as a command.
> Catch and return the status codes properly

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
- jenkins_pipelines/environments/common/pipeline.groovy
Move rename server and samba test into new rake file.
finishing.yml and finishing_pr.yml are now the same.
Depends on :
- https://github.com/uyuni-project/uyuni/pull/8128
- https://github.com/SUSE/spacewalk/pull/23374
> Update the CI pipeline to use the new secondary rake file

- README.md
We switched to openSUSE Leap 15.5 but forgot to update the image version matrix accordingly.
> Update image version matrix

- jenkins_pipelines/environments/common/pipeline.groovy
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-AWS
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-4.3-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Hub-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Ion-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-K3S
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-PRV
- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-podman
We currently have the capybara timeout and the default max timeout set for all the environments at the pipeline description level.
When the timeout is too short, PRV envs will timeout on some onboardings and if the timeout is too long, the execution time for the pipelines will drastically increase.
To fix this issue, I would like to have the timeout set at the environment description level. So we can easily have different timeout depending on where we run the tests.
Adapting those timeouts are now required because of the BV stabilization backport.
I had a in between timeout before to try to make it work on both envs.
In this PR I reduce the timeouts for NUE ( I had no issue so far with those timeouts ) and increase back the timeout for PRV when the CI was running correctly.
It should …
> Make the timeouts unique to each environment

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-almalinux9-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-sles15sp5
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-sles15sp5-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-ubuntu2204-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-almalinux9-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-sles15sp5
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-sles15sp5-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-ubuntu2204-bundle
This PR simply fixes the configuration for the `URLTrigger` scheduler set in some Salt Shaker jobs:
- Add node to run the URLTrigger execution.
- Replace the URL to monitor for Salt Bundle to testsuite repository.
- Monitor a change on the MD5Sum of the content of the URL.
The "URLTrigger" is only configured for:
- `products:testing` -> SLE15SP5 (classic & bundle), AlmaLinux9 (bundle) and Ubuntu2204 (bundle)
- `products:next` -> SLE15SP5 (classic & bundle), AlmaLinux9 (bundle) and Ubuntu2204 (bundle)
> Fix URLTrigger schedule for some Salt Shaker tests

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-almalinux9-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-sles15sp5
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-sles15sp5-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-ubuntu2204-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-almalinux9-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-sles15sp5
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-sles15sp5-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-ubuntu2204-bundle
I'm having issues to make "URLTrigger" plugin to find nodes where to run.
According to https://www.jenkins.io/doc/pipeline/steps/params/pipelinetriggers/ , now passing both `triggerLabel` and `labelRestriction` parameters I think this should work.
> Make sure URLTrigger finds nodes to run for Salt Shaker

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-almalinux9-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-sles15sp5
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-sles15sp5-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-ubuntu2204-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-almalinux9-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-sles15sp5
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-sles15sp5-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-ubuntu2204-bundle
I just realized there was a problem on how the parameters were passed to `URLTrigger` and that is what was causing the final pipeline didn't get the expected configuration for URLTrigger.
Reference: "URLTrigger section" at https://www.jenkins.io/doc/pipeline/steps/params/pipelinetriggers/
> Fix issue on how parameters are passed to URLTrigger

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Use the new controller variable created in https://github.com/uyuni-project/sumaform/pull/1465 to enable the catch timeout mechanism during BV pipelines.
> Enable catch timeout message for BV pipelines

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Rationalizing, the initial numbering was done in the middle of datacenter move and s390 network separation, so it was a bit of a mess.
> Renumbering s390 in prevision of addition of 5.0

- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
- terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env6.tf
Tests on deblike minions are failing. Disabling them so this is usable.
> Disable deblike minions in 4.3 PR testing

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- Removing not implemented options to use special partitioning of the VM disk resources
- Adding the required variable to get known as containerized server
> Tweak Head CI for SUMA containerized server options

- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This will add new pipelines and terraform configuration files for a new HEAD/5.0 BV.
- According to Cedric we do not need the Helm charts for SUMA/5.0.
See https://github.com/SUSE/spacewalk/issues/23078
> Add a new HEAD BV

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
As we don't have yet support to deploy a containerized proxy for Head. Let's keep for now Proxy VM out of Head test environments, until we do.
> CI: remove proxy from head test pipelines

- README.md
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-AWS.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
- terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars
This PR
- removes the old openSUSE Leap 15.4 images from the image lists
- switches all the remaining minions from openSUSE Leap 15.4 to 15.5
- updates the CI version matrix accordingly
> Update minions to openSUSE Leap 15.5

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
* Re-enabled SLE Micro 5.5 in 4.3 (was temporarily disabled)
* Switched SLE Micro 5.5 to cloud-init in every branch
> SLE Micro 5.5 now uses cloud-init

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
This PR fixes the image names of SLE Micro 5.5 according to the recent changes in sumaform.
See https://github.com/uyuni-project/sumaform/pull/1483
> Fix SLE Micro 5.5 image names

- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
On uyuni branch:
```
/dev/vda3                                         200G  5.7G  195G   3% /
/dev/vdb1                                         196G  175G   12G  95% /var/spacewalk
/dev/vdc1                                          49G   17G   31G  35% /var/lib/pgsql
```
This PR shrinks `/` and enlarges `/var/spacewalk`.
> Tune disk sizes for CI

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
In the prevision of movement from Provo to a new datacenter, where we might have to drop some machines, use hosts with more cores and more RAM.
Also, unlike in NUE, there's no need to use same hypervisors for Uyuni and 5.0 in Provo.
details:
```
BV Uyuni
caipirinha             Cat. A
--> giediprime           Cat. C, but with 3 TB disk
hugo                   Cat. C
--> margarita            Cat. A
irishcoffee            Cat. C
--> caipirinha           Cat. A
BV 4.3
giediprime             Cat. C
--> moscowmule           Cat. A
BV 5.0 (formerly BV 4.2)
(taking 4.2 hypervisors, with no change)
Cat A: 128 GB, 48 cores
Cat B:  96 GB, 24 cores
Cat C:  64 GB, 12 cores
caladan and arrakis are Cat. C, but have 3 TB disk space - keeping them unchanged
```
> Better allocation of hypervisors in Provo

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- jenkins_pipelines/scripts/maintenance_json_generator.py
Make the name of SLE 15 SP5 s390 minions aligned with the Cucumber tags used in the testsuite:
> **@sle15sp5s390_minion, @sle15sp5s390_ssh_minion**
Remove **salt_migration_minion** from the list as migration(s) testing is not yet properly supported in the pipelines.
> BV: update minionList

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
Disable mirror usage in Head and Uyuni podman. 
Issue: Fixes https://github.com/SUSE/spacewalk/issues/23570
Also some empty lines removal.
> Disable mirror usage in Head and Uyuni podman

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
Removing proxy from HEAD again, so we can reach secondary tests, which is a priority - repeating what was done in https://github.com/SUSE/susemanager-ci/pull/1089 and discussed in https://suse.slack.com/archives/C02D134507M/p1707474456766809
> QE: Remove proxy from HEAD

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
According to https://github.com/uyuni-project/sumaform/blob/master/README_TESTING.md#using-salt-bundle-venv-salt-minion-in-head-and-uyuni, we should use the Salt bundle for all minions on HEAD. Pablo confirmed this in [Slack](https://suse.slack.com/archives/C02CY2CLLH3/p1707484962948199).
I am not 100 % sure if this will work for the SLE Micro 5.x minions and the new s390 ones.
> Add the Salt bundle to all minions in the 5.0 BV

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Move all 24 minions from `overdrive3` and `overdrive4` to suma-arm
(We were missing IP and MAC addresses for 5.0 Provo -- added them)
> Re-enabled the 24 ARM minions

- .github/workflows/sumaform-validation.yml
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This PR
- fixes the CI with respect to the Feilong version bump (0.0.4 -> 0.0.6)
- removes the Salt bundle for SLE Micro SSH Minions (This is not supported, yet. See https://bugzilla.suse.com/show_bug.cgi?id=1208045)
> Remove Salt Bundle from SLE Micro SSH Minions

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This does not work in sumaform properly, yet, because the Salt state for handling additional packages does not take transactional systems into account. 
https://github.com/uyuni-project/sumaform/pull/1509 fixes this state, but there is still the problem with a necessary reboot.
> BV: Disable Salt Bundle for SLE Micros in 5.0

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This updates the server container URL for the 5.0 Beta 1 BV.
> BV: Use the correct 5.0 Beta 1 URL

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Closes https://github.com/SUSE/susemanager-ci/issues/1108
Docs for the sh global function state this about using returnStatus
>Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example
Currently most of the steps for the proxy save the returnStatus to a variable but don't use it to determine whether a failure occurred or not. The same holds true for the monitoring server.
Only the MUs stages will properly fail if a script execution does not return with 0.
> BV: check sh return code in all proxy and monitoring stages

- terracumber_config/tf_files/Uyuni-Master-K3S.tf
Increase disk space of Uyuni K3s to 250GB.
Otherwise, it becomes unstable when it finish, as it consumes too much disk space, the root cause it might be the DB backup test, but I don't have the time to debug it, I need to unblock this issue to be able to debug a more important issue configuring the Proxy. Therefore, I will increase the size of that disk in our terraform file.
```
Events:
Type     Reason            Age                  From               Message
----     ------            ----                 ----               -------
Warning  FailedScheduling  32m (x67 over 6h2m)  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.. …
```
> Increase disk space of Uyuni K3s to 250GB

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This will add the new containerized proxy to the 5.0 BV. I had to remove some of the options, since they are not available on the containerized proxy. See https://github.com/uyuni-project/sumaform/blob/90ef843cc7a62184328bfe23d13d4393c5957480/modules/proxy_containerized/main.tf
Depends on https://github.com/uyuni-project/sumaform/pull/1529
> QE: Add containerized proxy to 5.0 BV

- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
As default, we will deploy server_containerized in uyuni_master product version using "leapmicro55o".
> Mirror "leapmicro55o" image tf files deploying server_containerized

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
Fixes https://github.com/SUSE/spacewalk/issues/23908.
We have a variable for the container tag in sumaform
https://github.com/uyuni-project/sumaform/blob/b16b99d312db4093b06781e75b71d95794a8b60e/modules/server_containerized/main.tf#L43
but we are not using it. Therefore, we do not use the latest image in our Uyuni Podman and HEAD CI.
> Use `latest` container tag in Uyuni and HEAD

- terracumber_config/tf_files/PR-testing-template.tf
Align disks sizes in PR Tests and Uyuni CI.
As we are experiencing a full disk space in Uyuni PR tests
> Align disks sizes in PR Tests and Uyuni CI

- terracumber_config/tf_files/PR-testing-template.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
We are experiencing this issue:
And we though it could be related with the implementation we made of additional disks.
Cedric Bosdonnat:
> For some reason postgresql is already started and the /var/lib/pqsql/.bash_profile is gone
> /var/lib/pgsql and /var/spacewalk are mounted volumes in the Jenkins PR CI... is that expected? It seems this mount hides the .bash_profile
> In server containerized use only main_disk

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Fix typo in comparison
fixes error:
```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 7269fbd1-3333-49c4-8199-23e46f59c37a
org.jenkinsci.plugins.workflow.cps.CpsCompilationErrorsException: startup failed:
Script1.groovy: 59: expecting '(', found 'res_python_script' @ line 59, column 32.
if res_python_script != 0 {
^
1 error
```
example happening: https://ci.suse.de/view/Manager/view/Manager-4.3/job/manager-4.3-qe-sle-update/113/console
> Fix typo in comparison

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
This will adapt the regular BV (Uyuni, 5.0, 4.3) to take the 2 proxy types (traditional, container) into account, by
- introducing a new Jenkins variable called `proxy_type`
- having a choice in Uyuni/5.0 (defaults to `proxy_container`)
- having a choice in 4.3 (defaults to `proxy_traditional`)
> BV: Add proxy type selection

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
Temporary changes only for the 5.0 BV NUE configuration file.
- use the devel container until the 5.0 Beta 2 submissions are ready
- disable the mirror to verify a bug in the Product Wizard
> QE: Change the 5.0 BV confituration for testing

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This will add missing sumaform dummy parameters to the 5.0 BV configuration file in order to get the deployment working. Those values will be needed for the retail tests, but they are not yet migrated to the containerized setup. So these dummy values will be enough for now.
```bash
[2024-03-22T12:27:10.718Z] Terraform has been successfully initialized!
[2024-03-22T12:27:10.718Z] 
[2024-03-22T12:27:10.718Z] You may now begin working with Terraform. Try running "terraform plan" to see
[2024-03-22T12:27:10.718Z] any changes that are required for your infrastructure. All Terraform commands
[2024-03-22T12:27:10.718Z] should now work.
[2024-03-22T12:27:10.718Z] 
[2024-03-22T12:27:10.718Z] If you ever set or change modules or backend configuration for Terraform,
[2024-03-22T12:27:10.718Z] rerun …
```
> 5.0 BV: Add missing sumaform parameters

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
This will temporarily disable Liberty Linux 9 in the 5.0 BV in NUE due to firewall issues.
> 5.0 BV: Temporary disable Liberty Linux 9

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
Follow-up of https://github.com/SUSE/susemanager-ci/pull/1138
Related to https://github.com/SUSE/spacewalk/issues/21702
Adds the mi_ids parameter to the current 4.3 AWS pipeline and uses it to generate the **custom_repositories.json** file calling `maintenance_json_generator.py`.
The `--no_embargo` instruct the script to discard MIs containing fixes which are still under embargo.
> BV-AWS: Add and use mi_ids parameters to generate custom repositories

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Fixes: 
```
09:43:15  Don't know how to build task 'cucumber:build_validation_init_client_proxy' (See the list of available tasks with `rake --tasks`)
09:43:15  Did you mean?  cucumber:build_validation_init_proxy
```
> Fix init proxy rake command in BV

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This PR adds missing entries to the Uyuni BV files for the new DHCP/DNS module.
See https://ci.suse.de/blue/organizations/jenkins/uyuni-master-qe-build-validation-NUE/detail/uyuni-master-qe-build-validation-NUE/131/pipeline/30/
```bash
[2024-04-04T08:48:31.020Z] Terraform has been successfully initialized!
[2024-04-04T08:48:31.020Z] 
[2024-04-04T08:48:31.020Z] You may now begin working with Terraform. Try running "terraform plan" to see
[2024-04-04T08:48:31.020Z] any changes that are required for your infrastructure. All Terraform commands
[2024-04-04T08:48:31.020Z] should now work.
[2024-04-04T08:48:31.020Z] 
[2024-04-04T08:48:31.020Z] If you ever set or change modules or backend configuration for Terraform,
[2024-04-04T08:48:31.020Z] rerun this command to reinitialize your working …
```
> Uyuni BV: Add entries for private network

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This sets the correct registry for the server container again to be ready for Beta 2.
> BV 5.0: Enable correct container registry for Beta 2

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
This will also add the correct registry to the containerized proxy in the 5.0 BV environment.  Thank you, @srbarrios, for catching this!
Otherwise, sumaform would set it as
```jinja
{% if grains.get('container_repository') %}
{% set container_repository = grains.get('container_repository') %}
{% else %}
{% if 'uyuni' in grains.get('product_version') %}
{% set container_repository = 'registry.opensuse.org/systemsmanagement/uyuni/master/containers/uyuni' %}
{% elif '5.0' in grains.get('product_version') %}
{% set container_repository = 'registry.suse.de/devel/galaxy/manager/5.0/containers/suse/manager/5.0' %}
{% else %} # Head
{% set container_repository = 'registry.suse.de/devel/galaxy/manager/head/containers/suse/manager/5.0' %}
{% endif %}
{% endif %}
```
> BV 5.0: Enable correct container registry for proxy

- terracumber_config/tf_files/Uyuni-Master-K3S.tf
**Related PR**
- https://github.com/uyuni-project/sumaform/pull/1560
We need to change the default image if we are under a K3S deployment. In such case, for now, we will keep using Leap Micro 5.5, to be aligned with the server, as we encountered some technical issues there.
> K3s: Change the default image for server and proxy

- jenkins_pipelines/environments/common/pipeline-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
(Needs to be confirmed by running the pipeline with this change)
The previous regular expressions used to extract the images name from HTML might have been failing because of some incorrect escape characters.
This PR addresses the issue by introducing a slight refactor to avoid an HTTP call and using a different (hopefully more readable) RegEx.
Given that this pipeline definition is specifically for AWS BV, I think we can also make the RegEx more restrictive and have `EC2-Build` in it.
> BV-AWS: fix AMI images RegEx

- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
aa:b2:93:02:01:xx -> aa:b2:93:04:05 in Provo, to avoid false positives from MAC detector
> Avoid duplicate MACs between NUE and PRV

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
Related to
- https://github.com/SUSE/spacewalk/issues/23586
In the BV pipelines, defines an additional boolean parameter allowing to run separate stages for the products and Salt migration test - the latter runs on a dedicated SLES 15 SP 5 minion.
> BV: Add products and Salt migration tests stages

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
Hopefully fixes the following for the 5.0 BV in NUE:
```bash
[2024-04-17T12:12:28.044Z] module.slemicro53-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec):       Result: False
[2024-04-17T12:12:28.044Z] module.slemicro53-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec):      Comment: Parent directory not present
[2024-04-17T12:12:28.044Z] module.slemicro53-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec):      Started: 14:12:27.292446
[2024-04-17T12:12:28.044Z] module.slemicro53-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec):     Duration: 2.781 ms
[2024-04-17T12:12:28.044Z] module.slemicro53-minion.module.minion.module.host.null_resource.provisioning[0] (remote-exec): …
```
> QE: Do not use Salt bundle by default in 5.0 BV

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
Fixes
```
Scenario: Activate the branch network on the proxy
Then the "dhcp_dns" host should be present on private network
```
> Add DHCP and DNS server to private network

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
Currently, deploying sle15sp5s390_sshminion is failing with this error : 
```
13:51:06  [31m│[0m [0mGot error: HTTP status: 409, body: {"overallRC": 8, "modID": 1, "rc": 400,
13:51:06  [31m│[0m [0m"rs": 8, "errmsg": "Failed to create userid 'S43SSNUE'. SMT error: SMT
13:51:06  [31m│[0m [0mrequest failed. RequestData: 'makevm S43SSNUE directory LBYONLY 2G G --cpus
13:51:06  [31m│[0m [0m1 --profile osdflt --maxCPU 32 --maxMemSize 64G --setIniStandbyRem
13:51:06  [31m│[0m [0m--logonby guest --ipl 0100 --commandSetShare \"RELATIVE 100\"', Results:
13:51:06  [31m│[0m [0m'{'overallRC': 8, 'rc': 400, 'rs': 8, 'errno': 0, 'strError': 'ULGSMC5400E
13:51:06  [31m│[0m [0mImage or profile name already defined', 'response': ['(Error) ULTVMU0300E
13:51:06  [31m│[0m [0mSMAPI API failed: Image_Create_DM, …
```
> Remove sles15sp5 ssh minion from NUE 43 BV deployment

- terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars
Using Leap 15.5 seems to break the CI as the proxy host couldn't be bootstrapped due to broken repo. Trying SLE 15 SP4 instead to unblock PR test.
> Use SLES 15-SP4 for PR CI in Provo

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
It does not make sense to keep deploying Uyuni BV with non-containerized components.
So, this PR converts them to containerized components.
> BV: Convert Uyuni BV to Uyuni containerized

- terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars
This reverts commit c140ee6069786241c9dc235600b0f36d05993bcd.
This doesn't work as `uyuni-tools` are not available for this SLE version: reverting
> Revert "Use SLES 15-SP4 for PR CI in Provo"

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
As the title implies, these stages have been moved to their own function and some issues with permissions and concurrency have been fixed.
> Fix and move products and client migration stages to a separate function

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-saltstack-leap154
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-saltstack-leap155
- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Saltstack-Leap154.tf
- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Saltstack-Leap155.tf
The goal is to be able to run the Salt Shaker tests after build finished in `systemsmanagement:saltstack` for OpenSUSE Leap 15.4 and OpenSUSE Leap 15.5.
Part of https://github.com/SUSE/spacewalk/issues/23286
> Add pipelines for OpenSUSE Leap testing in Salt Shaker

- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Next-SLMicro60-Bundle.tf
- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Next-SLMicro60.tf
- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Testing-SLMicro60-Bundle.tf
- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Testing-SLMicro60.tf
The SLMicro60 instances for Salt Shaker need to be rebooted after the deployment, so we need the IP address to be preserved after the reboot so terracumber is able to connect to the deployed instance and trigger the Salt Shaker execution.
The necessary configuration for dhcp and bind was made here: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/895
> Salt Shaker: Define static MAC address for SLMicro60 instances

- jenkins_pipelines/environments/common/pipeline-salt-shaker.groovy
When running the Salt Shaker pipeline on SLMicro 6.0, we pass a `testsuite_dir` parameter to the pipeline in order to set `--directory` parameter to `salt-test` execution, in order to read the testsuite from a custom "rw" directory, but we were missing to propage the corresponding `--package-flavor` param in these cases, so the correct Python interpreter is used when running the testsuite.
> Salt Shaker: Select proper package flavor when passing 'testsuite_dir' param

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-slmicro60
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-slmicro60-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-slmicro60
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-slmicro60-bundle
Apparently, testsuite execution on SLMicro 6.0, particurly the integration tests, are taking much longer to complete than in SLE, and the default 3 hours timeout is reached by our Jenkins jobs.
The tests are not stuck, but they are progressing quite slowly. We still need to debug this further but this PR increases the timeout from 3 to 6 hours trying to get at least one complete execution of the tests.
> Salt Shaker: Temporary increase timeout for SLMicro 6.0 to allow testsuite to finish

- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
As the title implies, adds entries in 5.0 BV for a dedicated SLES 15 SP5 minion on which to test migration from OS Salt to Salt bundle
> 5.0 BV: add Salt migration minion

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-saltstack-leap155
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-saltstack-tumbleweed
- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Saltstack-Tumbleweed.tf
Add Tumbleweed testing pipelines for Salt Shaker and also fix the triggers in the Leap pipeline for the classic Salt package in `systemsmanagement:saltstack`.
> Add Tumbleweed testing pipelines in Salt Shaker

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-slmicro60
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-next-slmicro60-bundle
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-slmicro60
- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-slmicro60-bundle
After fixing the root cause of the performance drop for SLMicro60 tests, included in https://github.com/openSUSE/salt/pull/654, this PR just sets back the timeout for Salt Shaker SLMicro60 jobs to 3 hours
> Salt Shaker: Reduce timeout value for SLMicro60 jobs

- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Add SLE Micro 6.0 minions to BV envs.
~Missing MAC addresses in tf files.~ added
TODO: Verify that the suffixes in the json script are correct.
~The test is failing because [this PR](https://github.com/uyuni-project/sumaform/pull/1583) is not yet merged and the slemicro60 module is still unknown~
The test is failing because the sumaform states are not implemented properly for these variables: helm_chart_url, runtime, container_repository, container_tag
> Add SLE Micro 6.0 minions to BV envs

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
To avoid having different registries in proxy and server, declare the required values on both.
> Define containers registry for the proxy

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-saltstack-tumbleweed
Fix a wrong `tf_file` parameter for Salt Shaker test suite for openSUSE Tumbleweed.
> Fix wrong `tf_file` parameter for Salt Shaker test suite for TW

- terracumber_config/tf_files/salt-shaker/Salt-Shaker-Saltstack-Tumbleweed.tf
Avoid trying to install Salt Bundle for openSUSE Tumbleweed.
> Do not install Salt Bundle when running the Salt Shaker test suite in Tumbleweed.

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Otherwise, the bootstrap will fail.
> SL Micro 6.0: Deploy using install_salt_bundle = false, as we do for SLE Micro

- jenkins_pipelines/environments/manager-TEST-Ion-acceptance-tests
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
We don't need the traditional client at this time, but it would be good to have a widely available SLE Micro 5.5 instance.
> Ion replace trad client with slem

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
Disable liberty 9 again, it still does not deploy
```
[2024-06-20T14:24:35.559Z] module.liberty9-sshminion.module.sshminion.module.host.
null_resource.provisioning[0] (remote-exec): Error: Cannot find venv-salt-call or salt-call on the system
```
> Disable liberty 9 again, it still does not deploy

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
- jenkins_pipelines/scripts/tests/test_maintenance_json_generator.py
Fixes https://github.com/SUSE/spacewalk/issues/24615
The things that this PR does:
> Add liberty 9 to json generator and fix proxy repos

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
Related to https://github.com/SUSE/spacewalk/issues/24233
Depends on https://github.com/uyuni-project/uyuni/pull/8989 and its  4.3 backport https://github.com/SUSE/spacewalk/pull/24679
Execute the migration stages using a Rake run set instead of the final feature file.
This allows to use the `cucumber:` namespace, which is responsible for creating and collect tests results.
> QE: use Rakefiles for BV migration stages

- terracumber_config/tf_files/SUSEManager-4.3-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
* fix hypervisor for 5.0 NUE refenv
(was in Provo, my bad)
* move hypervisor of 4.3 NUE refenv from suma-03 to suma-02
rationale: align with other refenvs, we already have many things on suma-03
* align containers registry of 5.0 NUE refenv with 5.0 NUE acceptance
(was identical to 5.0 BV)
> Various fixes for reference environments

- jenkins_pipelines/environments/manager-5.0-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-5.0-dev-acceptance-tests-PRV
Add 5.0 acceptance tests pipelines
For the moment I keep the @scope_traditional_client and @scope_containerized_proxy in the pipelines. I will create a card to remove them later.
> Add 5.0 acceptance tests pipelines

- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
CentOS 7 reached EOL on the 30th June 2024.
This prevents 4.3 CI pipelines from deploying.
As a temporary measure, we'll use a Rocky8 minion before attempting to move all CIs pipelines to Rocky9.
> Replace CentOS 7 (EOL) with Rocky8 in 4.3 CI

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
During my BV testing for 4.3 NUE, I had all my clients failing during bootstrap. This fail was related to the events taking up to 700 seconds. Currently the default timeout is set to 500 seconds for BV. I think this timeout is correct for everything except the client bootstrap ( the server can be slow at that time ).
That's why I added a temporary default timeout of about 800 for the client bootstrap stage ( I prefer to keep a ratio from default timeout if we need to change it later ).
Also, the catch timeout method should not be needed anymore with the last server configuration. And I think this solution is bringing more problems than it solves. ( screenshot not available sometime when timing out ).
That's why I'm disabling this method for all the pipelines. Let's see if we see those …
> BV: increase default timeout during client boostrap and disable the catch timeout method

- jenkins_pipelines/manager_prs/tests_files/rubocop.sh
- jenkins_pipelines/uyuni_prs/tests_files/rubocop.sh
This adds the RuboCop version as output for our RuboCop CI checks, which helps debugging issues in the future.
```bash
sumadocker5:/var/lib/jenkins/workspace/manager-prs-ruby_rubocop-pipeline # rubocop.ruby2.5 -v
0.84.0
```
> Add RuboCop version output

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
During BV, sles15sp5s390 bootstrap is always failing because the bootstrap repository is missing for this architecture.
The issue is cause by the fact that sles15sp5 x86_64 arch and s390 arch are sharing the same bootstrap repository.
When the testsuite create the bootstrap repository, it will always flush the directory before generate the new bootstrap repository. @Bischoff  changed the create bootstrap step definition to be able to remove the flush option but this option is not used during create bootstrap stage in BV.
On uyuni side, we changed the create bootstrap feature so sles15sp5 x86_64 flush the directory and then sles15sp5s390 doesn't flush it.
We now need to make sure sles15sp5 x86_64 is creating his bootstrap repository before sles15sp5s390.
To do so, I'm using the node …
> BV : Create bootstrap stage : synchronize s390 minion with there x86_64 equivalent

- terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf
Fix SLE 5.0 testsuite url because we add /server at the end from sumaform and this was it was double and it was invalid.
> Fix SLE 5.0 testsuite url

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
In 4.3 BV, salt-migration is always failing to bootstrap. I was able to fix the issue by rebooting venv-salt-minion service but I was surprise we were using venv-salt-minion and not OS salt.
From my understanding, we want to bootstrap this minion using salt and then do the migration ? 
I need some feedback from @NamelessOne91.
If we want to bootstrap using salt, those changes will fix the deployment.
If we don't specify the `install_salt_bundle`, it will be set to `true` by default.
With `auto_connect_to_master` set to true and `install_salt_bundle` set to true, we will bootstrap the minion using venv-salt-minion  :
https://github.com/uyuni-project/sumaform/blob/676c3aaacd724ef454f6da2bcad9f3129e76591d/salt/minion/init.sls#L50-L81
> Don't use the default venv-salt-minion for salt migration minon

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Fixes
- renderning error:
```bash
[2024-08-14T10:15:53.058Z] module.sles15sp5s390-minion.null_resource.provisioning (remote-exec): local:
[2024-08-14T10:15:53.058Z] module.sles15sp5s390-minion.null_resource.provisioning (remote-exec):     Data failed to compile:
[2024-08-14T10:15:53.058Z] module.sles15sp5s390-minion.null_resource.provisioning (remote-exec): ----------
[2024-08-14T10:15:53.058Z] module.sles15sp5s390-minion.null_resource.provisioning (remote-exec):     Rendering SLS 'base:repos' failed: Jinja error: argument of type 'NoneType' is not iterable
[2024-08-14T10:15:53.058Z] module.sles15sp5s390-minion.null_resource.provisioning (remote-exec): Traceback (most recent call last):
[2024-08-14T10:15:53.058Z] module.sles15sp5s390-minion.null_resource.provisioning (remote-exec):   File …
```
> Add missing `product_version` to s390 Minions

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Fixes the Salt bundle for SLE Micros in the Uyuni BV.
> Fix Salt bundle for SLE Micros in the Uyuni BV

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
Add the option to specify mi IDs in a file instead of providing them directly on the command line.
File name : mis_12082024
Content : 
```
35198
32007
35176
34880
35142
35177
35114
```
Command : `maintenance_json_generator.py -f mis_12082024`
> Add possibility to use file to declare the sle update reference number

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
Wrong MAC addresses for ARM clients in Provo (probably my bad, I probably forgot to update at last renumbering in infra)
> Wrong MAC addresses for ARM clients in Provo

- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This PR
- ~fixes the main disk image size~
- removes the CentOS 7 client
- explicitly defines the server OS image version
- removes `catch_timeout_message = false` from the controller
for the Uyuni BV.
> Fixes for the Uyuni BV

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
To be able to use directly the minionList to remove the disable minions from the deployment, rename the module names to match the testsuite tag.
https://github.com/SUSE/spacewalk/issues/25063
> Rename module to match testsuite minion tags.

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
When nodes were disable in the minion list, they were still check by the sanity check
Correctly unset the disable nodes during sanity check stage.
> Unset disable clients before sanity check

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
Minion naming through the project is not consistent. Those differences complexify the use of script and increase the difficulty to add new minions.
Those naming issue are mainly for BV.
Rename main.tf ref modules to match minion names in testsuite.
> Rename build validation 5.0 PRV modules

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf
Minion naming through the project is not consistent. Those differences complexify the use of script and increase the difficulty to add new minions.
Those naming issue are mainly for BV.
Rename main.tf ref modules to match minion names in testsuite.
Related to : https://github.com/SUSE/spacewalk/issues/25098
> Rename build validation AWS modules

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
https://github.com/SUSE/spacewalk/issues/25032
We want the output of the script to have a predictable structure.
Adding this parameter to the **json.dump** function call should take care of it
> Order keys in the produced JSON file

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
Don't merge before @Bischoff  go. Those changes are going to force terraform to redeploy ( and so delete server )
Minion naming through the project is not consistent. Those differences complexify the use of script and increase the difficulty to add new minions.
Those naming issue are mainly for BV.
Rename main.tf ref modules to match minion names in testsuite.
> Rename build validation 4.3 NUE modules

- terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf
Use latest tag in SLE testsuite containers because otherwise it's trying 5.0.0 and the MI registry of course doesn't have this.
> Use latest tag in SLE testsuite containers

- terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf
This url works, the mgradm appends the namespace end, but mgrpxy doesn't.
> Fix url for proxy registry in SLE

- terracumber_config/tf_files/tfvars/PR-testing-uyuni.tfvars
We need to use the micro version of openSUSE Leap. This is what it is expected and what we have already in the "podman pipeline".
Otherwise, we would need to install NetworkManager, which is not in the openSUSE Leap "non-micro" version.
> Fix proxy in PR testing

- terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
Do not specify completely the image name, let mgradm and mgrpxy choose
> Use shorter registry identifiers

- terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
5.0 Reference environment uses `5.0-nightly` as `product_version`. Therefore, we also should use the correct container URLs for it.
> Use correct container URLs for 5.0 reference CI pipelines

- terracumber_config/tf_files/PR-testing-template.tf
... so we do not lose 2.5 minutes waiting for a DHCP address on the containerized proxy
> Add DHCP-DNS VM to tests on PRs

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
Don't merge before @nodeg go. This change will trigger a server redeployment by default.
Minion naming through the project is not consistent. Those differences complexify the use of script and increase the difficulty to add new minions.
Those naming issue are mainly for BV.
Rename main.tf ref modules to match minion names in testsuite.
> Rename build validation uyuni NUE modules

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
We were injecting and triggering a script file as it was in the host.
But in the case of a containerized product, we first need to copy that script inside the container, then we can trigger it through mgrctl.
> Refactor to support set custom header in both standalone and containerize versions

- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
openSUSE 15.4 is EOL since the end of 2023. See [en.opensuse.org/Lifetime](https://en.opensuse.org/Lifetime)
> Remove openSUSE Leap 15.4 due to EOL

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
Rename hostname to match hostname in minion list 
```
160  IN PTR suma-bv-43-ctl.mgr.prv.suse.net.
161  IN PTR suma-bv-43-srv.mgr.prv.suse.net.
162  IN PTR suma-bv-43-pxy.mgr.prv.suse.net.
163  IN PTR suma-bv-43-monitoring.mgr.prv.suse.net.
164  IN PTR suma-bv-43-build-sles12sp5.mgr.prv.suse.net.
165  IN PTR suma-bv-43-build-sles15sp4.mgr.prv.suse.net.
```
become
```
160  IN PTR suma-bv-43-controller.mgr.prv.suse.net.
161  IN PTR suma-bv-43-server.mgr.prv.suse.net.
162  IN PTR suma-bv-43-proxy.mgr.prv.suse.net.
163  IN PTR suma-bv-43-monitoring.mgr.prv.suse.net.
164  IN PTR suma-bv-43-sles12sp5-build.mgr.prv.suse.net.
165  IN PTR suma-bv-43-sles15sp4-build.mgr.prv.suse.net.
168  IN PTR suma-bv-43-sles15sp6-clientent.mgr.prv.suse.net.
169  IN PTR …
```
> Update names in BV NUE 43

- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
... with the hope to have time to debug it
> Re-enable liberty 9

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
After discussion about the minion renaming, we decided to see sshminion as one word without seperation.
Rename modules names and references to change ssh_minion to sshminion.
Update the minion list to use sshminion.
Update nodeHandler to not convert sshminion into ssh_minion.
Move the changes from https://github.com/SUSE/susemanager-ci/pull/1310 into this PR to avoid conflicts
Changes tested during https://ci.suse.de/blue/organizations/jenkins/manager-4.3-qe-build-validation-NUE/detail/manager-4.3-qe-build-validation-NUE/355/pipeline
> Rename ssh_minion for sshminion and change nodeHandler behavior.

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage
We need to use "mgrctl exec" to restart tomcat inside the container
> fix tomcat restart in uyuni-master-dev-acceptance-tests-code-coverage

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage
unzip is not installed in the server container. Let's unzip it at the host and copy that to the volume mapped to /var/cache
gzip can't uncompress .zip files.
> coverage pipeline: fix unzip

- jenkins_pipelines/environments/salt-shaker/manager-salt-shaker-products-testing-debian11-bundle
In an attempt to narrow down the failure of the debian11 execution pipeline, we can modify the default execution schedule. If the pipeline still fails, this excludes CI machine failures due to maintenance windows.
> Modify debian11 salt shaker pipeline execution schedule

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
This should solve https://github.com/SUSE/spacewalk/issues/25032 
Python sets guarantee the absence of duplicate values but the actual order of items at runtime is not guaranteed to stay the same. 
For lists the reverse is true.
Given the same inputs, we want each run to produce exactly the same JSON output so we'll to stick with lists and make sure through other means that we do not insert duplicate values in the dictionaries.
> Replace sets with lists as values for tools dictionaries

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
5.0 BV PRV is currently because of this error: 
```
Error: Can't retrieve base volume with name 'suma-bv-50-libertylinux9o': virError(Code=50, Domain=18, Message='Storage volume not found: no storage vol with matching name 'suma-bv-50-libertylinux9o'')
```
This error is caused by not declaring the image at the base level and then using it at the module level.
Correctly declare this images and base for all minion in 5.0 BV PRV.
> Add image declarations to different bases for 5.0 BV PRV

- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
This PR adds support for Ubuntu 24.04. Part of SUSE/spacewalk#23851.
Continuation of #1354 (Dominik absent)
Note: there is no ubuntu 24.04 support on 4.3.
> Add support for Ubuntu 24.04 in BV

- jenkins_pipelines/environments/common/pipeline.groovy
This PR change (**ONLY in pipeline.groovy for now**) the output of the terraform apply command to make it more readable.
Example:
Previous output:
```
[2024-09-30T08:07:09.425Z] Resource instance example_resource has been created.
[2024-09-30T08:18:36.562Z] module.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): <some_random_commands>
```
New output:
```
[08:07:09] Resource instance example_resource has been created.
[08:18:36] cucumber_testsuite.controller (remote-exec): <some_random_commands>
```
> Filter the output of the terraform apply command to make it more readable

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
Align 5.0 BV pipeline to 4.3 BV pipeline.
By default, we assume that client is using the salt-bundle and so venv-salt-minion is going to be installed during cloud init and also during testsuite requirement high-state.
- `additional_packages = ['venv-salt-minion']` value is not necessary because this package is installed by default.
- `install_salt_bundle` is set to True by default in sumaform and should only be set when we want to use pure salt ( like for salt-migration-minion ). 
- Use separate disk from main disk / repository / pgsql ( as recommended in documentation and done in 4.3 and uyuni )
I supposed this declaration is coming from CI example where we need to set install_salt_bundle to true because the cucumber module is setting this value to false by default. I think this behavior …
> Remove unuse references to venv-salt package and use sperate disks for server for 5.0 BVs

- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Repo synchronization is failing for uyuni BV because of disk space shortage.
```bash
uyuni-bv-master-server:/var/lib/containers/storage # df -h
Filesystem                                   Size  Used Avail Use% Mounted on
devtmpfs                                     4.0M  4.0K  4.0M   1% /dev
tmpfs                                         20G   92K   20G   1% /dev/shm
tmpfs                                        7.9G  1.2M  7.9G   1% /run
tmpfs                                        4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/vda3                                     15G  2.0G   13G  14% /
/dev/vda3                                     15G  2.0G   13G  14% /root
/dev/vda4                                    5.1G  4.6G  106M  98% /var
overlay                                      5.1G  4.6G  106M …
```
> Increase main disk size for uyuni BVs

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
I align the minionList name with the module names in CI.
Unfortunately, the rake task file are still named with the version sle1X and not sles1X.
I want to move those tags to sles1X too in the testsuite project but it will require more time.
To fix this issue, add a temporary variable nodeTag to use the correct rake task file name for sle1X minion.
>  add a temporary variable nodeTag to use the correct rake task file name for sle1X minion

- terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
After the changes made for sumaform with https://github.com/uyuni-project/sumaform/pull/1713, we can now only declare product_version at the base level and remove it from the individual modules.
> Move product_version to base level.

- jenkins_pipelines/environments/common/pipeline.groovy
Reverts SUSE/susemanager-ci#1395
This change doesn't catch errors on terraform deployments.
Let's revert it now, and think a fix later.
> Revert "Filter the output of the terraform apply command to make it more readable"

- jenkins_pipelines/manager_prs/tests_files/rubocop.sh
Manager-4.3 branch will for now use Ruby 2.5, while on Manager-5.0 we want to start using Ruby 3.3, therefore the Rubocop version will change accordly.
It means we need to handle both versions of Rubocop and Ruby at same time.
This PR improves the Rubocop version that will be triggered depending the Ruby version targeted.
> Dinamically select the right Rubocop version for each Ruby version

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
Add sl micro 60 staging and remove hardcoded 50 server proxy
The SL Micro 6.0 is supported for both 4.3 and 5.0 so no need to differentiate between versions.
~This is still a draft because I am looking at missing proxy MIs for last time.~ [see here](https://github.com/SUSE/spacewalk/issues/25035#issuecomment-2402667307) for why I didn't change anything for proxy
Fixes https://github.com/SUSE/spacewalk/issues/25035
> Add sl micro 60 staging remove hardcoded 50 server proxy

- jenkins_pipelines/manager_prs/tests_files/rubocop.sh
We must adapt sumadockers to support both Rubocop versions coming from different Ruby versions.
Before we have this done, let's skip the Rubocop check for Ruby 3.3
For more context follow this thread https://suse.slack.com/archives/C02EWMAB7QV/p1728486959198399
> Temporary skip rubocop tests for Ruby 3.3

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Remove all parameters not use during deployment. Either it's not used during the salt states ( example server_configuration without auto connect to master ) or default value is true ( venv-salt-bundle install ).
The idea is to simplify our BV description and later create a common template.
Depends on: https://github.com/uyuni-project/sumaform/pull/1736.
I didn't impact 4.3 for stability.
> Remove unuse parameters for uyuni and 5.0 BV pipelines

- jenkins_pipelines/manager_prs/tests_files/rubocop.sh
- jenkins_pipelines/uyuni_prs/tests_files/rubocop.sh
We can't install two Rubocop versions through zypper, as they require different Ruby versions and that cause conflicts.
So instead, we will be using these rubocop containers from DockerHub.
> Run Rubocop from a container

- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
Card: https://github.com/SUSE/spacewalk/issues/24758
Use the variables defined in https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/973
> Add Redis credentials via Sumaform node variables

- .github/workflows/sumaform-validation.yml
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-sle-update-NUE
- jenkins_pipelines/environments/manager-5.0-qe-sle-update-PRV
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Currently, when we have a new container image, we need to modify main.tf.
Create a variable for it and make it accessible at Jenkins level.
Related to: https://github.com/SUSE/spacewalk/issues/25212
> Make container repository configurable

- jenkins_pipelines/environments/manager-5.0-qe-sle-update-NUE
- jenkins_pipelines/environments/manager-5.0-qe-sle-update-PRV
We should be using the latest available released container from the registry for SLE, and we can overwrite it as we want with the new jenkins parameter. This registry currently works and deploys. The previous was not until the MU was ready and would not after it was released. So this with the latest tag and the server image from mgradm works now. Tested on NUE deployment
> Add 5.0 registry for both SLE envs

- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
Append correct path for registry in SLE and BV. I don't want to change the default value in the jenkins because this is used for the server and there the rest of this path (which is part of the image name basically) is hardcoded in the product code. But not for the proxy product code. I only tested this on SLE not BV but since it's common code I think it is needed there as well.
> Append correct path for registry in SLE and BV

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
Card https://github.com/SUSE/spacewalk/issues/25577
With the new mgrpxy version ( > 0.1.21 ), we don't need the /suse/manager/5.0/x86_64 anymore for proxy_containerized.
> Changing the container repository path for mgrpxy

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
https://github.com/SUSE/spacewalk/issues/25575#issuecomment-2429292573
Regarding Proxy host deployment, if we just add the additional repositories in the main.tf, through Terracumber and the placeholder (all already implemented), then the mgrpxy version it's just the updated version from the MI.
Example main.tf:
```
provider "libvirt" {
uri = "qemu:///system"
}
terraform {
required_version = "1.0.10"
required_providers {
libvirt = {
source = "dmacvicar/libvirt"
version = "0.6.3"
}
}
}
module "base" {
source = "./sumaform/modules/base"
cc_username = var.SCC_USER
cc_password = var.SCC_PASSWORD
name_prefix = "oscar-"
use_avahi   = false
domain      = "mgr.suse.de"
images = ["slemicro55o"]
testsuite          = true
provider_settings = {
network_name = null
pool = "obarrios_disks"
bridge = …
```
> Proxy additional repos placeholder on BV 5.0

- jenkins_pipelines/environments/uyuni-prs-ci-tests
As otherwise it tries to load the groovy file from the wrong directory.
> Loading the groovy file from outside the node

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
In our server containerized, we don't have a separated partition for the new overlay, located in `/var/lib/containers/storage/overlay`, that's causing a full disk issue in `/var`.
For now, I'm fixing it by increasing the main disk size, which automatically will give more space to `/var` partition. [But ideally we should implement a new partition for the overlay through sumaform.](https://github.com/SUSE/spacewalk/issues/25719)
> Temporary incr. of main disk until we implement a partition for /var/lib/containers/storage/overlay

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-podman
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- Rename Uyuni Master components:
- Updates the names of Uyuni Master Podman NUE modules and hostnames to comply with the new standardized minion naming conventions, ensuring consistency across our infrastructure.
> Rename uyuni master podman nue modules and hostnames

- jenkins_pipelines/environments/manager-5.0-dev-acceptance-tests-NUE
- jenkins_pipelines/environments/manager-5.0-dev-acceptance-tests-PRV
- terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
> SUMA 5.0 - rename module names and remove configurations to use cucumber testsuite default values

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-PRV
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- Convert classic uyuni master to podman container
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/987
**Depends on https://github.com/uyuni-project/sumaform/pull/1662 but can be merge before. …
> UYUNI MASTER PRV - rename module names and remove configurations to use cucumber testsuite default values and convert to podman

- jenkins_pipelines/environments/manager-Head-dev-acceptance-tests-NUE
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- Convert classic uyuni master to podman container
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/987
**Depends on https://github.com/uyuni-project/sumaform/pull/1662 but can be merge before. …
> SUMA HEAD - rename module names and remove configurations to use cucumber testsuite default values

- jenkins_pipelines/environments/manager-4.3-infra-reference-NUE
- jenkins_pipelines/environments/manager-4.3-infra-reference-PRV
- terracumber_config/tf_files/SUSEManager-4.3-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-refenv-PRV.tf
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/988
> SUMA 4.3 - REFENV - rename module names and remove configurations to use cucumber testsuite default values

- jenkins_pipelines/environments/manager-5.0-infra-reference-NUE
- jenkins_pipelines/environments/manager-5.0-infra-reference-PRV
- terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/988
> SUMA 5.0 - REFENV - rename module names and remove configurations to use cucumber testsuite default values

- jenkins_pipelines/environments/uyuni-master-infra-reference-NUE
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/988
> UYUNI MASTER - REFENV - rename module names and remove configurations to use cucumber testsuite default values

- terracumber_config/tf_files/PR-testing-template.tf
> Revert to 0.6.3 for tests on PRs

- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
I made some adjustments to the Terraform configuration for the Test Ion environment. For example, now for the continerized server the configuration points to the proper registry. Other changes were made for it to be more similar to the HEAD NUE environment.
> Adjust Terraform environment for Test Ion

- jenkins_pipelines/environments/manager-TEST-Hexagon-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Ion-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Naica-acceptance-tests
- jenkins_pipelines/environments/manager-TEST-Orion-acceptance-tests
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf
Depends on: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/990
> Update all squad pipeline module names and hostnames

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
- terracumber_config/tf_files/SUSEManager-4.3-AWS.tf
- terracumber_config/tf_files/Uyuni-Master-AWS.tf
Align aws uyuni pipeline with the new module names to be compatible with the new cucumber testsuite module.
Use the new naming convention for the node deployment (route53 in AWS has been updated).
Remove useless venv-salt declaration.
Depends on https://github.com/uyuni-project/sumaform/pull/1662
> update aws hostname and modules

- terracumber_config/tf_files/Uyuni-Master-K3S.tf
Now that the kubernetes refactoring is merged in `main`, we can use the regular builds again.
> No more need to use cbosdonnat's packages for the kubernetes refactoring build

- terracumber_config/tf_files/PR-testing-template.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/tfvars/PR-testing-NUE-environments.tfvars
- terracumber_config/tf_files/tfvars/PR-testing-PRV-environments.tfvars
- terracumber_config/tf_files/tfvars/PR-testing-additionnal-repos.tf
Not removing it from the test projects since those could test 4.3 still. Each squad should decide what to do with it.
> Remove KVM host from HEAD and Master

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
Alike generated part for `slmicro60_minion` with reference to https://jira.suse.com/browse/MSQA-914
```json
"slmicro60_minion": {
"slmicro60_staging": "http://download.suse.de/ibs/SUSE:/ALP:/Source:/Standard:/1.0:/Staging:/Z/standard/"
},
```
The same should be done for the newly added `slmicro61_minion`.
Output after run:
```json
...
"slmicro61_minion": {
"slmicro61_staging": "http://download.suse.de/ibs/SUSE:/ALP:/Source:/Standard:/1.0:/Staging:/Z/standard/"
},
...
```
Full output here: https://github.com/SUSE/spacewalk/issues/24901#issuecomment-2612391085
> Adding staging repository to SL Micro 6.1 for BV

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
Follow-up of https://github.com/SUSE/susemanager-ci/pull/1520
Fixed iptables package was not shipped in a product increment yet.
> Re-add a workaround for ip6tables

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
The problem is that packages are numbered with lower values, forcing the need of --oldpackages
> Still fighting package updates

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
Can't use Leap 16.0 online repo because of GPG keys
> Can't use Leap 16.0 online repo because of GPG keys

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
Disable client tools that are not enabled yet in HEAD.
See https://github.com/uyuni-project/uyuni/pull/9743 : avoid starting to synchronize the "Manager beta client tools" that appear in the product tree, but are in fact the beta client tools for 5.0.
In fact, this setting does not seem to work. We had:
```
terracumber_config/tf_files/SUSEManager-Head-NUE.tf:      beta_enabled = true
```
but on the controller:
```
suma-ci-head-controller:~ # env | grep BETA
BETA_ENABLED=False
```
There is probably some bug in sumaform and/or terracumber, that should be fixed before we enable the beta client tools...
> Beta client tools are not ready yet

- jenkins_pipelines/environments/common/pipeline.groovy
Card: https://github.com/SUSE/spacewalk/issues/22434
Some time ago, we have the proxy initialized in a different stage.
Having the proxy at the same stage of the rest of the clients it impedes to bootstrap the clients in parallel. 
This PR refactors it, so we have again the proxy onboarding on its own stage, before initializing the clients on CI test suites.
This PR can't be merged without the refactors in 4.3, 5.0, master branches, to have different YAML file for the proxy features.
> QE: Have Proxy bootstrap on its own stage

- jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
- jenkins_pipelines/environments/qe-build-validation-cleaning-pipeline
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
To facilitate rerunning BV pipelines while also enabling testing of client tools for both versions 4.3 and 5.0, we need to push an updated `custom_repositories.json` file.
Currently, this file is only copied during the sumaform deployment, meaning there is no mechanism to update it without redeploying the controller.
To address this, a new feature was introduced in the cleaning pipeline. However, this feature has now been moved from the cleaning pipeline to the BV pipelines.
> Move force push custom repositories file from cleanup pipeline to BV pipelines

- jenkins_pipelines/environments/common/pipeline-pull-request.groovy
Proxy is required for the init client step but not declare in the PR pipeline.
Add  init proxy to PR pipeline script.
> Add proxy to PR testing

- README.md
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-AWS.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
Switch to Ubuntu 24.04 in CI/refenv 5.0/head/uyuni
Note: 5.0 done separately in 5.0 because of considerations on merging order: #1545
> Switch to Ubuntu 24.04 in CI/refenv 5.0/head/uyuni

- jenkins_pipelines/environments/common/pipeline-salt-shaker.groovy
As title describes, this PR just enables colorful output on the pytest execution, in order to have colors in the Jenkins jobs outputs.
> Salt Shaker: add colorful output for pytest executions

- jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
- jenkins_pipelines/scripts/test_environment_cleaner/delete_s390_clients.sh
The deletion of s390 clients using terraform destroy is failing due to the issue described in [#26502.](https://github.com/SUSE/spacewalk/issues/26502) This problem is currently blocking the BV cleanup pipeline and the ability to clean up the BV environment using Terraform.
Since a long-term solution is not expected soon, this PR introduces a temporary workaround to address the issue.
-   Introduces a new script, delete_s390_guest, to manually remove the s390 minion.
-  Removes s390 modules from the Terraform state file (tfstate) to prevent conflicts during environment cleanup.
-  Updates the cleanup pipeline to execute the new bash script before running Terraform commands.
-  This ensures the environment is properly cleaned and avoids the issue when invoking terraform destroy.
> Workaround s390 clients delete

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-code-coverage
Clients fail because they cannot be bootstrapped against proxy, due to non-existant proxy setup:
```
18:13:31  Scenario: Bootstrap a SLES minion                                # features/init_clients/sle_minion.feature:13
18:13:31  This scenario ran at: 2025-02-25 18:12:13 +0100
18:13:31  When I follow the left menu "Systems > Bootstrapping"          # 
...
18:13:31  Node: suma-codecov-proxy, OS Version: 5.5, Family: opensuse-leap-micro
18:13:31  And I select the hostname of "proxy" from "proxies" if present # features/step_definitions/navigation_steps.rb:461
18:13:31        Unable to find xpath "//*[contains(@class, 'data-testid-proxies-child__control')]" (Capybara::ElementNotFound)
18:13:31        ./features/step_definitions/navigation_steps.rb:171:in `/^I select "([^"]*)" from …
```
> uyuni-master-dev-acceptance-tests-code-coverage: Core Proxy stage is missing

- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
Path extension for Proxy should be no longer needed.
> Remove  proxy registry path extension in 5.0 SLE updates

- jenkins_pipelines/environments/common/pipeline-reference-new.groovy
The new proxy stage was missing for all the reference entvironments.
> fix: Add proxy stage to reference pipelines definition

- jenkins_pipelines/environments/common/pipeline-reference-new.groovy
```bash
[2025-02-28T14:37:27.091Z] + ./terracumber-cli --outputdir /home/jenkins/workspace/manager-Head-infra-reference-NUE/results --tf susemanager-ci/terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf --gitfolder /home/jenkins/workspace/manager-Head-infra-reference-NUE/results/sumaform --terraform-bin /usr/bin/terraform --logfile /home/jenkins/workspace/manager-Head-infra-reference-NUE/results/1812/testsuite.log --runstep cucumber --cucumber-cmd 'cd /root/spacewalk/testsuite; null rake cucumber:proxy'
[2025-02-28T14:37:27.091Z] 2025-02-28 15:37:27,070 - __main__ - INFO - Running command...
[2025-02-28T14:37:27.091Z] 2025-02-28 15:37:27,070 - INFO - Running command...
[2025-02-28T14:37:27.346Z] 2025-02-28 15:37:27,091 - INFO - Connected (version 2.0, client OpenSSH_8.4) …
```
> Fix proxy init for reference pipeline

- terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
IP range 10.146.*.* is on the second network (the one with dhcp2.mgr.suse.de), so we have to use bridge `br1`.
> Use correct bridge for x86 VMs

- jenkins_pipelines/environments/manager-5.0-qe-build-validation-AWS
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-paygo-AWS.tf
Adds to the 5.0 PAYGO AWS build validation pipeline the option to deploy a RHEL 9.X PAYGO minion.
> Add RHEL PAYGO minion to 5.0 PAYG BV pipeline

- terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-SLE-update-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-alternative-base-OS-NUE.tf
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
Move some test suites to `suma-10` and `suma-11`:
```
suma-05    42
suma-06    60
suma-bv-50          51
suma-continuous-bv   9 --> suma-11
suma-07   103
mlm-bv-51           49 --> suma-10
suma-bv-43          54
suma-08    53
suma-pr             39
suma-su              8 --> suma-11
suma-alt             4 --> suma-11
minima-mirror        1
kafka                1
```
> Move some testsuites to the new servers

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
Switch Uyuni and Head to large_deployment to see if that solves the issue with the session crashes. This should at least increase taskomatic threads etc.
If this does work then we will switch the rest of the CI maybe
> Switch Uyuni and Head to large_deployment

- jenkins_pipelines/environments/uyuni-master-dev-acceptance-tests-AWS
- jenkins_pipelines/scripts/test_environment_cleaner/test_environment_cleaner_program/TestEnvironmentCleaner.py
- terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-SLE-update-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-SLE-update-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-AWS.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-paygo-AWS.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-SLE-update-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-alternative-base-OS-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-paygo-AWS.tf
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-AWS.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
- terracumber_config/tf_files/local_mirror.tf
Follow up to https://github.com/SUSE/spacewalk/issues/26776
Somewhat related to https://github.com/SUSE/spacewalk/issues/26493
If possible, we should drop the use of old RSA keys and switch to a more secure algorithm such as ed25519.
This will also allow us to drop a few workarounds we have in place to make newer version of openSSH, shipped with some newer distros, accept RSA keys - see https://github.com/uyuni-project/sumaform/pull/1807
We already had one ed25519 AWS keypair, used on some pipelines.
I took care of adding the corresponding pub key to the bastion.
> Replace RSA SSH keys with ed_25519 ones

- jenkins_pipelines/environments/manager-5.1-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
- terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
Support Amazon Linux 2023 in 5.1, Head, and Uyuni BVs
This PR does NOT include the changes to the json generator
> Support Amazon Linux 2023

- jenkins_pipelines/environments/common/pipeline-build-validation-cleanup.groovy
During 5.0.4 client tools testing on 4.3, I attempted to use the cleanup pipeline to clean only the clients and test the 5.0.4 client tools.
However, the newer version of sumaform (from Git) was incompatible with the older sumaform deployment used in 4.3 BV results/sumaform. As a result, the controller was redeployed but became incompatible with the server and minions.
This issue is expected to occur occasionally, as we sometimes retain deployments for extended periods while sumaform continues to evolve.
To prevent this in the future, the cleanup pipeline will no longer clone sumaform from Git. Instead, it will use the version provided by the targeted project.
If a more recent sumaform version is needed, we’ll either need to update it at the project level or redeploy the environment …
> Cleaning bv pipeline - use sumaform from targeted project

- terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-build-validation-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-build-validation-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
salt bundle is now available for slmicro 6.0 and slmicro 6.1.
Using classic salt seems to be broken for slmicro 6.1.
Update all the BV pipelines to use salt bundle for those two minions by removing the salt_bundle value (default true).
> Use salt bundle 61

- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
Seen in the DNS queries:
```
2025-05-09T06:14:00.905210+02:00 dhcp named[29159]: timed out resolving 
'suma-continuous-bv-50-proxy.mgr.suse.de.prg2.suse.org/A/IN': 10.144.53.53#53
```
The name of the proxy was incorrect.
> Remainder of renamings

- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
This pull request updates the Terraform configuration files to disable the `beta_enabled` flag across multiple modules.
> Beta disabled in Head

- terracumber_config/tf_files/PR-testing-template.tf
- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-4.3-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-Test-Vega-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-refenv-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hexagon-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Hub.tf
- terracumber_config/tf_files/SUSEManager-Test-Ion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Naica-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Orion-NUE.tf
- terracumber_config/tf_files/SUSEManager-Test-Vega-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-K3S.tf
- terracumber_config/tf_files/Uyuni-Master-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
- terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
In order to mitigate our infrastructure issue, we want to stop using the HTTP Proxy in most of our test suites. We will keep it only on Head.
Related Slack thread: https://suse.slack.com/archives/C02EWMAB7QV/p1749637044417959
> Commenting server_http_proxy except in Head

- terracumber_config/tf_files/Uyuni-Master-AWS.tf
See https://github.com/uyuni-project/sumaform/pull/1858  - AMIs for Leap 15.5 are no longer available. We already did the switch to 15.6 and should not need them anyway.
The attached volume for AWS CI Server needs to be increased as it is currently insufficient to sync Leap 15.6, SLES 15 SP4, Rocky8 and Ubuntu 24.04
> Increase server volume size

- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
This PR introduces Jenkins parameters that allow you to select the product version and base OS for both the proxy and the server.
With these changes, you can now deploy 5.1 or Head on top of either SLE Micro 6.1 or SLES 15 SP7.
To use this functionality, you need to specify the following four parameters:
- Product version for the Uyuni client tools
- Base OS (default: slmicro6.1)
- server_container_repository: Container registry for the server (differs between 5.1 and Head)
- proxy_container_repository: Container registry for the proxy (differs between 5.1 and Head)
This enhancement makes it easier to switch between product versions without needing additional pull requests.
> Add possibility to choose product version/base OS  Continuous BV

- terracumber_config/tf_files/MLM-5.1-build-validation-NUE.tf
- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-build-validation-PRV.tf
SP1 image lacks cloud-init and is unusable.
We will probably switch to another openEuler version after 5.1. In the meantime, we disable automated tests in BV.
Not removing from infra, sumaform, pipelines, mirrors,  test suite code, etc. to let people experiment with openeuler and to make revival easier.
> Disable openeuler until we find a solution for the broken image

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
- jenkins_pipelines/scripts/json_generator/repository_versions/__init__.py
- jenkins_pipelines/scripts/json_generator/repository_versions/v43_nodes.py
- jenkins_pipelines/scripts/json_generator/repository_versions/v50_nodes.py
- jenkins_pipelines/scripts/json_generator/repository_versions/v51_nodes.py
The JSON generator currently only supports generating custom repository JSON for a single host type (either slemicro55 or slmicro61) when using versions 5.1 or 5.0. This limits our ability to test or validate Uyuni tool repositories across multiple host types.
This PR adds support for generating custom repository JSON for multiple host types (e.g., slmicro61 and sles15sp7) when using version 5.1.
- The version argument now accepts a suffix (e.g., 51-slmicro61, 51-sles15sp7) to indicate which host variant should be used.
- This avoids introducing a separate --host argument, which would complicate logic and break backward compatibility, especially for version 4.3, which doesn’t need host-specific repositories.
- Only 5.1 variants are supported for now.
- Similar support for 5.0 variants …
> Add suport multihost json generator

- jenkins_pipelines/environments/common/pipeline-build-validation-aws.groovy
- jenkins_pipelines/environments/common/pipeline-build-validation.groovy
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-4.3-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-AWS
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-5.0-qe-build-validation-PRV
- jenkins_pipelines/environments/manager-5.1-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
During my BV testing, I will split my tests into separate runs (deploy -> reposync -> proxy -> etc).
Having only the build number make it complicated to manage so I started to rename the jobs.
Automatically update the  run name for BV run.
The name will be as follow:
<product_version>(_<base_os>|'') - <enabled stages>
If the names is too long because we run all the stages, it will just display: <BUILD_NUMBER>-<product_version>
I was thinking to also add a field that could be edited by us when running the test to specify for example the release version (5.0.14).
I also took the opportunity to fix how we handle the parameter `non_MU_channels_tasks_file` to make it easier to find.
Some groovy functions are blocked by jenkins so we need to use basic function.
> QoL: BV: Rename run with <version_OS> - <triggered options>

- terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
- terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
- terracumber_config/tf_files/SUSEManager-5.0-NUE.tf
- terracumber_config/tf_files/SUSEManager-5.0-PRV.tf
- terracumber_config/tf_files/SUSEManager-Head-NUE.tf
- terracumber_config/tf_files/Uyuni-Master-PRV.tf
- terracumber_config/tf_files/Uyuni-Master-podman.tf
Increase number of vCPUs on CI's controllers for two reasons:
* hope to increase performance
* hope to avoid Net::ReadTimeout issue
Supported by Maxime's tests and Eric's measurements.
> Increase number of vCPUs on CI's controllers

- terracumber_config/tf_files/SUSEManager-5.0-build-validation-paygo-AWS.tf
4 vCPU and 16 GB of RAM tends to feel quite slow when syncing multiple repositories and/or big ones.
Switching to the recommended 8 vCPU and 32GB instance.
> Increase AWS instance size for PAYGO servers

- jenkins_pipelines/environments/manager-5.1-qe-build-validation-NUE
- jenkins_pipelines/environments/manager-qe-continuous-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-NUE
- jenkins_pipelines/environments/uyuni-master-qe-build-validation-PRV
Remove resources not used, openeuler is not an option anymore and it's causing problems with the resource-cleaner in terracumber.
> Remove openeuler as an option from pipelines

- terracumber_config/tf_files/SUSEManager-continuous-build-validation-NUE.tf
Rename s390 guest in continuous BV to use 51 name instead of 50. The MACs are correct
> Rename s390 guest in continuous BV to use 51 name

- jenkins_pipelines/scripts/json_generator/maintenance_json_generator.py
- jenkins_pipelines/scripts/json_generator/repository_versions/v43_nodes.py
- jenkins_pipelines/scripts/json_generator/repository_versions/v50_nodes.py
- jenkins_pipelines/scripts/json_generator/repository_versions/v51_nodes.py
Do not overwrite server and proxy for 50 in json script.
The timeout is to try and speed the execution.
Added 4.3 LTS server and proxy (server confirmed, proxy not confirmed) and web scripting for 5.0
Tested with all versions with some SLE updates and none throw any errors and the 5.0 is not overwritten.
> Do not overwrite server and proxy for 50 in json script

- terracumber_config/tf_files/MLM-Head-refenv-NUE.tf
Depends on https://github.com/uyuni-project/sumaform/pull/1913
Enable syncing of OVAL data in the HEAD reference environment.
> Enable OVAL data synchronization in HEAD refenv
